// Module included in the following assemblies:
//
// assembly-tenant-guide.adoc

[id='managing-addresses-{context}']
= Managing addresses

{ProductName} is configured to support managing addresses using the {KubePlatform} command-line tools
and the {ProductName} Console. `Address` resources can be managed like any other {KubePlatform}
API resource using `{cmdcli}`.

Some address types also support changing the `plan` field: `queue`, `anycast` and `multicast`
address types in the `standard` address space support changing the plan as long as the new plan
does not exceed the allowed quota. For queues, addresses are dynamically migrated across brokers
which may cause reordering of messages.

== Example

[source,yaml,options="nowrap"]
----
include::../common/address-example1.yaml[]
----
<1> The address name must be prefixed with the address space name and a dot. Address names can only include alphanumeric characters.
<2> The address is the messaging address this address resource represents.
<3> The address type dictates the semantics of this address.
<4> The address plan describes the resource usage for the address.

include::../modules/proc-create-address-cli.adoc[leveloffset=+1]

include::../modules/proc-replace-address-cli.adoc[leveloffset=+1]

include::../modules/proc-create-address-console.adoc[leveloffset=+1]

