// This assembly is included in the following assemblies:
//
// assembly-service-admin-guide.adoc
[id='installing-{context}']
= Installing {ProductName}

ifeval::["{cmdcli}" == "kubectl"]

ifdef::OperatorSource[]
{ProductName} can be installed by applying the YAML files using the `kubectl` command-line tool, or by using the Operator Marketplace.
endif::OperatorSource[]

ifndef::OperatorSource[]
{ProductName} can be installed by applying the YAML files using the `kubectl` command-line tool.
endif::OperatorSource[]

include::../common/snip-prerequisites-kubernetes.adoc[]

include::../common/proc-download-procedure.adoc[leveloffset=+1]

include::../modules/proc-installing-using-bundle.adoc[leveloffset=+1]

ifdef::OperatorSource[]
include::../modules/proc-installing-using-olm.adoc[leveloffset=+1]
endif::OperatorSource[]

endif::[]
ifeval::["{cmdcli}" == "oc"]

ifdef::OperatorSource[]
{ProductName} can be installed by applying the YAML files using the `oc` command-line tool, by using
the Operator Marketplace, or by running the link:https://www.ansible.com/[Ansible^] playbooks.
endif::OperatorSource[]

ifndef::OperatorSource[]
{ProductName} can be installed by applying the YAML files using the `oc` command-line tool, or by running the link:https://www.ansible.com/[Ansible^] playbooks.
endif::OperatorSource[]

include::../common/snip-prerequisites-openshift.adoc[]

include::../common/proc-download-procedure.adoc[leveloffset=+1]

include::../modules/proc-installing-using-bundle.adoc[leveloffset=+1]

ifdef::OperatorSource[]
include::../modules/proc-installing-using-olm.adoc[leveloffset=+1]
endif::OperatorSource[]

include::../modules/proc-installing-using-ansible.adoc[leveloffset=+1]

endif::[]
