// Module included in the following assemblies:
//
// master.adoc

:parent-context: {context}

[id='managing-address-spaces-{context}']
= Managing address spaces

{ProductName} is configured to support managing address spaces using the
ifdef::Kubernetes[Kubernetes and]
OpenShift command-line tools.

== Minimal example

The minimal example shows the smallest set of options needed to create an `AddressSpace`.

[source,yaml,options="nowrap"]
.link:resources/address-space-example1.yaml[address-space-example1.yaml]
----
include::../common/address-space-example1.yaml[]
----
<1> The address space type can be either `brokered` or `standard`.
<2> The address space plan depends on the address space type and what has been configured by the {ProductName} admin.

== Advanced example

The advanced example show how you can configure the authentication service and endpoints of an `AddressSpace`.

[source,yaml,options="nowrap"]
.link:resources/address-space-example2.yaml[address-space-example2.yaml]
----
include::../common/address-space-example2.yaml[]
----
<1> The address space type can be either `brokered` or `standard`.
<2> The address space plan depends on the address space type and what has been configured by the {ProductName} admin.
<3> The authentication service type can be `none`, `standard` or `external`. External requires an additional field, `details`, including `host` and `port` information.
<4> The endpoints that must be configured for the `AddressSpace`.  Endpoints can specity either `messaging`, `console` or `mqtt` services. However, the `mqtt` service is supported for the `standard` address space type only.
<5> Expose the configuration of an endpoint. Endpoints can be kept internal to the cluster, or exposed using an OpenShift route or a load-balancer service.
<6> The certificate configuration can be used to specify how the endpoint certificate is provided.  The provider can be `selfsigned` (default), `wildcard` (requires it to be enabled by the {ProductName} admin), `openshift` (signed by the OpenShift cluster CA), or `certBundle` (base64-encoded PEM key and certificate).


:context: okd
:cmdcli: oc
:KubePlatform: OpenShift
include::../modules/proc-create-address-space-cli.adoc[leveloffset=+1]

:context: kube
:cmdcli: kubectl
:KubePlatform: Kubernetes
include::../modules/proc-create-address-space-cli.adoc[leveloffset=+1]

:context: {parent-context}
