// This assembly is included in the following assemblies:
//
// assembly-service-admin-guide.adoc
:parent-context: {context}

[id='infrastructure-configuration-{context}']
= Infrastructure configuration

{ProductName} creates infrastructure components such as routers, brokers, and consoles. These
components can be configured while the system is running, and {ProductName} automatically updates
the components with the new settings. The {ProductName} service operator can edit the {ProductName}
default infrastructure configuration or create new configurations.

Infrastructure configurations can be referred to from one or more address space plans. For more information
about address space plans, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#con-address-space-plans-messaging[Address space plans].

Infrastructure configuration can be managed for both `brokered` and `standard` infrastructure
using `BrokeredInfraConfig` and `StandardInfraConfig` resources.

include::../modules/con-brokered-infra-config.adoc[leveloffset=+1]

include::../modules/con-standard-infra-config.adoc[leveloffset=+1]

:context: {parent-context}

