// Module included in the following assemblies:
//
// master.adoc

:parent-context: {context}

[id='managing-address-spaces-{context}']
= Managing address spaces

{ProductName} is configured to support manipulating address spaces using the
ifdef::Kubernetes[Kubernetes and]
OpenShift command-line tools.

== Minimal configuration

The minimal configuration uses the defaults configured when installing {ProductName}.

[source,yaml,options="nowrap"]
.link:resources/address-space-example1.yaml[address-space-example1.yaml]
----
include::../common/address-space-example1.yaml[]
----
<1> The type of the address space can be either `brokered` or `standard`.
<2> The plan of the address space depends on the type and what has been configured by the {ProductName} admin.

== Advanced configuration

The advanced configuration allow you to configure the authentication service and endpoints of an
address space.

[source,yaml,options="nowrap"]
.link:resources/address-space-example2.yaml[address-space-example2.yaml]
----
include::../common/address-space-example2.yaml[]
----
<1> The type of the address space can be either `brokered` or `standard`.
<2> The plan of the address space depends on the type and what has been configured by the {ProductName} admin.
<3> The authentication service type can be either `none`, `standard` or `external`. External requires an additional field `details` with `host` and `port` information.
<4> The endpoints that should be configured for the `AddressSpace`.  Endpoints can point to either `messaging`, `console` or `mqtt` services (`mqtt` service is for `standard` address space type only).
<5> Expose configuration of an endpoint. Endpoints can be kept internal to the cluster, or exposed using an OpenShift route or a load balancer service.
<6> The certificate configuration can be used to select how the endpoint certificate is provided.  The provider can be `selfsigned` (default), `wildcard` (requires it to be enabled by the {ProductName} admin), `openshift` (Signed by OpenShift Cluster CA), or `certBundle` (base64 encoded PEM key and cert specified in the input).


:context: okd
:cmdcli: oc
:KubePlatform: OpenShift
include::../modules/proc-create-address-space-cli.adoc[leveloffset=+1]

:context: kube
:cmdcli: kubectl
:KubePlatform: Kubernetes
include::../modules/proc-create-address-space-cli.adoc[leveloffset=+1]

:context: {parent-context}
