apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleservices.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ConsoleService
    listKind: ConsoleServiceList
    singular: consoleservice
    plural: consoleservices
    categories:
    - enmasse
  validation:
    openAPIV3Schema:
      type: object
      description: ConsoleService creates a console that can be used by messaging tenants to manage EnMasse. This resource is created by the service administrator.
      properties:
        spec:
          type: object
          properties:
            discoveryMetadataURL:
              type: string
            certificateSecret:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            oauthClientSecret:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            ssoCookieSecret:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            ssoCookieDomain:
              type: string
            scope:
              type: string
            host:
              type: string
        status:
          type: object
          properties:
            host:
              type: string
            port:
              type: integer
            caCertSecret:
              type: object
              properties:
                name:
                  type: string

