/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	iotv1 "github.com/enmasseproject/enmasse/pkg/apis/iot/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIoTTenants implements IoTTenantInterface
type FakeIoTTenants struct {
	Fake *FakeIotV1
	ns   string
}

var iottenantsResource = schema.GroupVersionResource{Group: "iot.enmasse.io", Version: "v1", Resource: "iottenants"}

var iottenantsKind = schema.GroupVersionKind{Group: "iot.enmasse.io", Version: "v1", Kind: "IoTTenant"}

// Get takes name of the ioTTenant, and returns the corresponding ioTTenant object, and an error if there is any.
func (c *FakeIoTTenants) Get(name string, options v1.GetOptions) (result *iotv1.IoTTenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(iottenantsResource, c.ns, name), &iotv1.IoTTenant{})

	if obj == nil {
		return nil, err
	}
	return obj.(*iotv1.IoTTenant), err
}

// List takes label and field selectors, and returns the list of IoTTenants that match those selectors.
func (c *FakeIoTTenants) List(opts v1.ListOptions) (result *iotv1.IoTTenantList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(iottenantsResource, iottenantsKind, c.ns, opts), &iotv1.IoTTenantList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &iotv1.IoTTenantList{ListMeta: obj.(*iotv1.IoTTenantList).ListMeta}
	for _, item := range obj.(*iotv1.IoTTenantList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ioTTenants.
func (c *FakeIoTTenants) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(iottenantsResource, c.ns, opts))

}

// Create takes the representation of a ioTTenant and creates it.  Returns the server's representation of the ioTTenant, and an error, if there is any.
func (c *FakeIoTTenants) Create(ioTTenant *iotv1.IoTTenant) (result *iotv1.IoTTenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(iottenantsResource, c.ns, ioTTenant), &iotv1.IoTTenant{})

	if obj == nil {
		return nil, err
	}
	return obj.(*iotv1.IoTTenant), err
}

// Update takes the representation of a ioTTenant and updates it. Returns the server's representation of the ioTTenant, and an error, if there is any.
func (c *FakeIoTTenants) Update(ioTTenant *iotv1.IoTTenant) (result *iotv1.IoTTenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(iottenantsResource, c.ns, ioTTenant), &iotv1.IoTTenant{})

	if obj == nil {
		return nil, err
	}
	return obj.(*iotv1.IoTTenant), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIoTTenants) UpdateStatus(ioTTenant *iotv1.IoTTenant) (*iotv1.IoTTenant, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(iottenantsResource, "status", c.ns, ioTTenant), &iotv1.IoTTenant{})

	if obj == nil {
		return nil, err
	}
	return obj.(*iotv1.IoTTenant), err
}

// Delete takes name of the ioTTenant and deletes it. Returns an error if one occurs.
func (c *FakeIoTTenants) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(iottenantsResource, c.ns, name), &iotv1.IoTTenant{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIoTTenants) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(iottenantsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &iotv1.IoTTenantList{})
	return err
}

// Patch applies the patch and returns the patched ioTTenant.
func (c *FakeIoTTenants) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *iotv1.IoTTenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(iottenantsResource, c.ns, name, pt, data, subresources...), &iotv1.IoTTenant{})

	if obj == nil {
		return nil, err
	}
	return obj.(*iotv1.IoTTenant), err
}
