/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/typed/iot/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIotV1 struct {
	*testing.Fake
}

func (c *FakeIotV1) IoTInfrastructures(namespace string) v1.IoTInfrastructureInterface {
	return &FakeIoTInfrastructures{c, namespace}
}

func (c *FakeIotV1) IoTTenants(namespace string) v1.IoTTenantInterface {
	return &FakeIoTTenants{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIotV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
