/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

// IoTInfrastructureListerExpansion allows custom methods to be added to
// IoTInfrastructureLister.
type IoTInfrastructureListerExpansion interface{}

// IoTInfrastructureNamespaceListerExpansion allows custom methods to be added to
// IoTInfrastructureNamespaceLister.
type IoTInfrastructureNamespaceListerExpansion interface{}

// IoTTenantListerExpansion allows custom methods to be added to
// IoTTenantLister.
type IoTTenantListerExpansion interface{}

// IoTTenantNamespaceListerExpansion allows custom methods to be added to
// IoTTenantNamespaceLister.
type IoTTenantNamespaceListerExpansion interface{}
