/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/enmasseproject/enmasse/pkg/apis/iot/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IoTTenantLister helps list IoTTenants.
type IoTTenantLister interface {
	// List lists all IoTTenants in the indexer.
	List(selector labels.Selector) (ret []*v1.IoTTenant, err error)
	// IoTTenants returns an object that can list and get IoTTenants.
	IoTTenants(namespace string) IoTTenantNamespaceLister
	IoTTenantListerExpansion
}

// ioTTenantLister implements the IoTTenantLister interface.
type ioTTenantLister struct {
	indexer cache.Indexer
}

// NewIoTTenantLister returns a new IoTTenantLister.
func NewIoTTenantLister(indexer cache.Indexer) IoTTenantLister {
	return &ioTTenantLister{indexer: indexer}
}

// List lists all IoTTenants in the indexer.
func (s *ioTTenantLister) List(selector labels.Selector) (ret []*v1.IoTTenant, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IoTTenant))
	})
	return ret, err
}

// IoTTenants returns an object that can list and get IoTTenants.
func (s *ioTTenantLister) IoTTenants(namespace string) IoTTenantNamespaceLister {
	return ioTTenantNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// IoTTenantNamespaceLister helps list and get IoTTenants.
type IoTTenantNamespaceLister interface {
	// List lists all IoTTenants in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.IoTTenant, err error)
	// Get retrieves the IoTTenant from the indexer for a given namespace and name.
	Get(name string) (*v1.IoTTenant, error)
	IoTTenantNamespaceListerExpansion
}

// ioTTenantNamespaceLister implements the IoTTenantNamespaceLister
// interface.
type ioTTenantNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all IoTTenants in the indexer for a given namespace.
func (s ioTTenantNamespaceLister) List(selector labels.Selector) (ret []*v1.IoTTenant, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IoTTenant))
	})
	return ret, err
}

// Get retrieves the IoTTenant from the indexer for a given namespace and name.
func (s ioTTenantNamespaceLister) Get(name string) (*v1.IoTTenant, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("iottenant"), name)
	}
	return obj.(*v1.IoTTenant), nil
}
