/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"time"

	v1beta2 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta2"
	scheme "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MessagingPlansGetter has a method to return a MessagingPlanInterface.
// A group's client should implement this interface.
type MessagingPlansGetter interface {
	MessagingPlans(namespace string) MessagingPlanInterface
}

// MessagingPlanInterface has methods to work with MessagingPlan resources.
type MessagingPlanInterface interface {
	Create(*v1beta2.MessagingPlan) (*v1beta2.MessagingPlan, error)
	Update(*v1beta2.MessagingPlan) (*v1beta2.MessagingPlan, error)
	UpdateStatus(*v1beta2.MessagingPlan) (*v1beta2.MessagingPlan, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta2.MessagingPlan, error)
	List(opts v1.ListOptions) (*v1beta2.MessagingPlanList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.MessagingPlan, err error)
	MessagingPlanExpansion
}

// messagingPlans implements MessagingPlanInterface
type messagingPlans struct {
	client rest.Interface
	ns     string
}

// newMessagingPlans returns a MessagingPlans
func newMessagingPlans(c *EnmasseV1beta2Client, namespace string) *messagingPlans {
	return &messagingPlans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the messagingPlan, and returns the corresponding messagingPlan object, and an error if there is any.
func (c *messagingPlans) Get(name string, options v1.GetOptions) (result *v1beta2.MessagingPlan, err error) {
	result = &v1beta2.MessagingPlan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingplans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MessagingPlans that match those selectors.
func (c *messagingPlans) List(opts v1.ListOptions) (result *v1beta2.MessagingPlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.MessagingPlanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested messagingPlans.
func (c *messagingPlans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("messagingplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a messagingPlan and creates it.  Returns the server's representation of the messagingPlan, and an error, if there is any.
func (c *messagingPlans) Create(messagingPlan *v1beta2.MessagingPlan) (result *v1beta2.MessagingPlan, err error) {
	result = &v1beta2.MessagingPlan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("messagingplans").
		Body(messagingPlan).
		Do().
		Into(result)
	return
}

// Update takes the representation of a messagingPlan and updates it. Returns the server's representation of the messagingPlan, and an error, if there is any.
func (c *messagingPlans) Update(messagingPlan *v1beta2.MessagingPlan) (result *v1beta2.MessagingPlan, err error) {
	result = &v1beta2.MessagingPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingplans").
		Name(messagingPlan.Name).
		Body(messagingPlan).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *messagingPlans) UpdateStatus(messagingPlan *v1beta2.MessagingPlan) (result *v1beta2.MessagingPlan, err error) {
	result = &v1beta2.MessagingPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingplans").
		Name(messagingPlan.Name).
		SubResource("status").
		Body(messagingPlan).
		Do().
		Into(result)
	return
}

// Delete takes name of the messagingPlan and deletes it. Returns an error if one occurs.
func (c *messagingPlans) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingplans").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *messagingPlans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingplans").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched messagingPlan.
func (c *messagingPlans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.MessagingPlan, err error) {
	result = &v1beta2.MessagingPlan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("messagingplans").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
