/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"time"

	v1beta2 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta2"
	scheme "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MessagingAddressesGetter has a method to return a MessagingAddressInterface.
// A group's client should implement this interface.
type MessagingAddressesGetter interface {
	MessagingAddresses(namespace string) MessagingAddressInterface
}

// MessagingAddressInterface has methods to work with MessagingAddress resources.
type MessagingAddressInterface interface {
	Create(*v1beta2.MessagingAddress) (*v1beta2.MessagingAddress, error)
	Update(*v1beta2.MessagingAddress) (*v1beta2.MessagingAddress, error)
	UpdateStatus(*v1beta2.MessagingAddress) (*v1beta2.MessagingAddress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta2.MessagingAddress, error)
	List(opts v1.ListOptions) (*v1beta2.MessagingAddressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.MessagingAddress, err error)
	MessagingAddressExpansion
}

// messagingAddresses implements MessagingAddressInterface
type messagingAddresses struct {
	client rest.Interface
	ns     string
}

// newMessagingAddresses returns a MessagingAddresses
func newMessagingAddresses(c *EnmasseV1beta2Client, namespace string) *messagingAddresses {
	return &messagingAddresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the messagingAddress, and returns the corresponding messagingAddress object, and an error if there is any.
func (c *messagingAddresses) Get(name string, options v1.GetOptions) (result *v1beta2.MessagingAddress, err error) {
	result = &v1beta2.MessagingAddress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingaddresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MessagingAddresses that match those selectors.
func (c *messagingAddresses) List(opts v1.ListOptions) (result *v1beta2.MessagingAddressList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.MessagingAddressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingaddresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested messagingAddresses.
func (c *messagingAddresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("messagingaddresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a messagingAddress and creates it.  Returns the server's representation of the messagingAddress, and an error, if there is any.
func (c *messagingAddresses) Create(messagingAddress *v1beta2.MessagingAddress) (result *v1beta2.MessagingAddress, err error) {
	result = &v1beta2.MessagingAddress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("messagingaddresses").
		Body(messagingAddress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a messagingAddress and updates it. Returns the server's representation of the messagingAddress, and an error, if there is any.
func (c *messagingAddresses) Update(messagingAddress *v1beta2.MessagingAddress) (result *v1beta2.MessagingAddress, err error) {
	result = &v1beta2.MessagingAddress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingaddresses").
		Name(messagingAddress.Name).
		Body(messagingAddress).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *messagingAddresses) UpdateStatus(messagingAddress *v1beta2.MessagingAddress) (result *v1beta2.MessagingAddress, err error) {
	result = &v1beta2.MessagingAddress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingaddresses").
		Name(messagingAddress.Name).
		SubResource("status").
		Body(messagingAddress).
		Do().
		Into(result)
	return
}

// Delete takes name of the messagingAddress and deletes it. Returns an error if one occurs.
func (c *messagingAddresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingaddresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *messagingAddresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingaddresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched messagingAddress.
func (c *messagingAddresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.MessagingAddress, err error) {
	result = &v1beta2.MessagingAddress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("messagingaddresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
