/*
 * Copyright 2020, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

export enum DeviceActionType {
  EDIT_METADATA = "EDIT_METADATA",
  EDIT_DEVICE_IN_JSON = "EDIT_DEVICE_IN_JSON",
  CLONE_DEVICE = "CLONE_DEVICE",
  ADD_GATEWAYS = "ADD_GATEWAYS",
  EDIT_GATEWAYS = "EDIT_GATEWAYS",
  ADD_CREDENTIALS = "ADD_CREDENTIALS",
  EDIT_CREDENTIALS = "EDIT_CREDENTIALS",
  CHANGE_CONNECTION_TYPE = "CHANGE_CONNECTION_TYPE"
}
