#!/usr/bin/env bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck source=common
source "$SCRIPTDIR/common"

: "${NAMESPACE:=enmasse-infra}"
: "${PREFIX:=}"

function deleteSecret () {
  "${CLI}" -n "$NAMESPACE" delete secret "$1" --ignore-not-found=true
}

for i in ${IOT_SERVICES}; do
  deleteSecret "${PREFIX}${i}-tls"
done

deleteSecret "${PREFIX}iot-service-ca"
