// Code generated by goyacc -o parser.go -p Filter parser.y. DO NOT EDIT.

//line parser.y:10
package filter

import __yyfmt__ "fmt"

//line parser.y:10

func setExpressionTree(yylex interface{}, expr Expr) {
	yylex.(*lexer).expr = expr
}

func setOrderByTree(yylex interface{}, expr OrderBy) {
	yylex.(*lexer).orderBy = expr
}

//line parser.y:22
type FilterSymType struct {
	yys           int
	bytes         []byte
	stringValue   StringVal
	integralValue IntVal
	floatValue    FloatVal
	jsonPathValue JSONPathVal
	boolVal       BoolVal

	orderList OrderBy
	order     *Order

	expr Expr
	str  string
}

const OR = 57346
const AND = 57347
const NOT = 57348
const LE = 57349
const GE = 57350
const NE = 57351
const LIKE = 57352
const IS = 57353
const STRING = 57354
const INTEGRAL = 57355
const FLOAT = 57356
const JSON_PATH = 57357
const NULL = 57358
const TRUE = 57359
const FALSE = 57360
const START_EXPRESSION = 57361
const ASC = 57362
const DESC = 57363
const START_ORDER_LIST = 57364

var FilterToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"OR",
	"AND",
	"NOT",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"NE",
	"LIKE",
	"IS",
	"'('",
	"')'",
	"STRING",
	"INTEGRAL",
	"FLOAT",
	"JSON_PATH",
	"NULL",
	"TRUE",
	"FALSE",
	"START_EXPRESSION",
	"ASC",
	"DESC",
	"','",
	"START_ORDER_LIST",
}
var FilterStatenames = [...]string{}

const FilterEofCode = 1
const FilterErrCode = 2
const FilterInitialStackSize = 16

//line yacctab:1
var FilterExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 8,
	1, 8,
	4, 8,
	5, 8,
	16, 8,
	-2, 15,
}

const FilterPrivate = 57344

const FilterLast = 64

var FilterAct = [...]int{

	8, 19, 9, 7, 13, 14, 15, 16, 17, 10,
	11, 35, 6, 50, 13, 14, 15, 16, 17, 10,
	11, 37, 38, 20, 45, 47, 43, 43, 42, 44,
	2, 4, 22, 21, 3, 22, 21, 48, 23, 24,
	46, 21, 1, 36, 41, 18, 43, 12, 49, 25,
	5, 0, 0, 39, 40, 27, 29, 30, 31, 32,
	33, 34, 26, 28,
}
var FilterPact = [...]int{

	6, -1000, -3, 3, 31, -1000, -3, -3, -1000, 49,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -16, -1000,
	-4, -3, -3, 28, -1000, -13, -13, 11, 19, -1000,
	-1000, -1000, -1000, -1000, -1000, 3, -1000, -1000, -1000, -1000,
	36, -1000, -1000, -1000, -1000, -13, -1000, -8, -1000, -1000,
	-1000,
}
var FilterPgo = [...]int{

	0, 31, 50, 49, 47, 2, 0, 45, 1, 43,
	42,
}
var FilterR1 = [...]int{

	0, 10, 10, 1, 1, 1, 1, 1, 1, 2,
	2, 2, 2, 2, 5, 5, 3, 3, 3, 3,
	3, 3, 4, 4, 4, 4, 4, 6, 6, 7,
	7, 7, 8, 9, 9, 9,
}
var FilterR2 = [...]int{

	0, 2, 2, 1, 3, 3, 3, 2, 1, 3,
	3, 4, 3, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
	1, 3, 2, 0, 1, 1,
}
var FilterChk = [...]int{

	-1000, -10, 24, 28, -1, -2, 15, 6, -6, -5,
	22, 23, -4, 17, 18, 19, 20, 21, -7, -8,
	20, 5, 4, -1, -1, -3, 13, 6, 14, 7,
	8, 9, 10, 11, 12, 27, -9, 25, 26, -1,
	-1, 16, -5, -6, -5, 13, 21, 6, -8, -5,
	21,
}
var FilterDef = [...]int{

	0, -2, 0, 29, 1, 3, 0, 0, -2, 0,
	27, 28, 14, 22, 23, 24, 25, 26, 2, 30,
	33, 0, 0, 0, 7, 0, 0, 0, 0, 16,
	17, 18, 19, 20, 21, 0, 32, 34, 35, 5,
	6, 4, 9, 15, 10, 0, 12, 0, 31, 11,
	13,
}
var FilterTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	15, 16, 3, 3, 27, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	8, 7, 9,
}
var FilterTok2 = [...]int{

	2, 3, 4, 5, 6, 10, 11, 12, 13, 14,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
	28,
}
var FilterTok3 = [...]int{
	0,
}

var FilterErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	FilterDebug        = 0
	FilterErrorVerbose = false
)

type FilterLexer interface {
	Lex(lval *FilterSymType) int
	Error(s string)
}

type FilterParser interface {
	Parse(FilterLexer) int
	Lookahead() int
}

type FilterParserImpl struct {
	lval  FilterSymType
	stack [FilterInitialStackSize]FilterSymType
	char  int
}

func (p *FilterParserImpl) Lookahead() int {
	return p.char
}

func FilterNewParser() FilterParser {
	return &FilterParserImpl{}
}

const FilterFlag = -1000

func FilterTokname(c int) string {
	if c >= 1 && c-1 < len(FilterToknames) {
		if FilterToknames[c-1] != "" {
			return FilterToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func FilterStatname(s int) string {
	if s >= 0 && s < len(FilterStatenames) {
		if FilterStatenames[s] != "" {
			return FilterStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func FilterErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !FilterErrorVerbose {
		return "syntax error"
	}

	for _, e := range FilterErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + FilterTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := FilterPact[state]
	for tok := TOKSTART; tok-1 < len(FilterToknames); tok++ {
		if n := base + tok; n >= 0 && n < FilterLast && FilterChk[FilterAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if FilterDef[state] == -2 {
		i := 0
		for FilterExca[i] != -1 || FilterExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; FilterExca[i] >= 0; i += 2 {
			tok := FilterExca[i]
			if tok < TOKSTART || FilterExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if FilterExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += FilterTokname(tok)
	}
	return res
}

func Filterlex1(lex FilterLexer, lval *FilterSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = FilterTok1[0]
		goto out
	}
	if char < len(FilterTok1) {
		token = FilterTok1[char]
		goto out
	}
	if char >= FilterPrivate {
		if char < FilterPrivate+len(FilterTok2) {
			token = FilterTok2[char-FilterPrivate]
			goto out
		}
	}
	for i := 0; i < len(FilterTok3); i += 2 {
		token = FilterTok3[i+0]
		if token == char {
			token = FilterTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = FilterTok2[1] /* unknown char */
	}
	if FilterDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", FilterTokname(token), uint(char))
	}
	return char, token
}

func FilterParse(Filterlex FilterLexer) int {
	return FilterNewParser().Parse(Filterlex)
}

func (Filterrcvr *FilterParserImpl) Parse(Filterlex FilterLexer) int {
	var Filtern int
	var FilterVAL FilterSymType
	var FilterDollar []FilterSymType
	_ = FilterDollar // silence set and not used
	FilterS := Filterrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Filterstate := 0
	Filterrcvr.char = -1
	Filtertoken := -1 // Filterrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Filterstate = -1
		Filterrcvr.char = -1
		Filtertoken = -1
	}()
	Filterp := -1
	goto Filterstack

ret0:
	return 0

ret1:
	return 1

Filterstack:
	/* put a state and value onto the stack */
	if FilterDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", FilterTokname(Filtertoken), FilterStatname(Filterstate))
	}

	Filterp++
	if Filterp >= len(FilterS) {
		nyys := make([]FilterSymType, len(FilterS)*2)
		copy(nyys, FilterS)
		FilterS = nyys
	}
	FilterS[Filterp] = FilterVAL
	FilterS[Filterp].yys = Filterstate

Filternewstate:
	Filtern = FilterPact[Filterstate]
	if Filtern <= FilterFlag {
		goto Filterdefault /* simple state */
	}
	if Filterrcvr.char < 0 {
		Filterrcvr.char, Filtertoken = Filterlex1(Filterlex, &Filterrcvr.lval)
	}
	Filtern += Filtertoken
	if Filtern < 0 || Filtern >= FilterLast {
		goto Filterdefault
	}
	Filtern = FilterAct[Filtern]
	if FilterChk[Filtern] == Filtertoken { /* valid shift */
		Filterrcvr.char = -1
		Filtertoken = -1
		FilterVAL = Filterrcvr.lval
		Filterstate = Filtern
		if Errflag > 0 {
			Errflag--
		}
		goto Filterstack
	}

Filterdefault:
	/* default state action */
	Filtern = FilterDef[Filterstate]
	if Filtern == -2 {
		if Filterrcvr.char < 0 {
			Filterrcvr.char, Filtertoken = Filterlex1(Filterlex, &Filterrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if FilterExca[xi+0] == -1 && FilterExca[xi+1] == Filterstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Filtern = FilterExca[xi+0]
			if Filtern < 0 || Filtern == Filtertoken {
				break
			}
		}
		Filtern = FilterExca[xi+1]
		if Filtern < 0 {
			goto ret0
		}
	}
	if Filtern == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Filterlex.Error(FilterErrorMessage(Filterstate, Filtertoken))
			Nerrs++
			if FilterDebug >= 1 {
				__yyfmt__.Printf("%s", FilterStatname(Filterstate))
				__yyfmt__.Printf(" saw %s\n", FilterTokname(Filtertoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Filterp >= 0 {
				Filtern = FilterPact[FilterS[Filterp].yys] + FilterErrCode
				if Filtern >= 0 && Filtern < FilterLast {
					Filterstate = FilterAct[Filtern] /* simulate a shift of "error" */
					if FilterChk[Filterstate] == FilterErrCode {
						goto Filterstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if FilterDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", FilterS[Filterp].yys)
				}
				Filterp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if FilterDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", FilterTokname(Filtertoken))
			}
			if Filtertoken == FilterEofCode {
				goto ret1
			}
			Filterrcvr.char = -1
			Filtertoken = -1
			goto Filternewstate /* try again in the same state */
		}
	}

	/* reduction by production Filtern */
	if FilterDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Filtern, FilterStatname(Filterstate))
	}

	Filternt := Filtern
	Filterpt := Filterp
	_ = Filterpt // guard against "declared and not used"

	Filterp -= FilterR2[Filtern]
	// Filterp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Filterp+1 >= len(FilterS) {
		nyys := make([]FilterSymType, len(FilterS)*2)
		copy(nyys, FilterS)
		FilterS = nyys
	}
	FilterVAL = FilterS[Filterp+1]

	/* consult goto table to find next state */
	Filtern = FilterR1[Filtern]
	Filterg := FilterPgo[Filtern]
	Filterj := Filterg + FilterS[Filterp].yys + 1

	if Filterj >= FilterLast {
		Filterstate = FilterAct[Filterg]
	} else {
		Filterstate = FilterAct[Filterj]
		if FilterChk[Filterstate] != -Filtern {
			Filterstate = FilterAct[Filterg]
		}
	}
	// dummy call; replaced with literal code
	switch Filternt {

	case 1:
		FilterDollar = FilterS[Filterpt-2 : Filterpt+1]
//line parser.y:80
		{
			setExpressionTree(Filterlex, FilterDollar[2].expr)
		}
	case 2:
		FilterDollar = FilterS[Filterpt-2 : Filterpt+1]
//line parser.y:85
		{
			setOrderByTree(Filterlex, FilterDollar[2].orderList)
		}
	case 3:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:91
		{
			FilterVAL.expr = FilterDollar[1].expr
		}
	case 4:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:95
		{
			FilterVAL.expr = NewBoolExpr(FilterDollar[2].expr)
		}
	case 5:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:99
		{
			FilterVAL.expr = NewAndExpr(FilterDollar[1].expr, FilterDollar[3].expr)
		}
	case 6:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:103
		{
			FilterVAL.expr = NewOrExpr(FilterDollar[1].expr, FilterDollar[3].expr)
		}
	case 7:
		FilterDollar = FilterS[Filterpt-2 : Filterpt+1]
//line parser.y:107
		{
			FilterVAL.expr = NewNotExpr(FilterDollar[2].expr)
		}
	case 8:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:111
		{
			FilterVAL.expr = FilterDollar[1].boolVal
		}
	case 9:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:117
		{
			FilterVAL.expr = NewComparisonExpr(FilterDollar[1].expr, FilterDollar[2].str, FilterDollar[3].expr)
		}
	case 10:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:121
		{
			FilterVAL.expr = NewComparisonExpr(FilterDollar[1].expr, LikeStr, FilterDollar[3].expr)
		}
	case 11:
		FilterDollar = FilterS[Filterpt-4 : Filterpt+1]
//line parser.y:125
		{
			FilterVAL.expr = NewComparisonExpr(FilterDollar[1].expr, NotLikeStr, FilterDollar[4].expr)
		}
	case 12:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:129
		{
			FilterVAL.expr = NewIsNullExpr(FilterDollar[1].expr, IsNull)
		}
	case 13:
		FilterDollar = FilterS[Filterpt-4 : Filterpt+1]
//line parser.y:133
		{
			FilterVAL.expr = NewIsNullExpr(FilterDollar[1].expr, IsNotNull)
		}
	case 14:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:140
		{
			FilterVAL.expr = FilterDollar[1].expr
		}
	case 15:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:144
		{
			FilterVAL.expr = FilterDollar[1].boolVal
		}
	case 16:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:150
		{
			FilterVAL.str = EqualStr
		}
	case 17:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:154
		{
			FilterVAL.str = LessThanStr
		}
	case 18:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:158
		{
			FilterVAL.str = GreaterThanStr
		}
	case 19:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:162
		{
			FilterVAL.str = LessEqualStr
		}
	case 20:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:166
		{
			FilterVAL.str = GreaterEqualStr
		}
	case 21:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:170
		{
			FilterVAL.str = NotEqualStr
		}
	case 22:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:176
		{
			FilterVAL.expr = StringVal(FilterDollar[1].stringValue)
		}
	case 23:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:180
		{
			FilterVAL.expr = IntVal(FilterDollar[1].integralValue)
		}
	case 24:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:184
		{
			FilterVAL.expr = FloatVal(FilterDollar[1].floatValue)
		}
	case 25:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:188
		{
			FilterVAL.expr = FilterDollar[1].jsonPathValue
		}
	case 26:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:192
		{
			FilterVAL.expr = NewNullVal()
		}
	case 27:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:198
		{
			FilterVAL.boolVal = BoolVal(true)
		}
	case 28:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:202
		{
			FilterVAL.boolVal = BoolVal(false)
		}
	case 29:
		FilterDollar = FilterS[Filterpt-0 : Filterpt+1]
//line parser.y:207
		{
			FilterVAL.orderList = NewEmptyOrderBy()
		}
	case 30:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:211
		{
			FilterVAL.orderList = NewOrderBy(FilterDollar[1].order)
		}
	case 31:
		FilterDollar = FilterS[Filterpt-3 : Filterpt+1]
//line parser.y:215
		{
			FilterVAL.orderList = append(FilterDollar[1].orderList, FilterDollar[3].order)
		}
	case 32:
		FilterDollar = FilterS[Filterpt-2 : Filterpt+1]
//line parser.y:221
		{
			FilterVAL.order = NewOrder(FilterDollar[1].jsonPathValue, FilterDollar[2].str)
		}
	case 33:
		FilterDollar = FilterS[Filterpt-0 : Filterpt+1]
//line parser.y:226
		{
			FilterVAL.str = AscScr
		}
	case 34:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:230
		{
			FilterVAL.str = AscScr
		}
	case 35:
		FilterDollar = FilterS[Filterpt-1 : Filterpt+1]
//line parser.y:234
		{
			FilterVAL.str = DescScr
		}
	}
	goto Filterstack /* stack new state and value */
}
