apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-generator
  labels:
    name: rc-generator
spec:
  replicas: 1
  selector:
    name: rc-generator
  template:
    metadata:
      labels:
        name: rc-generator
    spec:
      serviceAccount: deployer
      containers:
      - name: master
        image: enmasseproject/rc-generator:latest
