#!/usr/bin/bash

BASE=`dirname $0`
ABS_BASE=`cd $BASE && pwd`
WORKING=`pwd`

#TODO: parameterise these URLs
wget http://archive.apache.org/dist/qpid/proton/0.13.1/qpid-proton-0.13.1.tar.gz
wget https://github.com/apache/qpid-dispatch/archive/master.tar.gz
tar -zxf master.tar.gz
tar -zxf qpid-proton-0.13.1.tar.gz
mkdir build staging proton_build proton_install
cd proton_build
cmake -DCMAKE_INSTALL_PREFIX=$WORKING/proton_install -DBUILD_CPP=OFF -DBUILD_PERL=OFF -DBUILD_RUBY=OFF -DBUILD_JAVA=OFF -DBUILD_GO=OFF -DBUILD_JAVASCRIPT=OFF -DBUILD_PHP=OFF $WORKING/qpid-proton-0.13.1 && make && make install
cd $WORKING/build
CMAKE_PREFIX_PATH=$WORKING/proton_install cmake -DBUILD_DOCS=OFF -DCONSOLE_INSTALL=OFF -DCMAKE_INSTALL_PREFIX=/usr $WORKING/qpid-dispatch-master/ && make && make DESTDIR=$WORKING/staging/ install && tar -z -C $WORKING/staging/ -cf $ABS_BASE/qpid-dispatch-binary.tar.gz usr etc
