PROJECT_NAME=qdrouterd

include ../Makefile.common

build:
	bash build_tarball

clean:
	rm -rf proton_build proton_install qpid-dispatch-binary.tar.gz qpid-dispatch-src qpid-proton.tar.gz qpid-proton-src staging build

.PHONY: build clean
