apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enmasse
  labels:
    monitoring-key: middleware
    app: enmasse
spec:
  selector:
    matchLabels:
      app: enmasse
  endpoints:
  - port: health
  - port: health-tls
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - port: prometheus
    path: /prometheus
  namespaceSelector:
    matchLabels:
      monitoring-key: middleware
