apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "enmasse.io:apiserver-authentication-reader"
  namespace: kube-system
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: api-server
  namespace: ${NAMESPACE}
