[[standard_address_space]]
=== Standard Address Space
The default address space in {ProductName} is the standard address space and it consists of an AMQP router network in combination with attachable storage units. The implementation of a storage unit is hidden from the client and the routers with a well-defined API. This address space type is appropriate when you have many connections and addresses. However, it has the following limitations: no transaction support, no message ordering, no selectors on queues, and no message groups.

Clients connect and send and receive messages in this address space using the AMQP or MQTT protocols. Note that MQTT does not support qos2 or retained messages.

// TODO This reflects the status quo, but how should multiple protocols actually be surfaced?

==== Address Types
The standard address space supports four address types:

* queue
* topic
* anycast
* multicast

// TODO Document plan restrictions and document properties for all 4 types

[[standard-queue]]
==== Queue
// standard.address.queue.shortDescription:A store-and-forward queue
// standard.address.queue.longDescription:start
The queue address type is a store-and-forward queue. This address type is appropriate for implementing a distributed work queue, handling traffic bursts, and other use cases where you want to decouple the producer and consumer. A queue can be sharded across multiple storage units; however, message order is no longer guaranteed.
// standard.address.queue.longDescription:stop

[[queue-plans]]
===== Queue Plans

* inmemory
* persisted
* pooled-inmemory
* pooled-persisted

[[in-memory-queue]]
====== In memory
// standard.address.queue.plan.inmemory.shortDescription:In memory only
// standard.address.queue.plan.inmemory.longDescription:start
Creates a standalone broker cluster for queues. Messages are not persisted on
stable storage.
// standard.address.queue.plan.inmemory.longDescription:stop

[[persisted-queue]]
====== Persisted

// standard.address.queue.plan.persisted.shortDescription:Saved to storage
// standard.address.queue.plan.persisted.longDescription:start
Creates a standalone broker cluster for queues. Messages are persisted on stable
storage.
// standard.address.queue.plan.persisted.longDescription:stop

[[pooled-in-memory-queue]]
====== Pooled in memory
// standard.address.queue.plan.pooled-inmemory.shortDescription:Shared broker cluster - not persisted
// standard.address.queue.plan.pooled-inmemory.longDescription:start
Schedules queues to run on a shared broker cluster, reducing overhead. Messages
are not persisted on stable storage.
// standard.address.queue.plan.pooled-inmemory.longDescription:stop

[[pooled-persisted-queue]]
====== Pooled persisted

// standard.address.queue.plan.pooled-persisted.shortDescription:Shared broker cluster - saved to storage
// standard.address.queue.plan.pooled-persisted.longDescription:start
Schedules queues to run on a shared broker cluster, reducing overhead. Messages
are persisted on stable storage.
// standard.address.queue.plan.pooled-persisted.longDescription:stop

[[standard-topic]]
==== Topic
// standard.address.topic.shortDescription:A publish-subscribe topic
// standard.address.topic.longDescription:start
The topic address type supports the publish-subscribe messaging pattern where you have 1..N producers and 1..M consumers. Each message published to a topic address is forwarded to all subscribers for that address. A subscriber can also be durable, in which case messages are kept until the subscriber has acknowledged them.
// standard.address.topic.longDescription:stop

[[topic-plans]]
===== Topic Plans

* inmemory
* persisted

[[in-memory-topic]]
====== In memory

// standard.address.topic.plan.inmemory.shortDescription:In memory only
// standard.address.topic.plan.inmemory.longDescription:start
Creates a standalone broker cluster for topics. Messages are not persisted on
stable storage.
// standard.address.topic.plan.inmemory.longDescription:stop

[[persisted-topic]]
====== Persisted

// standard.address.topic.plan.persisted.shortDescription:Saved to storage
// standard.address.topic.plan.persisted.longDescription:start
Creates a standalone broker cluster for topics. Messages are persisted on stable
storage.
// standard.address.topic.plan.persisted.longDescription:stop

[[anycast]]
==== Anycast
// standard.address.anycast.shortDescription:A scalable 'direct' address for sending messages to one consumer
// standard.address.anycast.longDescription:start
The anycast address type is a scalable direct address for sending messages to one consumer. Messages sent to an anycast address are not stored, but forwarded directly to the consumer. This method makes this address type ideal for request-reply (RPC) uses or even work distribution. This is the cheapest address type as it does not require any persistence.
// standard.address.anycast.longDescription:stop

[[anycast-plans]]
===== Anycast Plans

* standard

// standard.address.anycast.plan.inmemory.shortDescription:Configures the router network with an anycast address

[[multicast]]
==== Multicast
// standard.address.multicast.shortDescription:A scalable 'direct' address for sending messages to multiple consumers
// standard.address.multicast.longDescription:start
The multicast address type is a scalable direct address for sending messages to multiple consumers. Messages sent to a multicast address are forwarded to all consumers receiving messages on that address. It is important to note that only pre-settled messages can be sent to multicast addresses, as message acknowledgements from consumers are not propagated to producers.
// standard.address.multicast.longDescription:stop

[[multicast-plans]]
===== Multicast Plans

* standard

// standard.address.multicast.plan.inmemory.shortDescription:Configures router network with multicast address

[[brokered_address_space]]
=== Brokered Address Space

The brokered address space is designed to support broker-specific features, at the cost of limited
scale in terms of the number of connections and addresses. This address space supports JMS
transactions, message groups, and so on.

Clients connect and send and receive messages in this address space using the AMQP protocol.

==== Address types

* queue
* topic

[[brokered-queue]]
==== Queue

// brokered.address.queue.shortDescription:A store-and-forward queue
// brokered.address.queue.longDescription:start
The queue address type is a store-and-forward queue. This address type is appropriate for
implementing a distributed work queue, handling traffic bursts, and other use cases where you want
to decouple the producer and consumer. A queue in the brokered address spaces supports selectors,
message groups, transactions, and other JMS features.
// brokered.address.queue.longDescription:stop
// brokered.address.queue.plan.standard.shortDescription:start
Only a standard plan is available for queues.
// brokered.address.queue.plan.standard.shortDescription:stop
// brokered.address.queue.plan.standard.longDescription:There is no choice of plans for queues at this time.

[[brokered-topic]]
==== Topic
// brokered.address.topic.shortDescription:A publish-and-subscribe address with store-and-forward semantics
// brokered.address.topic.longDescription:start
The topic address type supports the publish-subscribe messaging pattern where you have 1..N producers and 1..M consumers. Each message published to a topic address is forwarded to all subscribers for that address. A subscriber can also be durable, in which case messages are kept until the subscriber has acknowledged them.
// brokered.address.topic.longDescription:stop

// brokered.address.topic.plan.standard.shortDescription:start
Only a standard plan is available for topics.
// brokered.address.topic.plan.standard.shortDescription:stop
// brokered.address.topic.plan.standard.longDescription:There is no choice of plans for topics at this time.
