[[address_model]]

== Address Model

The {ProductName} address model involves three distinct concepts:

* types of address spaces
* types of addresses within each address space
* available plans

=== Address Space
An address space is a group of addresses that can be accessed through a single connection (per protocol). This means that clients connected to an address space can send messages to or receive messages from any authorized address that is defined within that address space. An address space can support multiple protocols, which is defined by the address space type.

=== Address
// address.name.shortDescription:Type an address name.
// address.name.longDescription:The <b>address name</b> is a unique string to which messages can be sent and received.
// address.name.external:{OnlineBookURL}
An address is part of an address space and represents a destination used for sending and receiving messages. All addresses have an address type, which defines how messages sent to and from that address are handled.

=== Plans
Both address spaces and addresses can be restricted by a plan, which enforces a limit on resource usage across multiple dimensions.

==== Address Space Plans
Each address space has a plan that restricts the aggregated resource usage within an address space. Each address space type can translate the plan into a set of restrictions, for example, the ability to scale up to five routers or to create up to 10 addresses. These restrictions are documented within each address space.

==== Address Plans
The usage of each address is also constrained by a plan. Each address type translates the plan into a set of restrictions, for example, up to five consumers or up to 100 messages per hour. These restrictions are documented within each address type.
