[[brokered_address_space]]
== Brokered Address Space

The brokered address space is designed to support broker-specific features, at the cost of limited
scale in terms of the number of connections and addresses. This address space supports JMS
transactions, message groups, and so on.

Clients connect and send and receive messages in this address space using the AMQP protocol.

=== Address Types

The supported address types for the brokered address space are:

* queue
* topic

[[brokered-queue]]
=== Queue

The queue address type is a store-and-forward queue. This address type is appropriate for
implementing a distributed work queue, handling traffic bursts, and other use cases where you want
to decouple the producer and consumer. A queue in the brokered address spaces supports selectors,
message groups, transactions, and other JMS features.

//If the queue is a high-volume queue and these semantics are not needed, see the xref:standard-queue[standard address space `queue`] type.

////
==== Queue Plans

* standard

[[standard-queue-plan]]
===== Standard

The standard queue plan deploys a queue in the broker for that address space.
////

[[brokered-topic]]
=== Topic

The topic address type supports the publish-subscribe messaging pattern where you have 1..N producers and 1..M consumers. Each message published to a topic address is forwarded to all subscribers for that address. A subscriber can also be durable, in which case messages are kept until the subscriber has acknowledged them.

////
[[brokered-topic-plans]]
==== Topic Plans

* standard

[[standard-topic-plan]]
===== Standard

The standard topic plan deploys a topic in the broker for that address space.
////
