[[configuring-using-restapi]]

== Configuring {ProductName} using a REST API

{ProductName} provides an API that can be used for configuring address spaces and addresses
within those address spaces. Clients can be configured to authenticate using
https://kubernetes.io/docs/admin/authorization/rbac/[RBAC^]. 

All API URIs are namespaced. This means that address spaces are scoped within a particular
namespace. Addresses are scoped within an address space. This means that an address
space in address space A may have the same name as an address in address space B.

Likewise, an address space in namespace A can have the same name as an address space in namespace B.

=== Creating an Address Space

.Procedure

. Save the following JSON data to a file 'space.json':
+
[source,json,options="nowrap"]
----
{
    "apiVersion": "enmasse.io/v1alpha1",
    "kind": "AddressSpace",
    "metadata": {
        "name": "myspace"
    },
    "spec": {
        "type": "standard",
        "plan": "unlimited-standard"
    }
}
----
+
. POST the address space definition to the API using curl:
+
[source,options="nowrap"]
----
TOKEN=`oc whoami -t`
curl -X POST -T space.json -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/[:namespace]/addressspaces
----
+
This will create the infrastructure required for that address space. Replace the namespace with the
namespace of the application requesting the address space to be created. Starting up the address space
will take a while, usually depending on how fast it is able to download the Docker images for the
various components.

=== Viewing Address Space Status

.Procedure

* You can use the API to check the status of the address space:
+
[source,options="nowrap"]
----
TOKEN=`oc whoami -t`
curl -k -H "Authorization: Bearer $TOKEN" https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/[:namespace]/addressspaces/myspace
----
+
You can consider the address space to be ready to use when `status.isReady` is `true` in the returned JSON
object.

=== Creating Addresses

.Procedure

. To create addresses in the standard address space, save the address definition to a file:
+
[source,json,options="nowrap"]
----
{
  "apiVersion": "enmasse.io/v1alpha1",
  "kind": "Address",
  "metadata": {
      "addressSpace": "myspace"
  },
  "spec": {
    "address": "myqueue",
    "type": "queue",
    "plan": "pooled-queue"
  }
}
----

. You can then create the address using the following API. Replace the namespace with the same as for the address space:
+
[source,bash,options="nowrap"]
----
TOKEN=`oc whoami -t`
curl -X PUT -T address.json -H "content-type: application/json" -H "Authorization: Bearer $TOKEN" -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/[:namespace]/addressspaces/myspace/addresses
----

=== Viewing Configured Addresses

.Procedure 

* To check which addresses are configured:
+
[source,bash,options="nowrap"]
----
curl -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/[:namespace]/addressspace/myspace/addresses
----
+
The addresses are ready to be used by messaging clients once the `status.isReady` field of each
address is set to `true`. 
