/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

// MessagingInfraListerExpansion allows custom methods to be added to
// MessagingInfraLister.
type MessagingInfraListerExpansion interface{}

// MessagingInfraNamespaceListerExpansion allows custom methods to be added to
// MessagingInfraNamespaceLister.
type MessagingInfraNamespaceListerExpansion interface{}

// MessagingTenantListerExpansion allows custom methods to be added to
// MessagingTenantLister.
type MessagingTenantListerExpansion interface{}

// MessagingTenantNamespaceListerExpansion allows custom methods to be added to
// MessagingTenantNamespaceLister.
type MessagingTenantNamespaceListerExpansion interface{}
