/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1"
	scheme "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MessagingProjectsGetter has a method to return a MessagingProjectInterface.
// A group's client should implement this interface.
type MessagingProjectsGetter interface {
	MessagingProjects(namespace string) MessagingProjectInterface
}

// MessagingProjectInterface has methods to work with MessagingProject resources.
type MessagingProjectInterface interface {
	Create(*v1.MessagingProject) (*v1.MessagingProject, error)
	Update(*v1.MessagingProject) (*v1.MessagingProject, error)
	UpdateStatus(*v1.MessagingProject) (*v1.MessagingProject, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.MessagingProject, error)
	List(opts metav1.ListOptions) (*v1.MessagingProjectList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MessagingProject, err error)
	MessagingProjectExpansion
}

// messagingProjects implements MessagingProjectInterface
type messagingProjects struct {
	client rest.Interface
	ns     string
}

// newMessagingProjects returns a MessagingProjects
func newMessagingProjects(c *EnmasseV1Client, namespace string) *messagingProjects {
	return &messagingProjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the messagingProject, and returns the corresponding messagingProject object, and an error if there is any.
func (c *messagingProjects) Get(name string, options metav1.GetOptions) (result *v1.MessagingProject, err error) {
	result = &v1.MessagingProject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingprojects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MessagingProjects that match those selectors.
func (c *messagingProjects) List(opts metav1.ListOptions) (result *v1.MessagingProjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MessagingProjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("messagingprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested messagingProjects.
func (c *messagingProjects) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("messagingprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a messagingProject and creates it.  Returns the server's representation of the messagingProject, and an error, if there is any.
func (c *messagingProjects) Create(messagingProject *v1.MessagingProject) (result *v1.MessagingProject, err error) {
	result = &v1.MessagingProject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("messagingprojects").
		Body(messagingProject).
		Do().
		Into(result)
	return
}

// Update takes the representation of a messagingProject and updates it. Returns the server's representation of the messagingProject, and an error, if there is any.
func (c *messagingProjects) Update(messagingProject *v1.MessagingProject) (result *v1.MessagingProject, err error) {
	result = &v1.MessagingProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingprojects").
		Name(messagingProject.Name).
		Body(messagingProject).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *messagingProjects) UpdateStatus(messagingProject *v1.MessagingProject) (result *v1.MessagingProject, err error) {
	result = &v1.MessagingProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("messagingprojects").
		Name(messagingProject.Name).
		SubResource("status").
		Body(messagingProject).
		Do().
		Into(result)
	return
}

// Delete takes name of the messagingProject and deletes it. Returns an error if one occurs.
func (c *messagingProjects) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingprojects").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *messagingProjects) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("messagingprojects").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched messagingProject.
func (c *messagingProjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MessagingProject, err error) {
	result = &v1.MessagingProject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("messagingprojects").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
