/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	iotv1 "github.com/enmasseproject/enmasse/pkg/apis/iot/v1"
	versioned "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/enmasseproject/enmasse/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/enmasseproject/enmasse/pkg/client/listers/iot/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IoTInfrastructureInformer provides access to a shared informer and lister for
// IoTInfrastructures.
type IoTInfrastructureInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.IoTInfrastructureLister
}

type ioTInfrastructureInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIoTInfrastructureInformer constructs a new informer for IoTInfrastructure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIoTInfrastructureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIoTInfrastructureInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIoTInfrastructureInformer constructs a new informer for IoTInfrastructure type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIoTInfrastructureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IotV1().IoTInfrastructures(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IotV1().IoTInfrastructures(namespace).Watch(options)
			},
		},
		&iotv1.IoTInfrastructure{},
		resyncPeriod,
		indexers,
	)
}

func (f *ioTInfrastructureInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIoTInfrastructureInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ioTInfrastructureInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&iotv1.IoTInfrastructure{}, f.defaultInformer)
}

func (f *ioTInfrastructureInformer) Lister() v1.IoTInfrastructureLister {
	return v1.NewIoTInfrastructureLister(f.Informer().GetIndexer())
}
