/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	iotv1 "github.com/enmasseproject/enmasse/pkg/apis/iot/v1"
	versioned "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/enmasseproject/enmasse/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/enmasseproject/enmasse/pkg/client/listers/iot/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IoTTenantInformer provides access to a shared informer and lister for
// IoTTenants.
type IoTTenantInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.IoTTenantLister
}

type ioTTenantInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIoTTenantInformer constructs a new informer for IoTTenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIoTTenantInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIoTTenantInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIoTTenantInformer constructs a new informer for IoTTenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIoTTenantInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IotV1().IoTTenants(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IotV1().IoTTenants(namespace).Watch(options)
			},
		},
		&iotv1.IoTTenant{},
		resyncPeriod,
		indexers,
	)
}

func (f *ioTTenantInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIoTTenantInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ioTTenantInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&iotv1.IoTTenant{}, f.defaultInformer)
}

func (f *ioTTenantInformer) Lister() v1.IoTTenantLister {
	return v1.NewIoTTenantLister(f.Informer().GetIndexer())
}
