// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>
:parent-context: {context}

[id='infrastructure-configuration-{context}']
= Infrastructure configuration 

{ProductName} creates infrastructure components such as routers, brokers, and consoles. These
components can be configured while the system is running, and {ProductName} automatically updates
the components with the new settings. The {ProductName} service operator can edit the {ProductName}
default infrastructure configuration or create new configurations.

Infrastructure configs can be referred to from 1 or more address space plans. For more information
about address space plans, see xref:con-address-space-plans-{context}[].

Infrastructure configuration can be managed for both `brokered` and `standard` infrastructure
using `BrokeredInfraConfig` and `StandardInfraConfig` resources.

include::../modules/con-brokered-infra-config.adoc[leveloffset=+1]

include::../modules/con-standard-infra-config.adoc[leveloffset=+1]

:context: {parent-context}

