// Module included in the following assemblies:
//
// master.adoc

[id='con-standard-address-space-{context}']
= Standard address space
The standard address space is the default address space in {ProductName}. It consists of an AMQP router network in combination with attachable storage units. Clients connect to a message router, which forwards messages to or from one or more message brokers. This address space type is appropriate when you have many connections and addresses. However, the standard address space has the following limitations:

* No transaction support
* No message ordering
* No selectors on queues
* No browsing on queues
* No message groups
* Restrictions affecting the use of some AMQP delivery states, such as the `undeliverable-here=true` modified delivery state when there are competing consumers attached to the same message router.


Clients connect and send and receive messages in this address space using the AMQP protocol.

// TODO This reflects the status quo, but how should multiple protocols actually be surfaced?
