// Module included in the following assemblies:
//
// assembly-configuring.adoc

[id='con-authentication-services-{context}']
= Authentication services

Authentication services are used to configure the authentication and authorization endpoints
available to messaging clients. The authentication services are configured by the {ProductName}
service operator, and are specified when creating an address space. Authentication services are configured as custom resources.

An authentication service has a type, which can be `none`, `standard`, or `external`. The
`none` authentication service type allows all clients to send and receive messages to any address.

== Standard authentication service

The `standard` authentication service type uses a {AuthProductName} instance to store user
credentials and access policies. This authentication service also allows managing users using the
`MessagingUser` custom resource.

The following example shows an authentication service of type `standard`:
include::../modules/ref-standard-auth-service-example.adoc[leveloffset=+1]

== External authentication service

The `external` authentication service allows configuring an external provider of authentication and
authorization policies through an AMQP SASL handshake. This can be used to implement a bridge for
your existing identity management system.

An `external` authentication service can be configured using the following example:
include::../modules/ref-external-auth-service-example.adoc[leveloffset=+1]
