// Module included in the following assemblies:
//
// assembly-infrastructure-configuration.adoc

[id='con-brokered-infra-config-{context}']
= Brokered infrastructure configuration

`BrokeredInfraConfig` resources is used to configure infrastructure deployed by `brokered` address
spaces. The brokered infrastructure configuration is referenced by address space plans using a `enmasse.io/defined-by`
annotation. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#con-address-space-plans-messaging[Address space plans].

[source,yaml,options="nowrap",subs="attributes"]
----
apiVersion: admin.enmasse.io/v1beta1
kind: BrokeredInfraConfig
metadata:
  name: brokered-infra-config-example
spec:
  version: {EnMasseVersion}
  admin:
    resources:
      memory: 256Mi
  broker:
    resources:
      memory: 2Gi
      storage: 100Gi
    addressFullPolicy: PAGE
----

The `version` field specifies the {ProductName} version used. When upgrading, {ProductName} uses
this field to determine whether to upgrade the infrastructure to the requested version.

The `admin` object specifies the settings you can configure for the `admin` components.

The `broker` object specifies the settings you can configure for the `broker` components. Changing
the `.broker.resources.storage` setting does not configure the existing broker storage size.

