// Module included in the following assemblies:
//
// assembly-configuring.adoc

[id='con-address-space-plans-{context}']
= Address space plans

Address space plans are used to configure quotas and control the resources consumed by address spaces. Address space plans are configured by the {ProductName} service operator and are selected when creating an address space.

{ProductName} includes a default set of plans that are sufficient for most use cases.

Plans are configured as custom resources. The following example shows a plan for the standard address space:

[source,yaml,options="nowrap"]
----
include::../common/restrictive-plan.yaml[]
----

The following fields are required:

* `metadata.name`
* `spec.resourceLimits`
* `spec.addressPlans`
* `spec.addressSpaceType`
* `spec.infraConfigRef`

The other fields are used by the {ConsoleName} UI. Note the field `spec.infraConfigRef`, which
points to an infrastructure configuration that must exist when an address space using this plan is created.
For more information about infrastructure configurations, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#infrastructure-configuration-messaging[Infrastructure configuration].

