// Module included in the following assemblies:
//
// assembly-standard-address-types.adoc

[id='con-standard-queue-{context}']
= Queue
// !standard.address.queue.shortDescription:A store-and-forward queue
// !standard.address.queue.longDescription:start
The queue address type is a store-and-forward queue. This address type is appropriate for implementing a distributed work queue, handling traffic bursts, and other use cases when you want to decouple the producer and consumer. A queue can be sharded across multiple storage units. Message ordering might be lost for queues in the standard address space.
// !standard.address.queue.longDescription:stop

Regarding dead-letter queues (DLQs), you can determine if any messages are stored in a DLQ by logging in to the {ConsoleName} and link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-view-message-conn-stats-table-messaging[viewing the Addresses page]. To resolve this situation, you must connect to a client and consume from a DLQ address.

