// Module included in the following assemblies:
//
// assembly-plans.adoc

[id='con-brokered-infra-config-{context}']
= Brokered infrastructure configuration

`BrokeredInfraConfig` resources is used to configure infrastructure deployed by `brokered` address
spaces. The brokered infra configuration is referenced by address space plans using a `defined-by`
annotation. For more information, see xref:con-address-space-plans-{context}[].

[source,yaml,options="nowrap"]
.link:resources/brokered-infra-config-example.yaml[brokered-infra-config-example.yaml]
----
include::../common/brokered-infra-config-example.yaml[]
----

The `version` field represents the {ProductName} version used. When upgrading, {ProductName} will
use this field to determine that the infrastructure should be upgraded to the requested version.

The `admin` object represents the settings you can configure for the `admin` components.

The `broker` object represents the settings you can configure for the `broker` components. Changing
the `.broker.resources.storage` setting does not configure existing broker storage size.
