// This assembly is included in the following assemblies:
//
// assembly-using-console.adoc

[id='con-console-{context}']
= {ConsoleName} user permissions

{ConsoleName} uses the link:{KubePlatformRbacURL}[{KubePlatform} RBAC permissions model].

To use {ConsoleName}, the {KubePlatformCredentials} user requires a role that grants access to `addressspace` and `address` resources. For example, for edit access, `create`, `update` and `delete` permissions need be to given to the associated role object, and for view-only access, `list` permissions need to be granted.

ifdef::SingleBookLink[]
For more information about the {ProductName} example roles, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-example-roles-messaging[{ProductName} example roles].
endif::SingleBookLink[]

ifndef::SingleBookLink[]
For more information about the {ProductName} example roles, see link:{BookUrlBase}{BaseProductVersion}/html-single/installing_and_managing_amq_online_on_openshift/#ref-example-roles-messaging[{ProductName} example roles].
endif::SingleBookLink[]

