// Module included in the following assemblies:
//
// assembly-infrastructure-configuration.adoc

[id='con-standard-infra-config-{context}']
= Standard infrastructure configuration

`StandardInfraConfig` resources is used to configure infrastructure deployed by `standard` address
spaces. The standard infrastructure configuration is referenced by address space plans using a `enmasse.io/defined-by`
annotation. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#con-address-space-plans-messaging[Address space plans].

[source,yaml,options="nowrap"]
----
include::../common/standard-infra-config-example.yaml[]
----

The `version` field specifies the {ProductName} version used. When upgrading, {ProductName} uses
this field to determine whether to upgrade the infrastructure to the requested version.

The `admin` object specifies the settings you can configure for the `admin` components.

The `broker` object specifies the settings you can configure for the `broker` components. Changing
the `.broker.resources.storage` setting does not configure the existing broker storage size.

The `router` object specifies the settings you can configure for the `router` components.

