// Module included in the following assemblies:
//
// assembly-iot-service-admin-guide.adoc

[id='con-iot-logging-{context}']
= IoT logging

By default, the IoT components of {ProductName} use a conservative
logging configuration for the infrastructure services to
preserve resources for normal operation.

{ProductName} also allows operation-level tracing using Jaeger,
for more in-depth tracing scenarios.

== Configuration options

For IoT components, it might be necessary to increase the logging output at
the following application
levels, listed in order from lowest priority to highest priority:

* A default log level for all IoT components
* A default configuration for specific log channels
* A service specific default log level
* A service specific configuration for specific log channels
* A service specific custom log configuration file

All configuration is part of the `IoTConfig` instance and the {ProductName} Operator applies the configuration to the services.
The only exception is the service specific
log configuration file, which can either be provided through the `IoTConfig` resource
or by creating an entry in the service specific `ConfigMap` resource.

== Log levels

The following log levels are available, listed in order from most severe to least severe:

error:: Error conditions. Indicates an unexpected condition, which may impact the stability of the system. Displays only error messages.
warn:: Warning conditions. Indicates an expected condition, which may impact the current operation or stability of the system. Displays only warning and error messages.
info:: Informational messages. Indicates an expected event, which may impact the current operation. Displays only informational, warning, and error messages.
debug:: Displays debug messages, in addition to all of the above.
trace:: Displays all messages.
