// This assembly is included in the following assemblies:
//
// assembly-using-console.adoc

[id='con-console-{context}']
= {ConsoleName} user permissions

{ConsoleName} uses the OpenShift RBAC permissions model. For more information about the OpenShift RBAC permissions model, see the link:https://docs.openshift.com/container-platform/3.11/admin_guide/manage_rbac.html[OpenShift documentation^].

To access the {ConsoleName}, the OpenShift user requires the `addressspace` and `address` resources to be included in the role object, which defines a set of permissions that apply to one or more resources. The specific permissions given to the role object govern the extent of the access. For example, for edit access, `edit` permissions need be to given to the associated role object, and for view-only access, `list` permissions need to be granted. For more information about the provided example roles, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-example-roles-messaging[{ProductName} example roles].


