[[configuring-using-restapi]]

== Configuring {ProductName} using a REST API

TODO: Authentication of clients

{ProductName} provides a REST API that can be used for configuring address spaces and addresses
within those address spaces.

=== Creating address spaces

Creating address spaces is only applicable for multi-tenant deployments of {ProductName}. To create
a 'standard' address space, save the following JSON data to a file


[source,options="nowrap"]
----
{
    "apiVersion": "v1/enmasse",
    "kind": "AddressSpace",
    "metadata": {
        "name": "myspace"
    },
    "spec": {
        "type": "standard"
    }
}
----

This will create the infrastructure required for that address space. Starting up the address space
will take a while, usually depending on how fast it is able to download the docker images for the
various components.

You can use the REST API to check the status of the address space.

[source,options="nowrap"]
----
curl http://$(oc get route restapi -o jsonpath='{.spec.host}')/v1/addressspaces/myspace
----

You can consider the address space to be ready to use when 'status.isReady' is 'true' in the returned JSON
object.

=== Creating addresses

To create addresses in the standard address space, save the following to a file

[source,options="nowrap"]
----
{
  "apiVersion": "enmasse.io/v1",
  "kind": "AddressList",
  "items": [
    {
      "metadata": {
        "name": "myqueue"
      },
      "spec": {
        "type": "queue"
      }
    },
    {
      "metadata": {
        "name": "mytopic"
      },
      "spec": {
        "type": "topic"
      }
    },
    {
      "metadata": {
        "name": "myanycast"
      },
      "spec": {
        "type": "anycast"
      }
    },
    {
      "metadata": {
        "name": "mymulticast"
      },
      "spec": {
        "type": "multicast"
      }
    }
  ]
}
----

You can then create those addresses using the REST API.

[source,options="nowrap"]
----
curl -X PUT -T addresses.json -H "content-type: application/json" http://$(oc get route restapi -o jsonpath='{.spec.host}')/v1/addresses/default
----

To check what addresses are configured:

[source,options="nowrap"]
----
curl http://$(oc get route restapi -o jsonpath='{.spec.host}')/v1/addresses/default
----

The addresses are ready to be used by messaging clients once the 'status.isReady' field of each
address is set to 'true'. 
