// Module included in the following assemblies:
//
// assembly-iot-guide.adoc
// assembly-IoT.adoc

[id='iot-installing-services-{context}']
= Installing IoT services

To get started using the IoT feature on {ProductName}, you must first install the IoT services.

.Procedure

. (Optional) If you want to deploy to a project other than `{ProductNamespace}` you must run the following command and substitute `{ProductNamespace}` in subsequent steps:
+
[options="nowrap",subs="+quotes,attributes"]
----
sed -i 's/{ProductNamespace}/_my-project_/' install/preview-bundles/iot/*.yaml
----
. Deploy the IoT bundles:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f install/preview-bundles/iot
----
ifeval::["{cmdcli}" == "kubectl"]
. Create certificates for IoT services. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap",subs="attributes"]
----
./install/components/iot/examples/k8s-tls/create
./install/components/iot/examples/k8s-tls/deploy
----
endif::[]

ifeval::["{cmdcli}" == "oc"]
. Create certificates for the MQTT protocol adapter. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap",subs="attributes"]
----
./install/components/iot/examples/k8s-tls/create
{cmdcli} create secret tls iot-mqtt-adapter-tls --key=install/components/iot/examples/k8s-tls/build/iot-mqtt-adapter-key.pem --cert=install/components/iot/examples/k8s-tls/build/iot-mqtt-adapter-fullchain.pem
----
endif::[]

+
You can override the namespace to which the `deploy` script installs the keys and certificates by
setting the environment variable `NAMESPACE` when calling the script. For example:

+
[options="nowrap"]
----
NAMESPACE=my-namespace ./install/components/iot/examples/k8s-tls/deploy
----

+
[NOTE]
====
If your cluster is not running on `localhost`, you need to specify the cluster host name when creating certificates to allow external clients (like MQTT) to properly connect to the appropriate services. For example:
[options="nowrap",subs="attributes"]
----
CLUSTER=x.x.x.x.nip.io install/components/iot/examples/k8s-tls/create
----
====

. (Optional) Install the PostgreSQL server and create database:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f install/components/iot/examples/postgresql/deploy
----
+
You may skip this step if you already have a PostgreSQL instance and
created a database with a user to access to it.

. Apply database schema:
+
--
You will need to execute the following SQL files on the database instance
you created. Depenending on your setup, this may require database admin privileges:

- `install/components/iot/examples/postgresql/create.sql`
- `install/components/iot/examples/postgresql/create.devcon.sql`

You can execute the SQL file using the `psql` command, connected to
your database. The following shows an example, how to execute `psql`
from inside the container, when you installed PostgreSQL as described
in the previous step:

[options="nowrap",subs="attributes,specialchars"]
----
{cmdcli} exec -ti deployment/postgresql -- bash -c "PGPASSWORD=user12 psql device-registry registry" < install/components/iot/examples/postgresql/create.sql
{cmdcli} exec -ti deployment/postgresql -- bash -c "PGPASSWORD=user12 psql device-registry registry" < install/components/iot/examples/postgresql/create.devcon.sql
----
--

. Install an example IoT infrastructure configuration:
+
[options="nowrap",subs="attributes"]
----
ifeval::["{cmdcli}" == "kubectl"]
{cmdcli} apply -f install/components/iot/examples/iot-config-k8s.yaml
endif::[]
ifeval::["{cmdcli}" == "oc"]
{cmdcli} apply -f install/components/iot/examples/iot-config.yaml
endif::[]
----
