[id='troubleshooting-{context}']

= Determine which pods belong to an address space

.Procedure

. Retrieve the uuid for the address space:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get addressspace _myspace_ -o jsonpath='{.metadata.annotations.enmasse\.io/infra-uuid}'
----

. Find all pods with a matching `infraUuid` label:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get pods -l infraUuid=_uuid_
----

= Determine the currently running version of {ProductName}

.Procedure

. Determine the `enmasse-operator` pod name:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get pods | grep enmasse-operator
----

. Print the `VERSION` environment of the `enmasse-operator` pod:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} rsh _enmasse-operator-...._ env | grep VERSION
----

+
The `VERSION` corresponds to the major.minor version of {ProductName}, whereas `MAVEN_VERSION` corresponds to the build number.

= Unable to find a custom address space plan

.Procedure 

. Ensure that the address space plan was created in the namespace where {ProductName} is installed. 
. Ensure that the address space plan has passed validation and is in the `Active` phase:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get addressspaceplans -o wide -n {ProductNamespace}
----

= Unable to find a custom address plan

.Procedure 

. Ensure that the address plan was created in the namespace where {ProductName} is installed. 
. Ensure that the address plan has passed validation and is in the `Active` phase:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get addressplans -o wide -n {ProductNamespace}
----

= Address space is not ready and clients are unable to connect to messaging endpoints

.Procedure
. Check the address space status message for errors:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get addressspace _myspace_ -o wide
----

. Check address space controller logs for errors:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} logs deployment/address-space-controller
----

= Addresses are not getting ready

.Procedure
. Check the address status message for errors:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get address _myspace.myaddress_ -o wide
----

. If using the `brokered` address space, check the `agent` pod logs for errors:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} logs deployment/agent._uuid_
----

+
If using the `standard` address space, check the `admin` pod logs for errors:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} logs deployment/admin._uuid_ -c standard-controller
{cmdcli} logs deployment/admin._uuid_ -c agent
----

= Examining the state of a broker using the {BrokerName} management interfaces

If a problem is suspected with a Broker associated with an address space, you can examine the state of the
broker directly using its in-built link:{BrokerManagementDocs}[management interfaces].  {ProductName} exposes the
{BrokerName}'s CLI and JMX  (via Jolokia).  It does not expose the {BrokerName} Console.

.Procedure

ifeval::["{cmdcli}" == "oc"]
. Log in as a service admin:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} login -u admin
----

. Change to the project where {ProductName} is installed:
+
[subs="+quotes,attributes",options="nowrap"]
----
{cmdcli} project _{ProductNamespace}_
----
endif::[]

. Retrieve the uuid for the address space:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get addressspace _myspace_ -o jsonpath='{.metadata.annotations.enmasse\.io/infra-uuid}'
----

. Retrieve the broker support credentials (username and password) for the address space:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get secret broker-support-_uuid_  --template='{{.data.username}}' | base64 --decode
{cmdcli} get secret broker-support-_uuid_  --template='{{.data.password}}' | base64 --decode
----

. Identify the broker pod name:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get pods -l infraUuid=_uuid_,role=broker
----
+
In the standard address, there may be many brokers.  To identify the broker(s) hosting a particular queue, use this command:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} get address _address resource name_  -o jsonpath="{.status.brokerStatuses[*].containerId}"
----
+

. Execute support commands on the broker's pod:
+
To execute an {BrokerName} Jolokia JMX commands, use a command line like this:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} exec _broker pod name_ -- {BrokerCLI} address show --user _username_ --password _password_
----
+
To execute an {BrokerName} CLI command, use a command similar to the following:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} oc exec _broker pod name_ -- curl --silent --insecure --user _username_:_password_ 'https://localhost:8161/console/jolokia/read/org.apache.activemq.artemis:broker="_broker pod name_"/AddressMemoryUsage'
----
+
IMPORTANT: The double quotes around the broker pod name within the URL are required. Make sure you protect them from your
command shell (as done above using the single quotes surrounding the whole URL). If they are not present, you will
receive an authorization failure.
+
