// Module included in the following assemblies:
// 
// assembly-iot-service-admin-guide.adoc
// assembly-iot-getting-started.adoc

[id='proc-iot-service-registry-jdbc-{context}']
= Deploy JDBC external device registry

Using an external database requires you to create a database instance and
create the required tables and indices.

[IMPORTANT]
====
Although it should technically be possible to use any database which provides
a JDBC driver and support SQL, at the moment, only PostgreSQL is supported by
{ProductName}. Unless explicitly mentioned, this documentation will assume
your are using PostgreSQL. If you do not, then you might need to adapter provided
commands, and SQL statements.
====

In order to set up a JDBC based device registry, you need to perform
the following steps:

== Choose a data storage model

The JDBC based device registry supports the following data models:

* Flat JSON
* Hierarchical JSON
* Plain tables

The JSON based data models require no locking or foreign keys. However they
do rely on PostgreSQL support for JSONB. The flat JSON model is more flexible
when it comes to storing different types of credentials. The hierarchical JSON
model has better performance over the flat JSON model, but requires dedicated
indices for each credentials type in order to achieve this performance.

The plain table model does not require any JSON specific database support, but
require multiple tables, linked with foreign keys, and will need support for
locking when making changes. On the other side it will have better read
performance in most cases.

The default choice is the hierarchical JSON model.

NOTE: It is not possible to change the data model later on without loosing all data
or manual data migration.

== Create a database instance

First you need to create a database instance. It is recommended that you also
create at least two types of users. One for administrating the database and
one for accessing the device registry specific tables. In the following sections
the former user is assumed to be named "admin", and the latter "registry".

== Deploy the SQL schema to the database instance

.Prerequisites
* Created a database instance
* Have access credentials for the "admin" database user

.Procedure

. Connect to your database instance using the admin user
. Review and deploy the SQL schema `templates/iot/examples/postgresql/create.sql`

== Configure the IoT infrastructure

In order to enable the external JDBC device registry implementation, you will
need to configure the section `.spec.services.deviceRegistry.jdbc.server.external`,
and provide the chosen data model, database connection information and access credentials.

For an example see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#iot-registry-example-registry-jdbc-{context}[Configuration for JDBC with external PostgreSQL].

