// Module included in the following assemblies:
//
// assembly-monitoring-oc.adoc
// assembly-monitoring-kube.adoc

[id='restart-component-{context}']
= Restarting components to acquire security fixes

Restarting {ProductName} components is required to get image updates for CVEs. The scripts are provided in the {ProductName} installation files within the `script` folder. To restart all components, run all scripts.

== Restarting Operators

Operators can be restarted without affecting the messaging system.

.Procedure

* Run the `restart-operators.sh` script:
+
[options="nowrap",subs="+quotes,attributes"]
----
./scripts/restart-operators.sh {ProductNamespace}
----

== Restarting authentication services

Authentication service restarts will temporarily affect new messaging connections. Existing connections will continue to work even if the authentication service is restarted.

.Procedure

* Run the `restart-authservices.sh` script:
+
[options="nowrap",subs="+quotes,attributes"]
----
./scripts/restart-authservices.sh {ProductNamespace}
----

== Restarting routers

Messaging routers are only deployed in the `standard` address space type. The script assumes that at least two replicas of the router are running and performs a rolling restart. Messaging clients connected to the restarting router are disconnected and must reconnect to be served by a different router.

.Procedure

* Run the `restart-routers.sh` script, which requires at least one router to be available:
+
[options="nowrap",subs="+quotes,attributes"]
----
./scripts/restart-routers.sh {ProductNamespace} 1
----

== Restarting brokers

For the `brokered` address space type, restarting the broker causes downtime temporarily to messaging clients while the broker is restarted. For the `standard` address space type, messaging clients are not disconnected from the messaging routers, but clients are not able to consume messages stored on the restarting broker.

.Procedure

* Run the `restart-brokers.sh` script:
+
[options="nowrap",subs="+quotes,attributes"]
----
./scripts/restart-brokers.sh {ProductNamespace}
----

