// Module included in the following assemblies:
//
// assembly-managing-address-spaces.adoc

[id='proc-change-address-space-auth-service-console-{context}']
= Changing the authentication service associated with an address space using the {ConsoleName}

You can change the authentication service that is associated with an address space using the {ConsoleName}.

.Prerequisites
* You must have already created an address space. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#proc-create-address-space-console-messaging[Creating an address space using the {ConsoleName}].

.Procedure

. Log in to the {ConsoleName}. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#logging-into-console-messaging[Accessing the {ConsoleName}].

. Locate the address space for which you want to change the authentication service.

. In the far right column, click the vertical ellipsis icon and select *Edit*. The Edit window opens.

. In the *Authentication Service* field, select a different authentication service from the list and click *Confirm*. The authentication service is changed for that address space.
