// Module included in the following assemblies:
//
// rhassemblies/assembly-installing-olm-rh.adoc

[id="proc-olm-installing-from-operatorhub-using-console-{context}"]
= Installing {ProductName} from the OperatorHub using the {KubePlatform} console

You can install the {ProductName} Operator on an {KubePlatform} 4.x cluster by using OperatorHub in the {KubePlatform} console.

ifdef::LtsStatement[]
[IMPORTANT]
====
* {ProductName} {ProductVersion} has been designated as a Long Term Support (LTS) release version. Bug fixes and security advisories will be made available for {ProductName} {ProductVersion} in a series of micro releases (1.7.1, 1.7.2, 1.7.3, and so on) until the product’s end of life.

* You need to install the latest LTS version of the Operator for {ProductName} {ProductVersion}. To install the latest LTS version for {ProductName} {ProductVersion}, select the operator channel labeled `stable`.
====
endif::LtsStatement[]


.Prerequisites

* Access to an {KubePlatform} 4.x cluster and an account with `cluster-admin` permissions.

.Procedure

. In the {KubePlatform} 4.x console, log in using an account with `cluster-admin` privileges.

. To create the project where you want to deploy {ProductName}, click *Home > Projects*, and then click *Create Project*. The Create Project window opens.

. In the *Name* field, type `{ProductNamespace}` and click *Create*. The `{ProductNamespace}` project is created.

. Click *Operators > OperatorHub*.

. In the *Filter by keyword* box, type `{ProductName}` to find the {ProductName} Operator.

. Click the {ProductName} Operator.  Information about the Operator is displayed.

. Read the information about the Operator and click *Install*.

. On the *Install Operator* page:

.. Under *Installation Mode*, click *A specific namespace on the cluster*.

.. From the *Installed Namespace* drop-down list, select the `{ProductNamespace}` namespace.

.. Accept all of the remaining default selections and click *Install*.

When the Operator installation is complete, the *Installed Operators* page opens. You should see that the {ProductName} Operator is installed in the project namespace that you specified.

For troubleshooting information, see the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html-single/operators/index#olm-installing-operators-from-operatorhub_olm-adding-operators-to-a-cluster[{KubePlatform} documentation].

.Next steps

* link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#assembly-configuring-olm-messaging[Configure {ProductName} using the {KubePlatform} console]
