// Module included in the following assemblies:
//
// assembly-installing-manual-steps.adoc
ifeval::["{cmdcli}" == "oc"]
[id='deploying-service-broker-{context}']
= (Optional) Deploying the service broker

The service broker provides an implementation of the Open Service Broker API that integrates with the {PlatformName} Service Catalog.

.Prerequisites
* The service broker requires the `standard` authentication service to be deployed.
ifeval::["{PlatformName}" == "OpenShift"]
* To install the {ProductName} Service Broker on {PlatformName}, you must have `cluster-admin` access to set up the
required roles for delegating authentication to the {PlatformName} master; otherwise, you are restricted
to using templates for creating address spaces. For more information about how to deploy without `cluster-admin` access,
which restricts {ProductName} to using templates, see xref:installing-without-cluster-admin-privileges-{context}[].
endif::[]
* Modify the installation files according to the namespace the Service Broker is going to be installed in
+
[source, subs="+quotes"]
----
sed -i 's/namespace: .\*/namespace: _<my-namespace>_/' examples/install/service-broker/*.yaml
sed -i 's/namespace: .\*/namespace: _<my-namespace>_/' examples/install/cluster-service-broker/*.yaml
----

.Procedure

. Deploy the Service Broker:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f examples/install/service-broker
----

. Register the Service Broker with the OpenShift Service Catalog:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f examples/install/cluster-service-broker
----
endif::[]
