// Module included in the following assemblies:
//
// assembly-connecting-applications.adoc

[id='proc-client-get-cer-{context}']
= Retrieving the self-signed CA certificate

If you opted for the `selfsigned` certificate provider type in your `AddressSpace` endpoint configuration, the generated CA
that signed the `AddressSpace` server certificate is required when connecting to the messaging client application. You can retrieve the
certificate from the `AddressSpace` using the following procedure.

WARNING: Using a self-signed certificate in production environments is not recommended.

.Procedure

ifeval::["{cmdcli}" == "oc"]
. Log in as a messaging tenant:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} login -u developer
----
endif::[]

. Retrieve the CA certificate from the `AddressSpace`.
+
This will give you a file containing the CA certificate, in PEM format.
+
[subs="+quotes,attributes",options="nowrap"]
----
{cmdcli} get addressspace _myspace_ -n _namespace_ -o jsonpath='{.status.caCert}{"\n"}' | base64 --decode > ca.crt
----

. If a PKCS12 or JKS format trust store is required, use the following commands to generate one:
+
For PKS:
+
[subs="+quotes,attributes",options="nowrap"]
----
keytool -import -trustcacerts -alias root -file ca.crt -storetype pkcs12 -keystore ca.pkcs12 -storepass _password_ -noprompt
----
For JKS:
+
[subs="+quotes,attributes",options="nowrap"]
----
keytool -import -trustcacerts -alias root -file ca.crt -storetype jks -keystore ca.jsk -storepass _password_ -noprompt
----
