// Module included in the following assemblies:
//
// assembly-uninstalling.adoc

ifeval::["{cmdcli}" == "oc"]
:OperatorNamespace: openshift-operators
endif::[]

ifeval::["{cmdcli}" == "kube"]
:OperatorNamespace: operators
endif::[]

[id='uninstalling-olm-{context}']
= Uninstalling {ProductName} using the Operator Lifecycle Manager (OLM)

This method uninstalls {ProductName} that was installed using the Operator Lifecycle Manager (OLM).

.Procedure

ifeval::["{cmdcli}" == "oc"]
. Log in as a user with `cluster-admin` privileges:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} login -u system:admin
----
endif::[]

. Remove all `IoTProject` and `AddressSpace` instances:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete iotprojects -A --all
{cmdcli} delete addressspaces -A --all --timeout=600s
----

. Delete the subscription (replace `{OperatorName}` with the name of the subscription used in the installation):
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete subscription _{OperatorName}_ -n _{ProductNamespace}_
----

. Remove the CSV for the Operator:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete csv -l app=enmasse -n _{ProductNamespace}_
----

. Remove any remaining resources (replace `{ProductNamespace}` with the project where you installed {ProductName}):
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete all -l app=enmasse -n _{ProductNamespace}_
{cmdcli} delete cm -l app=enmasse -n _{ProductNamespace}_
{cmdcli} delete secret -l app=enmasse _{ProductNamespace}_
{cmdcli} delete consolelinks -l app=enmasse
{cmdcli} delete oauthclients -l app=enmasse
{cmdcli} delete crd -l app=enmasse
----

. (Optional: Skip this step if {ProductName} is installed in the `{OperatorNamespace}` namespace) Delete the namespace where {ProductName} was installed:
+
[options="nowrap",subs="+quotes,attributes"]
----
{cmdcli} delete namespace _{ProductNamespace}_
----

