// Module included in the following assemblies:
//
// assembly-installing-manual-steps.adoc

[id='deploying-api-server-{context}']
= Deploying the API server

The API server provides a REST API for creating address spaces and addresses. It can also serve as an aggregated API server if it is registered as an API service.

.Prerequisites
ifeval::["{PlatformName}" == "OpenShift"]
* To install the {ProductName} API Server on {PlatformName}, you must have `cluster-admin` access to set up the
required roles for delegating authentication to the {PlatformName} master; otherwise, you are restricted
to using templates for creating address spaces. For more information about how to deploy without `cluster-admin` access,
which restricts {ProductName} to using templates, see xref:installing-without-cluster-admin-privileges-{context}[].
endif::[]
* Modify the installation files according to the namespace the API Server is going to be installed in
+
[source, subs="+quotes"]
----
sed -i 's/namespace: .\*/namespace: _<my-namespace>_/' examples/install/api-service/*.yaml
sed -i 's/namespace: .\*/namespace: _<my-namespace>_/' examples/install/api-server/*RoleBinding*.yaml
----

.Procedure

. Register API service
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f examples/install/api-service
----

ifeval::["{cmdcli}" == "kubectl"]
. Create a certificate to use with the API server. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p api-server-cert/
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=api-server.enmasse.svc.cluster.local" -out api-server-cert/tls.crt -keyout api-server-cert/tls.key
----

. Create a secret containing the API server certificate:
+
[options="nowrap",subs="attributes"]
----
{cmdcli} create secret tls api-server-cert --cert=api-server-cert/tls.crt --key=api-server-cert/tls.key
----
endif::[]

. Deploy the API Server
+
[options="nowrap",subs="attributes"]
----
{cmdcli} apply -f examples/install/api-server/
----
