// Module included in the following assemblies:
//
// assembly-configuring-olm.adoc
// rhassemblies/assembly-configuring-olm-rh.adoc

[id="proc-create-address-space-plan-custom-resource-olm-ui-{context}"]
= Creating an address space plan custom resource using the {KubePlatform} console

You must create an address space plan custom resource to use {ProductName}. This procedure uses the example data that is provided when using the {KubePlatform} console.

.Procedure

. In the top right, click the *Plus* icon (+). The Import YAML window opens.

. From the top left drop-down menu, select the `{ProductNamespace}` project.

. Copy the following code:
+
[source,yaml,options="nowrap",subs="attributes"]
----
apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: standard-small
spec:
  addressSpaceType: standard
  infraConfigRef: default
  addressPlans:
    - standard-small-queue
  resourceLimits:
    router: 2.0
    broker: 3.0
    aggregate: 4.0
----

. In the Import YAML window, paste the copied code and click *Create*. The AddressSpacePlan overview page is displayed.

. Click *Operators > Installed Operators*.

. Click the {ProductName} Operator and click the *Address Space Plan* tab to verify that its *Status* displays as *Active*.

.Next steps

* link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#proc-create-address-plan-custom-resource-olm-ui-messaging[Create an address plan custom resource using the {KubePlatform} console]
