// Module included in the following assemblies:
//
// assembly-managing-addresses.adoc

[id='create-address-console-{context}']
= Creating addresses using the {ConsoleName}

You can create new addresses using the {ConsoleName}. The type of addresses that you can create are determined by the type of address space.

ifdef::Supported[]
For more information see the {ProductName} link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-supported-features-table-messaging[supported features table].
endif::Supported[]

.Prerequisites
* You must have created an address space. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#create-address-space-cli-messaging[Creating an address space].

.Procedure

. Log in to the {ConsoleName}. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#logging-into-console-messaging[Accessing the {ConsoleName}].

. Click the address space link for the address space where you want to create a new address.

. Click *Create Address*. The Create new address wizard opens.

. Complete the required fields and when you are finished, click *Finish* to create the new address. Your address is displayed in the {ConsoleName}.

NOTE: If you select the *subscription* address type, from the *Topic* list, select the topic name to which you want to create a subscription.
