// Module included in the following assemblies:
//
// assembly-upgrading.adoc

[id='post-upgrade-step-router-pod-{context}']
= Restarting router pods running a previous version of the image

When upgrading, sometimes a router pod is not automatically restarted by {KubePlatform}. If this issue occurs, it is important to manually restart the affected pod to ensure correct operation of the system. A scripts for restarting the router is provided in the {ProductName} installation files `script` folder. To restart all components, run all scripts.

.Prerequisites

* Completed the upgrading steps to a new release of {ProductName}. For more information on how to upgrade, see:
** link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#upgrading-enmasse-using-bundle-messaging[Upgrading {ProductName} using a YAML bundle]
** link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#upgrading-enmasse-using-ansible-messaging[Upgrading {ProductName} using Ansible]

.Procedure

* Run `restart-routers.sh` script:
+
[options="nowrap",subs="+quotes,attributes"]
----
./scripts/restart-routers.sh {ProductNamespace}
----