// Module included in the following assemblies:
//
// assembly-configure-infrastructure-configuration.adoc

[id='applying-infra-config-changes-{context}']
= Applying infrastructure configuration

You can edit existing configurations or create new ones.

.Prerequisites
* An infrastructure configuration change that you want to apply. For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#infrastructure-configuration-messaging[Infrastructure configuration].

.Procedure

ifeval::["{cmdcli}" == "oc"]
. Log in as a service operator:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} login -u developer
----

. Select the project where {ProductName} is installed:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} project enmasse
----
endif::[]

. Create infrastructure configuration:
+
[source,yaml,options="nowrap",subs="attributes"]
----
apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: myconfig
spec:
  version: "{EnMasseVersion}"
  admin:
    resources:
      memory: 256Mi
  broker:
    resources:
      memory: 2Gi
      storage: 100Gi
    addressFullPolicy: PAGE
  router:
    resources:
      memory: 256Mi
    linkCapcity: 1000
    minReplicas: 1
----

. Apply the configuration changes:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} apply -f standard-infra-config-example.yaml
----

. Monitor the pods while they are restarted:
+
[subs="attributes",options="nowrap"]
----
{cmdcli} get pods -w
----
+
The configuration changes will be applied within a couple of minutes.

