// Module included in the following assemblies:
//
// assembly-configuring.adoc

[id='ref-example-roles-{context}']
= {ProductName} example roles

{ProductName} provides the following example roles that you can use directly or use as models to create your own roles.

For more information about service administrator resources, see the link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-resources-table-service-admin-messaging[{ProductName} service administrator resources table].

ifdef::SingleBookLink[]
For more information about messaging tenant resources, see the link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-resources-table-messaging-tenant-messaging[{ProductName} messaging tenant resources table].
endif::SingleBookLink[]

ifndef::SingleBookLink[]
For more information about messaging tenant resources, see the link:{BookUrlBase}{BaseProductVersion}/html-single/using_amq_online_on_openshift_container_platform/#ref-resources-table-messaging-tenant-messaging[{ProductName} messaging tenant resources table].
endif::SingleBookLink[]

.{ProductName} example roles table
[cols="40%a,60%a",options="header",subs="attributes"]
|===
|Role |Description
|enmasse.io:tenant-view|Specifies `get` and `list` permissions for `addresses`, `addressspaces`, `addressspaceschemas`, and `messagingusers`
|enmasse.io:tenant-edit|Specifies `create`, `get`, `update`, `delete`, `list`, `watch`, and `patch` permissions for `addresses`, `addressspaces`, and `messagingusers`; `get` and `list` permissions for `addressspaceschemas`
|`service-admin` cluster role|Specifies `create`, `get`, `update`, `delete`, `list`, `watch`, and `patch` permissions for `addressplans`, `addressspaceplans`, `brokeredinfraconfigs`, and `standardinfraconfigs`
|===

:context: {parent-context}

