// Module included in the following assemblies:
//
// assembly-iot-service-admin-guide.adoc

[id='iot-project-managed-example']
= Using a managed messaging infrastructure

This IoT project configuration example relies on {ProductName} to manage the messaging infrastructure used by IoT traffic.
The {ProductName} `standard` address space and address plans are used.

[source,yaml,options="nowrap"]
----
include::../common/iot-project-managed-example.yaml[]
----
<1> The `managedStrategy` value refers to a messaging infrastructure managed by {ProductName}.
<2> Specifies the address space plan, defining the resource usage of the address space. Each IoT tenant must have its own address space.
<3> Each address must be associated with a valid address plan.
<4> Specifies the type of address space. The default value is `standard`.
+
ifdef::SingleBookLink[]
For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#managing-address-spaces-messaging[Managing address spaces].
endif::SingleBookLink[]

ifndef::SingleBookLink[]
For more information, see link:{BookUrlBase}{BaseProductVersion}{UsingGuideUrl}#managing-address-spaces-messaging[Managing address spaces].
endif::SingleBookLink[]

<5> Specifies the type of address.
+
ifdef::SingleBookLink[]
For more information, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#managing-address-spaces-messaging[Managing address spaces].
endif::SingleBookLink[]

ifndef::SingleBookLink[]
For more information, see link:{BookUrlBase}{BaseProductVersion}{UsingGuideUrl}#managing-address-spaces-messaging[Managing address spaces].
endif::SingleBookLink[]
