// Module included in the following assemblies:
//
// assembly-infrastructure-configuration.adoc

[id='ref-brokered-infra-config-override-probe-timeout-{context}']
= Overriding the probe timing for brokered infrastructure configuration

You can override the default values for the probe timing on broker resources.

The following example shows how to override certain default values of the readiness probe for broker resources.

[source,yaml,options="nowrap",subs="attributes"]
----
apiVersion: admin.enmasse.io/v1beta1
kind: BrokeredInfraConfig
metadata:
  name: brokered-infra-config
spec:
  broker:
    ...
    podTemplate:
      spec:
        containers:
          - name: broker <1>
            readinessProbe:
              failureThreshold: 6 <2>
              initialDelaySeconds: 20 <3>


----
<1> The `name` value must match the target container name. For a broker, the podTemplate name is `broker`.
<2> Specifies the number of times that {KubePlatform} tries when a Pod starts and the probe fails before either the Pod is marked `Unready` for a readiness probe, or restarting the container for a liveness probe. The default value is 3, and the minimum value is 1.
<3> Specifies the number of seconds before performing the first probe after the container starts.

ifeval::["{cmdcli}" == "kubectl"]
.Related links
* link:https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes[{KubePlatform} documentation about liveness and readiness probes (application health)]
endif::[]

ifeval::["{cmdcli}" == "oc"]
.Related links
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/dev-guide-application-health[{KubePlatform} 3.11 documentation on overriding probe timeouts]
* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html-single/nodes/index#nodes-nodes-health[{KubePlatform} 4.1 documentation on overriding probe timeouts]
endif::[]

