// Module included in the following assemblies:
//
// assembly-managing-address-spaces.adoc

[id='ref-address-space-example-auth-service-{context}']
= Address space example using authentication service

This address space example shows how you can configure the authentication service and endpoints of an `AddressSpace`.

[source,yaml,options="nowrap"]
----
include::../common/address-space-example2.yaml[]
----
<1> The address space type can be either `brokered` or `standard`.
<2> The address space plan depends on the address space type and what has been configured by the {ProductName} administrator. To view your available address space plans, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#proc-list-available-address-space-plans-messaging[Listing available address space plans].
<3> The authentication service name depends on the available authentication services configured by the {ProductName} administrator. To view the available authentication services for your address space type, see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#proc-list-available-auth-services-messaging[Listing available authentication services].
can be `none`, `standard` or `external`. `External` requires an additional field, `details`, which includes `host` and `port` information.
<4> The endpoints that must be configured for the `AddressSpace`.  Endpoints can specify either `messaging`, `console`, or `mqtt` services. However, the `mqtt` service is supported for the `standard` address space type only. Endpoints can be changed by replacing the address space.
<5> Exposes the configuration of an endpoint. Endpoints can be kept internal to the cluster, or exposed using an OpenShift route or a load-balancer service. Exposed configuration can be changed by replacing the address space.
<6> The certificate configuration can be used to specify how the endpoint certificate is provided.  The provider can be `selfsigned` (default), `wildcard` (requires it to be enabled by the {ProductName} administrator), `openshift` (signed by the OpenShift cluster CA), or `certBundle` (base64-encoded PEM key and certificate). When using the `certBundle` provider, the certificate can be rotated by updating the `tlsKey` and `tlsCert` values and replacing the address space.
<7> The endpoint information can be exported into a `ConfigMap`, `Secret`, or `Service` within the same namespace as the `AddressSpace`. This provides applications running on {KubePlatform} with a way to inject endpoint information or provide a proxy service in the same namespace as the application. For more information see link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#ref-address-space-example-exports-messaging][example exports format].

