// Module included in the following assemblies:
//
// assembly-iot-service-admin-guide.adoc

[id='iot-project-managed-example']
= Using a managed messaging infrastructure

This IoT project configuration example rely on {productName} to manage the messaging infrastructure used by iot traffic.
Here we use {productName} standard address space and address plans.

[source,yaml,options="nowrap"]
----
include::../common/iot-project-managed-example.yaml[]
----
<1> The `managedStrategy` value refers to an messaging infrastructure managed by {productName}.
<2> The address space plan, defining resource usage of the address space. Each iot tenant get his own address space.
<3> Each address must be declared with an valid address plan.
<4> The type of the address space. Default is `standard`. See link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#con-address-space-messaging[address space documentation] for more details.
<5> The type of the address. See link:{BookUrlBase}{BaseProductVersion}{BookNameUrl}#con-address-space-messaging[address space documentation] for more details.