// Module included in the following assemblies:
//
// assembly-iot-service-admin-guide.adoc

[id='ref-iot-metrics-{context}']
= IoT specific metrics

The IoT specific components of {ProductName} will provide the metrics described in this section.

== Common tags and metrics

The following tags are available on all IoT related components:

[options="header",]
|===
|Tag |Value |Description

|_host_ |_string_ |The name of the host that the component reporting the metric is running on.
|_component-type_ |`+adapter+`, `+service+` |The type of component reporting the metric.
|_component-name_ |_string_ |The name of the component reporting the metric. For a list of components, see the table below.
|===

The available components names are:

[options="header",]
|===
|Component |_component-name_
|HTTP protocol adapter |`+hono-http+`
|MQTT protocol adapter |`+hono-mqtt+`
|LoRaWAN protocol adapter |`+hono-lora+`
|Sigfox protocol adapter |`+hono-sigfox+`
|===

== Protocol adapters

Protocol adapters, components of type `+adapter+`, have some additional tags:

[options="header",]
|===
|Name |Value |Description
|_direction_ |`+one-way+`, `+request+`, `+response+` |The direction in
which a Command & Control message is being sent:`+one-way+` indicates a
command sent to a device for which the sending application doesn’t
expect to receive a response.`+request+` indicates a command request
message sent to a device.`+response+` indicates a command response
received from a device.

|_qos_ |`+0+`, `+1+`, `+unknown+` |The quality of service used for a
telemetry or event message.`+0+` indicates _at most once_,`+1+`
indicates _at least once_ and `+none+` indicates unknown delivery
semantics.

|_status_ |`+forwarded+`, `+unprocessable+`, `+undeliverable+` |The
processing status of a message.`+forwarded+` indicates that the message
has been forwarded to a downstream consumer`+unprocessable+` indicates
that the message has not been processed not forwarded, e.g. because the
message was malformed`+undeliverable+` indicates that the message could
not be forwarded, e.g. because there is no downstream consumer or due to
an infrastructure problem

|_tenant_ |_string_ |The identifier of the tenant that the metric is
being reported for

|_ttd_ |`+command+`, `+expired+`, `+none+` |A status indicating the
outcome of processing a TTD value contained in a message received from a
device.`+command+` indicates that a command for the device has been
included in the response to the device’s request for uploading the
message.`+expired+` indicates that a response without a command has been
sent to the device.`+none+` indicates that either no TTD value has been
specified by the device or that the protocol adapter does not support
it.

|_type_ |`+telemetry+`, `+event+` |The type of (downstream) message that
the metric is being reported for.
|===

The following metrics are specific to protocol adapters:

[width="100%",options="header",]
|===
|Metric |Type |Tags |Description
|_hono.commands.received_ |Timer |_host_, _component-type_,
_component-name_, _tenant_, _type_, _status_, _direction_ 
|The time it took to process a message conveying a command or
a response to a command.

|_hono.commands.payload_ |DistributionSummary |_host_, _component-type_,
_component-name_, _tenant_, _type_, _status_, _direction_ 
|The number of bytes conveyed in the payload of a command message.

|_hono.connections.authenticated_ |Gauge |_host_, _component-type_,
_component-name_, _tenant_
|Current number of connected, authenticated devices.

NOTE: This metric is only supported by protocol adapters that
maintain _connection state_ with authenticated devices. In particular,
the HTTP adapter does not support this metric.

|_hono.connections.unauthenticated_ |Gauge |_host_, _component-type_,
_component-name_
|Current number of connected, unauthenticated devices.

NOTE: This metric is only supported by protocol adapters that maintain
_connection state_ with authenticated devices. In particular, the HTTP
adapter does not support this metric.

|_hono.messages.received_ |Timer |_host_, _component-type_,
_component-name_, _tenant_, _type_, _status_, _qos_, _ttd_
|The time it took to process a message conveying a telemetry or event message.

|_hono.messages.payload_ |DistributionSummary |_host_, _component-type_,
_component-name_, _tenant_, _type_, _status_ 
|The number of bytes conveyed in the payload of a telemetry or event message.
|===
