// Module included in the following assemblies:
//
// assembly-managing-address-spaces.adoc

[id='ref-address-space-example-cert-providers-{context}']
= Configuring an address space certificate provider

This address space example shows how you can configure the endpoints of an `AddressSpace` to be configured using different certificate providers. The certificate provider determines how certificates are issued for the endpoints of an `AddressSpace`.

ifeval::["{cmdcli}" =="oc"]
== `openshift` provider

The `openshift` certificate provider can be used to configure endpoints with certificates signed by
the OpenShift Cluster CA.

[source,yaml,options="nowrap"]
----
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited
  authenticationService:
    name: standard-authservice
  endpoints:
  - name: messaging
    service: messaging
    cert:
     provider: openshift <1>
----
<1> (Required) The certificate provider type. The available types are `openshift` (on OpenShift only), `certBundle`, and `selfsigned` (default).
endif::[]

== `selfsigned` provider

The `selfsigned` certificate provider can be used to configure endpoints with self-signed
certificates. The CA for these certificates can be found in the `status.caCert` field of the
`AddressSpace` resource.

[source,yaml,options="nowrap"]
----
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited
  authenticationService:
    name: standard-authservice
  endpoints:
  - name: messaging
    service: messaging
    cert:
     provider: selfsigned <1>
----
<1> (Required) The certificate provider type. The available types are `openshift` (on OpenShift only), `certBundle`, and `selfsigned` (default).

== `certBundle` provider

The `certBundle` certificate provider can be used to configure endpoints with user-supplied
certificates signed by your own CA. Certificate rotation can be done by updating the `tlsKey` and
`tlsCert` fields with updated certificates, and then updating the `AddressSpace` resource.

[source,yaml,options="nowrap"]
----
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited
  authenticationService:
    name: standard-authservice
  endpoints:
  - name: messaging
    service: messaging
    cert:
     provider: certBundle <1>
     tlsKey: Y2VydGJ1bmRsZXByb3ZpZGVyY2VydA== <2>
     tlsCert: Y2VydGJ1bmRsZXByb3ZpZGVyY2VydA== <3> 
----
<1> (Required) The certificate provider type. The available types are `openshift` (on OpenShift only), `certBundle`, and `selfsigned` (default).
<2> (Required) The base64-encoded value of the PEM private key (including the preamble)
<3> (Required) The base64-encoded value of the PEM certificate (including the preamble)

