// Module included in the following assemblies:
//
// assembly-managing-addresses.adoc

[id='ref-address-example-message-redelivery-{context}']
= Address message redelivery/dead letter example

[source,yaml,options="nowrap"]
----
include::../common/address-example-message-redelivery.yaml[]
----
<1> (Optional) Destination for messages that have exceeded the maximum number of delivery attempts.  This address must be of type `deadletter`.
<2> (Optional) Provides message redelivery settings. Applies to address types `queue` and `subscription` only.
<3> (Optional) Maximum number of delivery attempts made for a message before the message is directed to a `deadletter` address (or dropped). Set to -1 for infinite re-deliveries.  Defaults to 10.
<4> (Optional) The number of milliseconds to wait before redelivery. Set to 0 for no redelivery delay.  Defaults to 0.
<5> (Optional) The redelivery multiplier. This factor is applied to the last redelivery delay. Defaults to 1.
<6> (Optional) The maximum delivery delay in milliseconds. Imposes an upper limit on the delivery delay. Set to 0 for no maximum.  Defaults to 0.

include::ref-message-redelivery.adoc[]

Message redelivery settings may also be defined by the address plan.  If both the address and address plan provide a message redelivery setting,
the value provided by the address takes priority. The address `status` section shows the
message redelivery settings that are in force.

If the address has a `deadletter` address assigned, messages that have exceeded the maximum number of delivery attempts are automatically moved to it.

If the address has no `deadletter` address assigned, the system drops the messages. These messages are lost permanently. footnote:[The standard address
space supports a *global DLQ* mode. If enabled in the `standardinfraconfig` the system will define address `!!GLOBAL_DLQ`.  These undelivered
message will be routed to it.  Connect a consuming application to `!!GLOBAL_DLQ` to process the messages and remove them from the broker(s).]
