apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:api-server
rules:
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "extension-apiserver-authentication" ]
    verbs: [ "get" ]
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaces", "addresses" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
