apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "api-server"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:api-server
subjects:
- kind: ServiceAccount
  name: api-server
  namespace: ${NAMESPACE}
