// +build !ignore_autogenerated

/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"

	v1beta1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedAdapterConfiguration) DeepCopyInto(out *AcceptedAdapterConfiguration) {
	*out = *in
	in.AdapterConfiguration.DeepCopyInto(&out.AdapterConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedAdapterConfiguration.
func (in *AcceptedAdapterConfiguration) DeepCopy() *AcceptedAdapterConfiguration {
	if in == nil {
		return nil
	}
	out := new(AcceptedAdapterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedConfiguration) DeepCopyInto(out *AcceptedConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make([]AcceptedAdapterConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(AcceptedTracingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = new(AcceptedResourceLimits)
		**out = **in
	}
	if in.TrustAnchors != nil {
		in, out := &in.TrustAnchors, &out.TrustAnchors
		*out = make([]AcceptedTrustAnchor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedConfiguration.
func (in *AcceptedConfiguration) DeepCopy() *AcceptedConfiguration {
	if in == nil {
		return nil
	}
	out := new(AcceptedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedResourceLimits) DeepCopyInto(out *AcceptedResourceLimits) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedResourceLimits.
func (in *AcceptedResourceLimits) DeepCopy() *AcceptedResourceLimits {
	if in == nil {
		return nil
	}
	out := new(AcceptedResourceLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedStatus) DeepCopyInto(out *AcceptedStatus) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedStatus.
func (in *AcceptedStatus) DeepCopy() *AcceptedStatus {
	if in == nil {
		return nil
	}
	out := new(AcceptedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedTracingConfiguration) DeepCopyInto(out *AcceptedTracingConfiguration) {
	*out = *in
	if in.SamplingModePerAuthId != nil {
		in, out := &in.SamplingModePerAuthId, &out.SamplingModePerAuthId
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedTracingConfiguration.
func (in *AcceptedTracingConfiguration) DeepCopy() *AcceptedTracingConfiguration {
	if in == nil {
		return nil
	}
	out := new(AcceptedTracingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedTrustAnchor) DeepCopyInto(out *AcceptedTrustAnchor) {
	*out = *in
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
	if in.AutoProvisioningEnabled != nil {
		in, out := &in.AutoProvisioningEnabled, &out.AutoProvisioningEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedTrustAnchor.
func (in *AcceptedTrustAnchor) DeepCopy() *AcceptedTrustAnchor {
	if in == nil {
		return nil
	}
	out := new(AcceptedTrustAnchor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdapterConfig) DeepCopyInto(out *AdapterConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(AdapterOptions)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdapterConfig.
func (in *AdapterConfig) DeepCopy() *AdapterConfig {
	if in == nil {
		return nil
	}
	out := new(AdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdapterConfiguration) DeepCopyInto(out *AdapterConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdapterConfiguration.
func (in *AdapterConfiguration) DeepCopy() *AdapterConfiguration {
	if in == nil {
		return nil
	}
	out := new(AdapterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdapterOptions) DeepCopyInto(out *AdapterOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdapterOptions.
func (in *AdapterOptions) DeepCopy() *AdapterOptions {
	if in == nil {
		return nil
	}
	out := new(AdapterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdapterStatus) DeepCopyInto(out *AdapterStatus) {
	*out = *in
	out.CommonStatus = in.CommonStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdapterStatus.
func (in *AdapterStatus) DeepCopy() *AdapterStatus {
	if in == nil {
		return nil
	}
	out := new(AdapterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptersConfig) DeepCopyInto(out *AdaptersConfig) {
	*out = *in
	if in.DefaultOptions != nil {
		in, out := &in.DefaultOptions, &out.DefaultOptions
		*out = new(AdapterOptions)
		**out = **in
	}
	in.AmqpAdapterConfig.DeepCopyInto(&out.AmqpAdapterConfig)
	in.HttpAdapterConfig.DeepCopyInto(&out.HttpAdapterConfig)
	in.MqttAdapterConfig.DeepCopyInto(&out.MqttAdapterConfig)
	in.SigfoxAdapterConfig.DeepCopyInto(&out.SigfoxAdapterConfig)
	in.LoraWanAdapterConfig.DeepCopyInto(&out.LoraWanAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptersConfig.
func (in *AdaptersConfig) DeepCopy() *AdaptersConfig {
	if in == nil {
		return nil
	}
	out := new(AdaptersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressConfig) DeepCopyInto(out *AddressConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressConfig.
func (in *AddressConfig) DeepCopy() *AddressConfig {
	if in == nil {
		return nil
	}
	out := new(AddressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressesConfig) DeepCopyInto(out *AddressesConfig) {
	*out = *in
	out.Telemetry = in.Telemetry
	out.Event = in.Event
	out.Command = in.Command
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressesConfig.
func (in *AddressesConfig) DeepCopy() *AddressesConfig {
	if in == nil {
		return nil
	}
	out := new(AddressesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmqpAdapterConfig) DeepCopyInto(out *AmqpAdapterConfig) {
	*out = *in
	in.CommonAdapterConfig.DeepCopyInto(&out.CommonAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmqpAdapterConfig.
func (in *AmqpAdapterConfig) DeepCopy() *AmqpAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(AmqpAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationServiceConfig) DeepCopyInto(out *AuthenticationServiceConfig) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationServiceConfig.
func (in *AuthenticationServiceConfig) DeepCopy() *AuthenticationServiceConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticationServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonAdapterConfig) DeepCopyInto(out *CommonAdapterConfig) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	in.AdapterConfig.DeepCopyInto(&out.AdapterConfig)
	in.Containers.DeepCopyInto(&out.Containers)
	in.Tls.DeepCopyInto(&out.Tls)
	in.EndpointConfig.DeepCopyInto(&out.EndpointConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonAdapterConfig.
func (in *CommonAdapterConfig) DeepCopy() *CommonAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(CommonAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonAdapterContainers) DeepCopyInto(out *CommonAdapterContainers) {
	*out = *in
	in.Adapter.DeepCopyInto(&out.Adapter)
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.ProxyConfigurator.DeepCopyInto(&out.ProxyConfigurator)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonAdapterContainers.
func (in *CommonAdapterContainers) DeepCopy() *CommonAdapterContainers {
	if in == nil {
		return nil
	}
	out := new(CommonAdapterContainers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonCondition) DeepCopyInto(out *CommonCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonCondition.
func (in *CommonCondition) DeepCopy() *CommonCondition {
	if in == nil {
		return nil
	}
	out := new(CommonCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonDeviceRegistry) DeepCopyInto(out *CommonDeviceRegistry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonDeviceRegistry.
func (in *CommonDeviceRegistry) DeepCopy() *CommonDeviceRegistry {
	if in == nil {
		return nil
	}
	out := new(CommonDeviceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonLoggingConfig) DeepCopyInto(out *CommonLoggingConfig) {
	*out = *in
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make(map[string]LogLevel, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonLoggingConfig.
func (in *CommonLoggingConfig) DeepCopy() *CommonLoggingConfig {
	if in == nil {
		return nil
	}
	out := new(CommonLoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonServiceConfig) DeepCopyInto(out *CommonServiceConfig) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	in.Tls.DeepCopyInto(&out.Tls)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonServiceConfig.
func (in *CommonServiceConfig) DeepCopy() *CommonServiceConfig {
	if in == nil {
		return nil
	}
	out := new(CommonServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	out.Endpoint = in.Endpoint
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigCondition) DeepCopyInto(out *ConfigCondition) {
	*out = *in
	in.CommonCondition.DeepCopyInto(&out.CommonCondition)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigCondition.
func (in *ConfigCondition) DeepCopy() *ConfigCondition {
	if in == nil {
		return nil
	}
	out := new(ConfigCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionInformation) DeepCopyInto(out *ConnectionInformation) {
	*out = *in
	out.Credentials = in.Credentials
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionInformation.
func (in *ConnectionInformation) DeepCopy() *ConnectionInformation {
	if in == nil {
		return nil
	}
	out := new(ConnectionInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfig) DeepCopyInto(out *ContainerConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfig.
func (in *ContainerConfig) DeepCopy() *ContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonSetTracingStrategy) DeepCopyInto(out *DaemonSetTracingStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonSetTracingStrategy.
func (in *DaemonSetTracingStrategy) DeepCopy() *DaemonSetTracingStrategy {
	if in == nil {
		return nil
	}
	out := new(DaemonSetTracingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceConnectionServiceConfig) DeepCopyInto(out *DeviceConnectionServiceConfig) {
	*out = *in
	if in.Infinispan != nil {
		in, out := &in.Infinispan, &out.Infinispan
		*out = new(InfinispanDeviceConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.JDBC != nil {
		in, out := &in.JDBC, &out.JDBC
		*out = new(JdbcDeviceConnection)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceConnectionServiceConfig.
func (in *DeviceConnectionServiceConfig) DeepCopy() *DeviceConnectionServiceConfig {
	if in == nil {
		return nil
	}
	out := new(DeviceConnectionServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRegistryServiceConfig) DeepCopyInto(out *DeviceRegistryServiceConfig) {
	*out = *in
	if in.Infinispan != nil {
		in, out := &in.Infinispan, &out.Infinispan
		*out = new(InfinispanDeviceRegistry)
		(*in).DeepCopyInto(*out)
	}
	if in.JDBC != nil {
		in, out := &in.JDBC, &out.JDBC
		*out = new(JdbcDeviceRegistry)
		(*in).DeepCopyInto(*out)
	}
	in.Management.DeepCopyInto(&out.Management)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRegistryServiceConfig.
func (in *DeviceRegistryServiceConfig) DeepCopy() *DeviceRegistryServiceConfig {
	if in == nil {
		return nil
	}
	out := new(DeviceRegistryServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamConfig) DeepCopyInto(out *DownstreamConfig) {
	*out = *in
	out.Addresses = in.Addresses
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamConfig.
func (in *DownstreamConfig) DeepCopy() *DownstreamConfig {
	if in == nil {
		return nil
	}
	out := new(DownstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfig) DeepCopyInto(out *EndpointConfig) {
	*out = *in
	if in.EnableDefaultRoute != nil {
		in, out := &in.EnableDefaultRoute, &out.EnableDefaultRoute
		*out = new(bool)
		**out = **in
	}
	if in.SecretNameStrategy != nil {
		in, out := &in.SecretNameStrategy, &out.SecretNameStrategy
		*out = new(SecretNameStrategy)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfig.
func (in *EndpointConfig) DeepCopy() *EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionImage) DeepCopyInto(out *ExtensionImage) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionImage.
func (in *ExtensionImage) DeepCopy() *ExtensionImage {
	if in == nil {
		return nil
	}
	out := new(ExtensionImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDeviceConnectionCacheNames) DeepCopyInto(out *ExternalDeviceConnectionCacheNames) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDeviceConnectionCacheNames.
func (in *ExternalDeviceConnectionCacheNames) DeepCopy() *ExternalDeviceConnectionCacheNames {
	if in == nil {
		return nil
	}
	out := new(ExternalDeviceConnectionCacheNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalInfinispanDeviceConnectionServer) DeepCopyInto(out *ExternalInfinispanDeviceConnectionServer) {
	*out = *in
	out.ExternalInfinispanServer = in.ExternalInfinispanServer
	if in.CacheNames != nil {
		in, out := &in.CacheNames, &out.CacheNames
		*out = new(ExternalDeviceConnectionCacheNames)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalInfinispanDeviceConnectionServer.
func (in *ExternalInfinispanDeviceConnectionServer) DeepCopy() *ExternalInfinispanDeviceConnectionServer {
	if in == nil {
		return nil
	}
	out := new(ExternalInfinispanDeviceConnectionServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalInfinispanRegistryServer) DeepCopyInto(out *ExternalInfinispanRegistryServer) {
	*out = *in
	out.ExternalInfinispanServer = in.ExternalInfinispanServer
	if in.CacheNames != nil {
		in, out := &in.CacheNames, &out.CacheNames
		*out = new(ExternalRegistryCacheNames)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalInfinispanRegistryServer.
func (in *ExternalInfinispanRegistryServer) DeepCopy() *ExternalInfinispanRegistryServer {
	if in == nil {
		return nil
	}
	out := new(ExternalInfinispanRegistryServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalInfinispanServer) DeepCopyInto(out *ExternalInfinispanServer) {
	*out = *in
	out.Credentials = in.Credentials
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalInfinispanServer.
func (in *ExternalInfinispanServer) DeepCopy() *ExternalInfinispanServer {
	if in == nil {
		return nil
	}
	out := new(ExternalInfinispanServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalJdbcDeviceConnectionServer) DeepCopyInto(out *ExternalJdbcDeviceConnectionServer) {
	*out = *in
	out.JdbcConnectionInformation = in.JdbcConnectionInformation
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]ExtensionImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalJdbcDeviceConnectionServer.
func (in *ExternalJdbcDeviceConnectionServer) DeepCopy() *ExternalJdbcDeviceConnectionServer {
	if in == nil {
		return nil
	}
	out := new(ExternalJdbcDeviceConnectionServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalJdbcRegistryServer) DeepCopyInto(out *ExternalJdbcRegistryServer) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(ExternalJdbcRegistryService)
		(*in).DeepCopyInto(*out)
	}
	if in.Adapter != nil {
		in, out := &in.Adapter, &out.Adapter
		*out = new(ExternalJdbcRegistryService)
		(*in).DeepCopyInto(*out)
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]ExtensionImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalJdbcRegistryServer.
func (in *ExternalJdbcRegistryServer) DeepCopy() *ExternalJdbcRegistryServer {
	if in == nil {
		return nil
	}
	out := new(ExternalJdbcRegistryServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalJdbcRegistryService) DeepCopyInto(out *ExternalJdbcRegistryService) {
	*out = *in
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	out.Connection = in.Connection
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalJdbcRegistryService.
func (in *ExternalJdbcRegistryService) DeepCopy() *ExternalJdbcRegistryService {
	if in == nil {
		return nil
	}
	out := new(ExternalJdbcRegistryService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRegistryCacheNames) DeepCopyInto(out *ExternalRegistryCacheNames) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRegistryCacheNames.
func (in *ExternalRegistryCacheNames) DeepCopy() *ExternalRegistryCacheNames {
	if in == nil {
		return nil
	}
	out := new(ExternalRegistryCacheNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAdapterConfig) DeepCopyInto(out *HttpAdapterConfig) {
	*out = *in
	in.CommonAdapterConfig.DeepCopyInto(&out.CommonAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAdapterConfig.
func (in *HttpAdapterConfig) DeepCopy() *HttpAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(HttpAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanDeviceConnection) DeepCopyInto(out *InfinispanDeviceConnection) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	out.CommonDeviceRegistry = in.CommonDeviceRegistry
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	in.Server.DeepCopyInto(&out.Server)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanDeviceConnection.
func (in *InfinispanDeviceConnection) DeepCopy() *InfinispanDeviceConnection {
	if in == nil {
		return nil
	}
	out := new(InfinispanDeviceConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanDeviceConnectionServer) DeepCopyInto(out *InfinispanDeviceConnectionServer) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalInfinispanDeviceConnectionServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanDeviceConnectionServer.
func (in *InfinispanDeviceConnectionServer) DeepCopy() *InfinispanDeviceConnectionServer {
	if in == nil {
		return nil
	}
	out := new(InfinispanDeviceConnectionServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanDeviceRegistry) DeepCopyInto(out *InfinispanDeviceRegistry) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	out.CommonDeviceRegistry = in.CommonDeviceRegistry
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	in.Server.DeepCopyInto(&out.Server)
	out.Management = in.Management
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanDeviceRegistry.
func (in *InfinispanDeviceRegistry) DeepCopy() *InfinispanDeviceRegistry {
	if in == nil {
		return nil
	}
	out := new(InfinispanDeviceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanRegistryManagement) DeepCopyInto(out *InfinispanRegistryManagement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanRegistryManagement.
func (in *InfinispanRegistryManagement) DeepCopy() *InfinispanRegistryManagement {
	if in == nil {
		return nil
	}
	out := new(InfinispanRegistryManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanRegistryServer) DeepCopyInto(out *InfinispanRegistryServer) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalInfinispanRegistryServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanRegistryServer.
func (in *InfinispanRegistryServer) DeepCopy() *InfinispanRegistryServer {
	if in == nil {
		return nil
	}
	out := new(InfinispanRegistryServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterServiceCertificates) DeepCopyInto(out *InterServiceCertificates) {
	*out = *in
	if in.SecretCertificatesStrategy != nil {
		in, out := &in.SecretCertificatesStrategy, &out.SecretCertificatesStrategy
		*out = new(SecretCertificatesStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceCAStrategy != nil {
		in, out := &in.ServiceCAStrategy, &out.ServiceCAStrategy
		*out = new(ServiceCAStrategy)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterServiceCertificates.
func (in *InterServiceCertificates) DeepCopy() *InterServiceCertificates {
	if in == nil {
		return nil
	}
	out := new(InterServiceCertificates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTConfig) DeepCopyInto(out *IoTConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTConfig.
func (in *IoTConfig) DeepCopy() *IoTConfig {
	if in == nil {
		return nil
	}
	out := new(IoTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTConfigList) DeepCopyInto(out *IoTConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IoTConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTConfigList.
func (in *IoTConfigList) DeepCopy() *IoTConfigList {
	if in == nil {
		return nil
	}
	out := new(IoTConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTConfigSpec) DeepCopyInto(out *IoTConfigSpec) {
	*out = *in
	if in.EnableDefaultRoutes != nil {
		in, out := &in.EnableDefaultRoutes, &out.EnableDefaultRoutes
		*out = new(bool)
		**out = **in
	}
	if in.ImageOverrides != nil {
		in, out := &in.ImageOverrides, &out.ImageOverrides
		*out = make(map[string]v1beta1.ImageOverride, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InterServiceCertificates != nil {
		in, out := &in.InterServiceCertificates, &out.InterServiceCertificates
		*out = new(InterServiceCertificates)
		(*in).DeepCopyInto(*out)
	}
	in.JavaDefaults.DeepCopyInto(&out.JavaDefaults)
	in.TlsDefaults.DeepCopyInto(&out.TlsDefaults)
	in.Mesh.DeepCopyInto(&out.Mesh)
	in.ServicesConfig.DeepCopyInto(&out.ServicesConfig)
	in.AdaptersConfig.DeepCopyInto(&out.AdaptersConfig)
	in.Tracing.DeepCopyInto(&out.Tracing)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Logging.DeepCopyInto(&out.Logging)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTConfigSpec.
func (in *IoTConfigSpec) DeepCopy() *IoTConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IoTConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTConfigStatus) DeepCopyInto(out *IoTConfigStatus) {
	*out = *in
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make(map[string]AdapterStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(map[string]ServiceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConfigCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTConfigStatus.
func (in *IoTConfigStatus) DeepCopy() *IoTConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IoTConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTProject) DeepCopyInto(out *IoTProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTProject.
func (in *IoTProject) DeepCopy() *IoTProject {
	if in == nil {
		return nil
	}
	out := new(IoTProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTProjectList) DeepCopyInto(out *IoTProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IoTProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTProjectList.
func (in *IoTProjectList) DeepCopy() *IoTProjectList {
	if in == nil {
		return nil
	}
	out := new(IoTProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTProjectSpec) DeepCopyInto(out *IoTProjectSpec) {
	*out = *in
	out.Downstream = in.Downstream
	in.Configuration.DeepCopyInto(&out.Configuration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTProjectSpec.
func (in *IoTProjectSpec) DeepCopy() *IoTProjectSpec {
	if in == nil {
		return nil
	}
	out := new(IoTProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTProjectStatus) DeepCopyInto(out *IoTProjectStatus) {
	*out = *in
	in.Accepted.DeepCopyInto(&out.Accepted)
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ProjectCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTProjectStatus.
func (in *IoTProjectStatus) DeepCopy() *IoTProjectStatus {
	if in == nil {
		return nil
	}
	out := new(IoTProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaContainerConfig) DeepCopyInto(out *JavaContainerConfig) {
	*out = *in
	in.ContainerConfig.DeepCopyInto(&out.ContainerConfig)
	if in.RequireNativeTls != nil {
		in, out := &in.RequireNativeTls, &out.RequireNativeTls
		*out = new(bool)
		**out = **in
	}
	in.Logback.DeepCopyInto(&out.Logback)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaContainerConfig.
func (in *JavaContainerConfig) DeepCopy() *JavaContainerConfig {
	if in == nil {
		return nil
	}
	out := new(JavaContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaContainerDefaults) DeepCopyInto(out *JavaContainerDefaults) {
	*out = *in
	if in.RequireNativeTls != nil {
		in, out := &in.RequireNativeTls, &out.RequireNativeTls
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaContainerDefaults.
func (in *JavaContainerDefaults) DeepCopy() *JavaContainerDefaults {
	if in == nil {
		return nil
	}
	out := new(JavaContainerDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcConnectionInformation) DeepCopyInto(out *JdbcConnectionInformation) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcConnectionInformation.
func (in *JdbcConnectionInformation) DeepCopy() *JdbcConnectionInformation {
	if in == nil {
		return nil
	}
	out := new(JdbcConnectionInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcDeviceConnection) DeepCopyInto(out *JdbcDeviceConnection) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	out.CommonDeviceRegistry = in.CommonDeviceRegistry
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	in.Server.DeepCopyInto(&out.Server)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcDeviceConnection.
func (in *JdbcDeviceConnection) DeepCopy() *JdbcDeviceConnection {
	if in == nil {
		return nil
	}
	out := new(JdbcDeviceConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcDeviceConnectionServer) DeepCopyInto(out *JdbcDeviceConnectionServer) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalJdbcDeviceConnectionServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcDeviceConnectionServer.
func (in *JdbcDeviceConnectionServer) DeepCopy() *JdbcDeviceConnectionServer {
	if in == nil {
		return nil
	}
	out := new(JdbcDeviceConnectionServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcDeviceRegistry) DeepCopyInto(out *JdbcDeviceRegistry) {
	*out = *in
	out.CommonDeviceRegistry = in.CommonDeviceRegistry
	in.Server.DeepCopyInto(&out.Server)
	out.Management = in.Management
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcDeviceRegistry.
func (in *JdbcDeviceRegistry) DeepCopy() *JdbcDeviceRegistry {
	if in == nil {
		return nil
	}
	out := new(JdbcDeviceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcRegistryManagement) DeepCopyInto(out *JdbcRegistryManagement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcRegistryManagement.
func (in *JdbcRegistryManagement) DeepCopy() *JdbcRegistryManagement {
	if in == nil {
		return nil
	}
	out := new(JdbcRegistryManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JdbcRegistryServer) DeepCopyInto(out *JdbcRegistryServer) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalJdbcRegistryServer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JdbcRegistryServer.
func (in *JdbcRegistryServer) DeepCopy() *JdbcRegistryServer {
	if in == nil {
		return nil
	}
	out := new(JdbcRegistryServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogbackConfig) DeepCopyInto(out *LogbackConfig) {
	*out = *in
	in.CommonLoggingConfig.DeepCopyInto(&out.CommonLoggingConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogbackConfig.
func (in *LogbackConfig) DeepCopy() *LogbackConfig {
	if in == nil {
		return nil
	}
	out := new(LogbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make(map[string]LogLevel, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Defaults = in.Defaults
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingDefaults) DeepCopyInto(out *LoggingDefaults) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingDefaults.
func (in *LoggingDefaults) DeepCopy() *LoggingDefaults {
	if in == nil {
		return nil
	}
	out := new(LoggingDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraWanAdapterConfig) DeepCopyInto(out *LoraWanAdapterConfig) {
	*out = *in
	in.CommonAdapterConfig.DeepCopyInto(&out.CommonAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraWanAdapterConfig.
func (in *LoraWanAdapterConfig) DeepCopy() *LoraWanAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(LoraWanAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedStatus) DeepCopyInto(out *ManagedStatus) {
	*out = *in
	in.PasswordTime.DeepCopyInto(&out.PasswordTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedStatus.
func (in *ManagedStatus) DeepCopy() *ManagedStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementConfig) DeepCopyInto(out *ManagementConfig) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementConfig.
func (in *ManagementConfig) DeepCopy() *ManagementConfig {
	if in == nil {
		return nil
	}
	out := new(ManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfig) DeepCopyInto(out *MeshConfig) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	in.ContainerConfig.DeepCopyInto(&out.ContainerConfig)
	in.Tls.DeepCopyInto(&out.Tls)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfig.
func (in *MeshConfig) DeepCopy() *MeshConfig {
	if in == nil {
		return nil
	}
	out := new(MeshConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MqttAdapterConfig) DeepCopyInto(out *MqttAdapterConfig) {
	*out = *in
	in.CommonAdapterConfig.DeepCopyInto(&out.CommonAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MqttAdapterConfig.
func (in *MqttAdapterConfig) DeepCopy() *MqttAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(MqttAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectCondition) DeepCopyInto(out *ProjectCondition) {
	*out = *in
	in.CommonCondition.DeepCopyInto(&out.CommonCondition)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectCondition.
func (in *ProjectCondition) DeepCopy() *ProjectCondition {
	if in == nil {
		return nil
	}
	out := new(ProjectCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLimits) DeepCopyInto(out *ResourceLimits) {
	*out = *in
	if in.MaximumConnections != nil {
		in, out := &in.MaximumConnections, &out.MaximumConnections
		*out = new(uint32)
		**out = **in
	}
	if in.MaximumTimeToLiveSeconds != nil {
		in, out := &in.MaximumTimeToLiveSeconds, &out.MaximumTimeToLiveSeconds
		*out = new(uint32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLimits.
func (in *ResourceLimits) DeepCopy() *ResourceLimits {
	if in == nil {
		return nil
	}
	out := new(ResourceLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCertificatesStrategy) DeepCopyInto(out *SecretCertificatesStrategy) {
	*out = *in
	if in.ServiceSecretNames != nil {
		in, out := &in.ServiceSecretNames, &out.ServiceSecretNames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCertificatesStrategy.
func (in *SecretCertificatesStrategy) DeepCopy() *SecretCertificatesStrategy {
	if in == nil {
		return nil
	}
	out := new(SecretCertificatesStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretNameStrategy) DeepCopyInto(out *SecretNameStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretNameStrategy.
func (in *SecretNameStrategy) DeepCopy() *SecretNameStrategy {
	if in == nil {
		return nil
	}
	out := new(SecretNameStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceCAStrategy) DeepCopyInto(out *ServiceCAStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceCAStrategy.
func (in *ServiceCAStrategy) DeepCopy() *ServiceCAStrategy {
	if in == nil {
		return nil
	}
	out := new(ServiceCAStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	out.CommonStatus = in.CommonStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesConfig) DeepCopyInto(out *ServicesConfig) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
	in.DeviceConnection.DeepCopyInto(&out.DeviceConnection)
	in.DeviceRegistry.DeepCopyInto(&out.DeviceRegistry)
	in.Tenant.DeepCopyInto(&out.Tenant)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesConfig.
func (in *ServicesConfig) DeepCopy() *ServicesConfig {
	if in == nil {
		return nil
	}
	out := new(ServicesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarTracingStrategy) DeepCopyInto(out *SidecarTracingStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarTracingStrategy.
func (in *SidecarTracingStrategy) DeepCopy() *SidecarTracingStrategy {
	if in == nil {
		return nil
	}
	out := new(SidecarTracingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigfoxAdapterConfig) DeepCopyInto(out *SigfoxAdapterConfig) {
	*out = *in
	in.CommonAdapterConfig.DeepCopyInto(&out.CommonAdapterConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigfoxAdapterConfig.
func (in *SigfoxAdapterConfig) DeepCopy() *SigfoxAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(SigfoxAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConfiguration) DeepCopyInto(out *TenantConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make(map[string]AdapterConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = new(ResourceLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(TracingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.TrustAnchors != nil {
		in, out := &in.TrustAnchors, &out.TrustAnchors
		*out = make([]TrustAnchor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConfiguration.
func (in *TenantConfiguration) DeepCopy() *TenantConfiguration {
	if in == nil {
		return nil
	}
	out := new(TenantConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantServiceConfig) DeepCopyInto(out *TenantServiceConfig) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	in.CommonServiceConfig.DeepCopyInto(&out.CommonServiceConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantServiceConfig.
func (in *TenantServiceConfig) DeepCopy() *TenantServiceConfig {
	if in == nil {
		return nil
	}
	out := new(TenantServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsOptions) DeepCopyInto(out *TlsOptions) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsOptions.
func (in *TlsOptions) DeepCopy() *TlsOptions {
	if in == nil {
		return nil
	}
	out := new(TlsOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfiguration) DeepCopyInto(out *TracingConfiguration) {
	*out = *in
	if in.SamplingModePerAuthId != nil {
		in, out := &in.SamplingModePerAuthId, &out.SamplingModePerAuthId
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfiguration.
func (in *TracingConfiguration) DeepCopy() *TracingConfiguration {
	if in == nil {
		return nil
	}
	out := new(TracingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingStrategy) DeepCopyInto(out *TracingStrategy) {
	*out = *in
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(SidecarTracingStrategy)
		**out = **in
	}
	if in.DaemonSet != nil {
		in, out := &in.DaemonSet, &out.DaemonSet
		*out = new(DaemonSetTracingStrategy)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingStrategy.
func (in *TracingStrategy) DeepCopy() *TracingStrategy {
	if in == nil {
		return nil
	}
	out := new(TracingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustAnchor) DeepCopyInto(out *TrustAnchor) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustAnchor.
func (in *TrustAnchor) DeepCopy() *TrustAnchor {
	if in == nil {
		return nil
	}
	out := new(TrustAnchor)
	in.DeepCopyInto(out)
	return out
}
