// +build !ignore_autogenerated

/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddress) DeepCopyInto(out *MessagingAddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddress.
func (in *MessagingAddress) DeepCopy() *MessagingAddress {
	if in == nil {
		return nil
	}
	out := new(MessagingAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingAddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressBroker) DeepCopyInto(out *MessagingAddressBroker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressBroker.
func (in *MessagingAddressBroker) DeepCopy() *MessagingAddressBroker {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressCondition) DeepCopyInto(out *MessagingAddressCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressCondition.
func (in *MessagingAddressCondition) DeepCopy() *MessagingAddressCondition {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressList) DeepCopyInto(out *MessagingAddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MessagingAddress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressList.
func (in *MessagingAddressList) DeepCopy() *MessagingAddressList {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingAddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpec) DeepCopyInto(out *MessagingAddressSpec) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Anycast != nil {
		in, out := &in.Anycast, &out.Anycast
		*out = new(MessagingAddressSpecAnycast)
		**out = **in
	}
	if in.Multicast != nil {
		in, out := &in.Multicast, &out.Multicast
		*out = new(MessagingAddressSpecMulticast)
		**out = **in
	}
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(MessagingAddressSpecQueue)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(MessagingAddressSpecTopic)
		**out = **in
	}
	if in.Subscription != nil {
		in, out := &in.Subscription, &out.Subscription
		*out = new(MessagingAddressSpecSubscription)
		**out = **in
	}
	if in.DeadLetter != nil {
		in, out := &in.DeadLetter, &out.DeadLetter
		*out = new(MessagingAddressSpecDeadLetter)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpec.
func (in *MessagingAddressSpec) DeepCopy() *MessagingAddressSpec {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecAnycast) DeepCopyInto(out *MessagingAddressSpecAnycast) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecAnycast.
func (in *MessagingAddressSpecAnycast) DeepCopy() *MessagingAddressSpecAnycast {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecAnycast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecDeadLetter) DeepCopyInto(out *MessagingAddressSpecDeadLetter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecDeadLetter.
func (in *MessagingAddressSpecDeadLetter) DeepCopy() *MessagingAddressSpecDeadLetter {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecDeadLetter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecMulticast) DeepCopyInto(out *MessagingAddressSpecMulticast) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecMulticast.
func (in *MessagingAddressSpecMulticast) DeepCopy() *MessagingAddressSpecMulticast {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecMulticast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecQueue) DeepCopyInto(out *MessagingAddressSpecQueue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecQueue.
func (in *MessagingAddressSpecQueue) DeepCopy() *MessagingAddressSpecQueue {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecSubscription) DeepCopyInto(out *MessagingAddressSpecSubscription) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecSubscription.
func (in *MessagingAddressSpecSubscription) DeepCopy() *MessagingAddressSpecSubscription {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressSpecTopic) DeepCopyInto(out *MessagingAddressSpecTopic) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressSpecTopic.
func (in *MessagingAddressSpecTopic) DeepCopy() *MessagingAddressSpecTopic {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressSpecTopic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingAddressStatus) DeepCopyInto(out *MessagingAddressStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MessagingAddressCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]MessagingAddressBroker, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingAddressStatus.
func (in *MessagingAddressStatus) DeepCopy() *MessagingAddressStatus {
	if in == nil {
		return nil
	}
	out := new(MessagingAddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpoint) DeepCopyInto(out *MessagingEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpoint.
func (in *MessagingEndpoint) DeepCopy() *MessagingEndpoint {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointCondition) DeepCopyInto(out *MessagingEndpointCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointCondition.
func (in *MessagingEndpointCondition) DeepCopy() *MessagingEndpointCondition {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointList) DeepCopyInto(out *MessagingEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MessagingEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointList.
func (in *MessagingEndpointList) DeepCopy() *MessagingEndpointList {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointPort) DeepCopyInto(out *MessagingEndpointPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointPort.
func (in *MessagingEndpointPort) DeepCopy() *MessagingEndpointPort {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpec) DeepCopyInto(out *MessagingEndpointSpec) {
	*out = *in
	if in.Tls != nil {
		in, out := &in.Tls, &out.Tls
		*out = new(MessagingEndpointSpecTls)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]MessagingEndpointProtocol, len(*in))
		copy(*out, *in)
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(MessagingEndpointSpecCluster)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(MessagingEndpointSpecIngress)
		**out = **in
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(MessagingEndpointSpecRoute)
		**out = **in
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(MessagingEndpointSpecNodePort)
		**out = **in
	}
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(MessagingEndpointSpecLoadBalancer)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpec.
func (in *MessagingEndpointSpec) DeepCopy() *MessagingEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecCluster) DeepCopyInto(out *MessagingEndpointSpecCluster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecCluster.
func (in *MessagingEndpointSpecCluster) DeepCopy() *MessagingEndpointSpecCluster {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecIngress) DeepCopyInto(out *MessagingEndpointSpecIngress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecIngress.
func (in *MessagingEndpointSpecIngress) DeepCopy() *MessagingEndpointSpecIngress {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecLoadBalancer) DeepCopyInto(out *MessagingEndpointSpecLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecLoadBalancer.
func (in *MessagingEndpointSpecLoadBalancer) DeepCopy() *MessagingEndpointSpecLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecNodePort) DeepCopyInto(out *MessagingEndpointSpecNodePort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecNodePort.
func (in *MessagingEndpointSpecNodePort) DeepCopy() *MessagingEndpointSpecNodePort {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecNodePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecRoute) DeepCopyInto(out *MessagingEndpointSpecRoute) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecRoute.
func (in *MessagingEndpointSpecRoute) DeepCopy() *MessagingEndpointSpecRoute {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecTls) DeepCopyInto(out *MessagingEndpointSpecTls) {
	*out = *in
	if in.SelfSigned != nil {
		in, out := &in.SelfSigned, &out.SelfSigned
		*out = new(MessagingEndpointSpecTlsSelfSigned)
		**out = **in
	}
	if in.OpenShift != nil {
		in, out := &in.OpenShift, &out.OpenShift
		*out = new(MessagingEndpointSpecTlsOpenShift)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(MessagingEndpointSpecTlsSecret)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecTls.
func (in *MessagingEndpointSpecTls) DeepCopy() *MessagingEndpointSpecTls {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecTls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecTlsOpenShift) DeepCopyInto(out *MessagingEndpointSpecTlsOpenShift) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecTlsOpenShift.
func (in *MessagingEndpointSpecTlsOpenShift) DeepCopy() *MessagingEndpointSpecTlsOpenShift {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecTlsOpenShift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecTlsSecret) DeepCopyInto(out *MessagingEndpointSpecTlsSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecTlsSecret.
func (in *MessagingEndpointSpecTlsSecret) DeepCopy() *MessagingEndpointSpecTlsSecret {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecTlsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointSpecTlsSelfSigned) DeepCopyInto(out *MessagingEndpointSpecTlsSelfSigned) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointSpecTlsSelfSigned.
func (in *MessagingEndpointSpecTlsSelfSigned) DeepCopy() *MessagingEndpointSpecTlsSelfSigned {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointSpecTlsSelfSigned)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingEndpointStatus) DeepCopyInto(out *MessagingEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MessagingEndpointCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]MessagingEndpointPort, len(*in))
		copy(*out, *in)
	}
	if in.InternalPorts != nil {
		in, out := &in.InternalPorts, &out.InternalPorts
		*out = make([]MessagingEndpointPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingEndpointStatus.
func (in *MessagingEndpointStatus) DeepCopy() *MessagingEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(MessagingEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfra) DeepCopyInto(out *MessagingInfra) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfra.
func (in *MessagingInfra) DeepCopy() *MessagingInfra {
	if in == nil {
		return nil
	}
	out := new(MessagingInfra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingInfra) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraCondition) DeepCopyInto(out *MessagingInfraCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraCondition.
func (in *MessagingInfraCondition) DeepCopy() *MessagingInfraCondition {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraList) DeepCopyInto(out *MessagingInfraList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MessagingInfra, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraList.
func (in *MessagingInfraList) DeepCopy() *MessagingInfraList {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingInfraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraReference) DeepCopyInto(out *MessagingInfraReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraReference.
func (in *MessagingInfraReference) DeepCopy() *MessagingInfraReference {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpec) DeepCopyInto(out *MessagingInfraSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(NamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Router.DeepCopyInto(&out.Router)
	in.Broker.DeepCopyInto(&out.Broker)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpec.
func (in *MessagingInfraSpec) DeepCopy() *MessagingInfraSpec {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecBroker) DeepCopyInto(out *MessagingInfraSpecBroker) {
	*out = *in
	if in.InitImage != nil {
		in, out := &in.InitImage, &out.InitImage
		*out = new(v1beta1.ImageOverride)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(v1beta1.ImageOverride)
		**out = **in
	}
	if in.ScalingStrategy != nil {
		in, out := &in.ScalingStrategy, &out.ScalingStrategy
		*out = new(MessagingInfraSpecBrokerScalingStrategy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecBroker.
func (in *MessagingInfraSpecBroker) DeepCopy() *MessagingInfraSpecBroker {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecBrokerScalingStrategy) DeepCopyInto(out *MessagingInfraSpecBrokerScalingStrategy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(MessagingInfraSpecBrokerScalingStrategyStatic)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecBrokerScalingStrategy.
func (in *MessagingInfraSpecBrokerScalingStrategy) DeepCopy() *MessagingInfraSpecBrokerScalingStrategy {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecBrokerScalingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecBrokerScalingStrategyStatic) DeepCopyInto(out *MessagingInfraSpecBrokerScalingStrategyStatic) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecBrokerScalingStrategyStatic.
func (in *MessagingInfraSpecBrokerScalingStrategyStatic) DeepCopy() *MessagingInfraSpecBrokerScalingStrategyStatic {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecBrokerScalingStrategyStatic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecRouter) DeepCopyInto(out *MessagingInfraSpecRouter) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(v1beta1.ImageOverride)
		**out = **in
	}
	if in.ScalingStrategy != nil {
		in, out := &in.ScalingStrategy, &out.ScalingStrategy
		*out = new(MessagingInfraSpecRouterScalingStrategy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecRouter.
func (in *MessagingInfraSpecRouter) DeepCopy() *MessagingInfraSpecRouter {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecRouterScalingStrategy) DeepCopyInto(out *MessagingInfraSpecRouterScalingStrategy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(MessagingInfraSpecRouterScalingStrategyStatic)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecRouterScalingStrategy.
func (in *MessagingInfraSpecRouterScalingStrategy) DeepCopy() *MessagingInfraSpecRouterScalingStrategy {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecRouterScalingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraSpecRouterScalingStrategyStatic) DeepCopyInto(out *MessagingInfraSpecRouterScalingStrategyStatic) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraSpecRouterScalingStrategyStatic.
func (in *MessagingInfraSpecRouterScalingStrategyStatic) DeepCopy() *MessagingInfraSpecRouterScalingStrategyStatic {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraSpecRouterScalingStrategyStatic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingInfraStatus) DeepCopyInto(out *MessagingInfraStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MessagingInfraCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingInfraStatus.
func (in *MessagingInfraStatus) DeepCopy() *MessagingInfraStatus {
	if in == nil {
		return nil
	}
	out := new(MessagingInfraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingTenant) DeepCopyInto(out *MessagingTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingTenant.
func (in *MessagingTenant) DeepCopy() *MessagingTenant {
	if in == nil {
		return nil
	}
	out := new(MessagingTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingTenantCondition) DeepCopyInto(out *MessagingTenantCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingTenantCondition.
func (in *MessagingTenantCondition) DeepCopy() *MessagingTenantCondition {
	if in == nil {
		return nil
	}
	out := new(MessagingTenantCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingTenantList) DeepCopyInto(out *MessagingTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MessagingTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingTenantList.
func (in *MessagingTenantList) DeepCopy() *MessagingTenantList {
	if in == nil {
		return nil
	}
	out := new(MessagingTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MessagingTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingTenantSpec) DeepCopyInto(out *MessagingTenantSpec) {
	*out = *in
	if in.MessagingInfraRef != nil {
		in, out := &in.MessagingInfraRef, &out.MessagingInfraRef
		*out = new(MessagingInfraReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingTenantSpec.
func (in *MessagingTenantSpec) DeepCopy() *MessagingTenantSpec {
	if in == nil {
		return nil
	}
	out := new(MessagingTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingTenantStatus) DeepCopyInto(out *MessagingTenantStatus) {
	*out = *in
	if in.MessagingInfraRef != nil {
		in, out := &in.MessagingInfraRef, &out.MessagingInfraRef
		*out = new(MessagingInfraReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MessagingTenantCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingTenantStatus.
func (in *MessagingTenantStatus) DeepCopy() *MessagingTenantStatus {
	if in == nil {
		return nil
	}
	out := new(MessagingTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}
