[[installing-kubernetes]]

== Installing {ProductName} on Kubernetes

:cmdcli: kubectl

include::common/prerequisites-kubernetes.adoc[leveloffset=+1]

include::common/install-procedure.adoc[leveloffset+=1]

To simplify deployment, have a look at the `deploy.sh` script which should work on Linux
and Mac. You can invoke the deployment script with `-h` to view a list of options.

This guide will walk through the manual deployment procedure and should work on any platform
supporting the `kubectl` command line client.

==== Creating namespace for {ProductName}

. Create enmasse namespace:
+
[options="nowrap"]
----
kubectl create namespace enmasse
kubectl config set-context $(kubectl config current-context) --namespace=enmasse
----

==== Deploying authentication services

{ProductName} require at least 1 authentication service to be deployed. The authentication service
can either be none (allow all), standard (keycloak) or external (not managed by enmasse).

===== Deploying the none authentication service

.Procedure

. Create a certificate to use for the none authentication service. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p none-authservice-cert
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=none-authservice.enmasse.svc.cluster.local" -out none-authservice-cert/tls.crt -keyout none-authservice-cert/tls.key
----

. Create secret with the none authentication service certificate:
+
[options="nowrap"]
----
kubectl create secret tls none-authservice-cert --cert=none-authservice-cert/tls.crt --key=none-authservice-cert/tls.key
----

. Create the none authentication service:
+
[options="nowrap"]
----
kubectl apply -f ./resources/none-authservice/service.yaml
kubectl apply -f ./resources/none-authservice/deployment.yaml
----

===== Deploying the standard authentication service

.Procedure

. Create a certificate to use for the standard authentication service. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p standard-authservice-cert
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=standard-authservice.enmasse.svc.cluster.local" -out standard-authservice-cert/tls.crt -keyout standard-authservice-cert/tls.key
----

. Create secret with the standard authentication service certificate:
+
[options="nowrap"]
----
kubectl create secret tls standard-authservice-cert --cert=standard-authservice-cert/tls.crt --key=standard-authservice-cert/tls.key
----

. Create secret with keycloak admin credentials. Choose password wisely as this user will have complete access over authentication and authorization policies:
+
[options="nowrap"]
----
kubectl create secret generic keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password=myrandompassword
----

. Create the standard authentication service:
+
[options="nowrap"]
----
kubectl apply -f ./resources/standard-authservice/service.yaml
kubectl apply -f ./resources/standard-authservice/keycloak-deployment.yaml
kubectl apply -f ./resources/standard-authservice/controller-deployment.yaml
kubectl apply -f ./resources/standard-authservice/pvc.yaml
----

. Create keycloak configuration used by controller and service. For the messaging console and
keycloak controller to work, you need to specify the `httpUrl` setting. To get the service ip:
+
[options="nowrap"]
----
kubectl get service standard-authservice -o jsonpath={.spec.clusterIP}
----

. Create keycloak configuration:
[options="nowrap"]
----
AUTH_HOST=<value from one of the previous commands>
AUTH_PORT=8443 if using the service ip, 443 if using the route host
kubectl create configmap keycloak-config --from-literal=hostname=standard-authservice --from-literal=port=5671 --from-literal=httpUrl=https://$AUTH_HOST:$AUTH_PORT/auth --from-literal=caSecretName=standard-authservice-cert
----

==== Deploying {ProductName}

. Create service account for the {ProductName} address controller:
+
[options="nowrap"]
----
kubectl create sa enmasse-admin
----

. Install default plan and resource configuration
+
[options="nowrap"]
----
kubectl apply -f ./resources/resource-definitions/resource-definitions.yaml
kubectl apply -f ./resources/plans/standard-plans.yaml
kubectl apply -f ./resources/plans/brokered-plans.yaml
----

. Create a certificate to use for the address controller. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p address-controller-cert/
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=address-controller.enmasse.svc.cluster.local" -out address-controller-cert/tls.crt -keyout address-controller-cert/tls.key
----

. Create secret with address-controller certificate:
+
[options="nowrap"]
----
kubectl secret tls address-controller-cert --cert=address-controller-cert/tls.crt --key=address-controller-cert/tls.key
----

. Deploy address-controller:
+
[options="nowrap"]
----
kubectl apply -f ./resources/address-controller/deployment.yaml
kubectl apply -f ./resources/address-controller/service.yaml
kubectl apply -f ./resources/address-controller/address-space-definitions.yaml
----
+
The deployments required for running {ProductName} are now created.

. {ProductName} will be up and running once all pods in the 'enmasse' namespace are in the `Running` state:
+
[options="nowrap"]
----
kubectl get pods -n enmasse
----
