[[installing-openshift]]

== Installing {ProductName} on OpenShift

include::common/prerequisites-openshift.adoc[leveloffset=+1]

include::common/install-procedure.adoc[leveloffset+=1]


==== Installing {ProductName} in Single-Tenant Mode

{ProductName} can be deployed in either a single-tenant mode or a multi-tenant mode. Choose
single-tenant mode if you do not expect to be creating multiple isolated address spaces or if you do
not have cluster-admin privileges. Otherwise, choose multi-tenant mode.

.Procedure 

. To install {ProductName} in single-tenant mode run the following script:

+
[source,options="nowrap"]
----
./deploy-openshift.sh -m "https://localhost:8443" -n enmasse -o singletenant
----
+
Running this script creates the deployments required for running {ProductName} in single-tenant mode. Starting
up {ProductName} will take a while, usually depending on how fast it is able to download the Docker
images for the various components.

. You can use the REST API to check the status of the deployment:
+
[source,options="nowrap"]
----
curl http://$(oc get route restapi -o jsonpath='{.spec.host}')/v1/addressspaces/default
----
+
The deployment is finished when `status.isReady` is `true` in the returned JSON object.

==== Installing {ProductName} in Multi-Tenant Mode

{ProductName} can be deployed in either a single-tenant mode or a multi-tenant mode. Choose
single-tenant mode if you do not expect to be creating multiple isolated address spaces or if you do
not have cluster-admin privileges. Otherwise, choose multi-tenant mode.

.Procedure

. To install {ProductName} in multi-tenant mode, run the following script:
+
[source,options="nowrap"]
----
./deploy-openshift.sh -m "https://localhost:8443" -n enmasse -o multitenant
----

. Grant cluster-admin privileges:
+
[source,options="nowrap"]
----
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:$(oc project -q):enmasse-service-account
oc adm policy add-cluster-role-to-user cluster-admin developer
----
+
The deployments required for running {ProductName} in multi-tenant mode are created.
{ProductName} will be up and running once all pods in the 'enmasse' namespace are in the `Running` state:
+
[source,options="nowrap"]
----
oc get pods -n enmasse
----
