[[installing-openshift]]

:cmdcli: oc

== Installing {ProductName} on OpenShift

include::common/prerequisites-openshift.adoc[leveloffset=+1]

include::common/install-procedure.adoc[leveloffset+=1]

{ProductName} can be installed using automated link:https://www.ansible.com/[Ansible] playbooks, the
`deploy.sh` script, or the manual steps.

*NOTE*: You can invoke the deployment script with `-h` to view a list of options.

=== Installing {ProductName} using Ansible

Installing {ProductName} using Ansible requires creating an inventory file with the variables for configuring the
system. Example inventory files can be found in the `ansible/inventory` folder. For more information about the supported Ansible configuration settings see xref:ref_ansible-config-settings_enmasse[Ansible configuration settings].

An example inventory file that enables both the API server and Service Broker integration:

[source,options="nowrap"]
.link:service_admin/multitenant-all.inventory[multitenant-all.inventory]
----
include::multitenant-all.inventory[]
----

.Procedure

* Run the ansible playbook:
+
[options="nowrap"]
----
ansible-playbook -i <inventory file> ansible/playbooks/openshift/deploy_all.yml
----

=== Installing {ProductName} manually

The manual deployment procedure can be performed on any platform
supporting the OpenShift client.

include::installing-manual.adoc[leveloffset+=1]

include::installing-manual-singletenant.adoc[leveloffset+=1]
