[[installing-openshift]]

:cmdcli: oc

== Installing {ProductName} on OpenShift

include::common/prerequisites-openshift.adoc[leveloffset=+1]

include::common/install-procedure.adoc[leveloffset+=1]

To simplify deployment, have a look at the ansible playbooks in the `ansible/playbooks/openshift` folder.

This guide will walk through the manual deployment procedure and should work on any platform
supporting the OpenShift client.

==== Creating project for {ProductName}

. Create enmasse project:
+
[options="nowrap"]
----
oc new-project enmasse
----

==== Deploying authentication services

{ProductName} require at least 1 authentication service to be deployed. The authentication service
can either be none (allow all), standard (keycloak) or external (not managed by enmasse).

===== Deploying the none authentication service

.Procedure

. Create a certificate to use for the none authentication service. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p none-authservice-cert
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=none-authservice.enmasse.svc.cluster.local" -out none-authservice-cert/tls.crt -keyout none-authservice-cert/tls.key
----

. Create secret with the none authentication service certificate:
+
[options="nowrap"]
----
oc create secret tls none-authservice-cert --cert=none-authservice-cert/tls.crt --key=none-authservice-cert/tls.key
----

. Create the none authentication service:
+
[options="nowrap"]
----
oc create -f ./resources/none-authservice/service.yaml
oc create -f ./resources/none-authservice/deployment.yaml
----

===== Deploying the standard authentication service

.Procedure

. Create a certificate to use for the standard authentication service. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p standard-authservice-cert
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=standard-authservice.enmasse.svc.cluster.local" -out standard-authservice-cert/tls.crt -keyout standard-authservice-cert/tls.key
----

. Create secret with the standard authentication service certificate:
+
[options="nowrap"]
----
oc create secret tls standard-authservice-cert --cert=standard-authservice-cert/tls.crt --key=standard-authservice-cert/tls.key
----

. Create secret with keycloak admin credentials. Choose password wisely as this user will have complete access over authentication and authorization policies:
+
[options="nowrap"]
----
oc create secret generic keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password=myrandompassword
----

. Give view permissions for the keycloak controller:
+
[options="nowrap"]
----
oc adm policy add-role-to-user view system:serviceaccount:enmasse:default
----

. Create the standard authentication service:
+
[options="nowrap"]
----
oc create -f ./resources/standard-authservice/service.yaml
oc create -f ./resources/standard-authservice/keycloak-deployment.yaml
oc create -f ./resources/standard-authservice/controller-deployment.yaml
oc create -f ./resources/standard-authservice/pvc.yaml
oc create -f ./resources/standard-authservice/route.yaml
----

. Create keycloak configuration used by controller and service. To make the standard authservice
accessible for the messaging console and keycloak operator, you need to specify the `httpUrl`
setting. If you are running a local OpenShift cluster without a public DNS, use the internal service
IP for the hostname, otherwise use the hostname of the external route. To get the service ip:
+
[options="nowrap"]
----
oc get service standard-authservice -o jsonpath={.spec.clusterIP}
----
+
. Or, if you have a public hostname:
[options="nowrap"]
----
oc get route keycloak -o jsonpath={.spec.host}
----

. Create keycloak configuration:
[options="nowrap"]
----
AUTH_HOST=<value from one of the previous commands>
AUTH_PORT=8443 if using the service ip, 443 if using the route host
oc create configmap keycloak-config --from-literal=hostname=standard-authservice --from-literal=port=5671 --from-literal=httpUrl=https://$AUTH_HOST:$AUTH_PORT/auth --from-literal=caSecretName=standard-authservice-cert
----

==== Deploying {ProductName}

To deploy {ProductName}, it is recommended that you have cluster-admin access in order to set up the
required roles for creating namespaces and managing resources in those namespaces. See
<<openshift-install-single-address-space>> for how to deploy {ProductName} without cluster-admin
access, which will restrict it to a single address space.

.Procedure

. Create a service account for the {ProductName} address controller:
+
[options="nowrap"]
----
oc create sa enmasse-admin
----

. Create cluster-wide roles used by the `enmasse-admin` service account:
+
[options="nowrap"]
----
oc login -u system:admin
oc create -f ./resources/cluster-roles/enmasse-admin.yaml
----

. Grant cluster-admin privileges to service account:
+
[options="nowrap"]
----
oc login -u system:admin
oc policy add-role-to-user admin system:serviceaccount:enmasse:enmasse-admin
oc adm policy add-cluster-role-to-user enmasse-admin system:serviceaccount:enmasse:enmasse-admin
----
+
*Note*: You can log back in as the regular user after this step.

. Create a certificate to use for the address controller. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p address-controller-cert/
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=address-controller.enmasse.svc.cluster.local" -out address-controller-cert/tls.crt -keyout address-controller-cert/tls.key
----

. Create a secret containing the address-controller certificate:
+
[options="nowrap"]
----
oc create secret tls address-controller-cert --cert=address-controller-cert/tls.crt --key=address-controller-cert/tls.key
----

. Create address controller config:
+
[options="nowrap"]
----
oc create configmap address-controller-config --from-literal=enableRbac=true
----

. Install default plan and resource configuration
+
[options="nowrap"]
----
oc create -f ./resources/resource-definitions/resource-definitions.yaml
oc create -f ./resources/plans/standard-plans.yaml
oc create -f ./resources/plans/brokered-plans.yaml
----

. Deploy the address-controller:
+
[options="nowrap"]
----
oc create -f ./resources/address-controller/deployment.yaml
oc create -f ./resources/address-controller/service.yaml
oc create -f ./resources/address-controller/route.yaml
----
+
The deployments required for running {ProductName} are now created.

. {ProductName} will be up and running once all pods in the 'enmasse' namespace are in the `Running` state:
+
[options="nowrap"]
----
oc get pods -n enmasse
----

[[openshift-install-single-address-space]]
==== Deploying {ProductName} limited to a single address space

.Procedure

. Create service accounts for the {ProductName} address controller and address space:
+
[options="nowrap"]
----
oc create sa enmasse-admin
oc create sa address-space-admin
----

. Grant privileges required for viewing and managing resources:
+
[options="nowrap"]
----
oc policy add-role-to-user view system:serviceaccount:enmasse:default
oc policy add-role-to-user admin system:serviceaccount:enmasse:enmasse-admin
oc policy add-role-to-user admin system:serviceaccount:enmasse:address-space-admin
----

. Install default plan and resource configuration
+
[options="nowrap"]
----
oc create -f ./resources/resource-definitions/resource-definitions.yaml
oc create -f ./resources/plans/standard-plans.yaml
----

. Deploy default address space
+
[options="nowrap"]
----
oc process -f ./resources/templates/address-space.yaml NAME=default NAMESPACE=enmasse TYPE=standard PLAN=unlimited-standard | oc create -f -
----

. Create a certificate to use for the address controller. For testing purposes, you can create a self-signed certificate:
+
[options="nowrap"]
----
mkdir -p address-controller-cert/
openssl req -new -x509 -batch -nodes -days 11000 -subj "/O=io.enmasse/CN=address-controller.enmasse.svc.cluster.local" -out address-controller-cert/tls.crt -keyout address-controller-cert/tls.key
----

. Create secret with address-controller certificate:
+
[options="nowrap"]
----
oc create secret tls address-controller-cert --cert=address-controller-cert/tls.crt --key=address-controller-cert/tls.key
----

. Create address controller config:
+
[options="nowrap"]
----
oc create configmap address-controller-config --from-literal=enableRbac=true
----

. Deploy address-controller:
+
[options="nowrap"]
----
oc create -f ./resources/address-controller/deployment.yaml
oc create -f ./resources/address-controller/service.yaml
oc create -f ./resources/address-controller/route.yaml
oc create -f ./resources/address-controller/address-space-definitions.yaml
----
+
The deployments required for running {ProductName} are now created.

. {ProductName} will be up and running once all pods in the 'enmasse' namespace are in the `Running` state:
+
[options="nowrap"]
----
oc get pods -n enmasse
----
