[[plans]]

== Configuring plans and resource definitions

Plans are used to configure quotas and control the resources consumed by a particular deployment.  Plans are configured by the {ProductName} service operator, and selected when creating an address space and address.

Resource definitions are a description of some resource referenced by the plans, which may be configured with a template and parameters to be used when instantiating the template.

By default, {ProductName} comes with a set of plans and resource definitions that will be
sufficient for most uses.

This guide will explain how to create and modify plans to suit your needs.

[[address-space-plans]]
=== Address Space plans

Address space plans configure the quota available to a given address space. By default, {ProductName} comes with an 'unlimited' quota plan for both the standard and brokered address space.

Plans are configured as configmaps. Following is an example plan for the standard address space:

[source,yaml,options="nowrap"]
.link:service_admin/restrictive-plan.yaml[restrictive-plan.yaml]
----
include::restrictive-plan.yaml[]
----

The following fields are required:

* metadata.name
* resources
* addressPlans
* addressSpaceType

The other fields are only used by the console UI. Its also important to note the annotation 'defined-by', which points to a resource definition describing the infrastructure that should be deployed when an address space with this plan is created.

[[address-plans]]
=== Address plans

Address plans configure the expected resource usage of a given address. The sum of the resource usage for all resource types determines the amount of infrastructure provisioned for an address space. A single router and broker pod has a max usage of 1. If a new address requires additional resources, and the resource consumption is within the address space plan limits, a new pod will be created automatically to handle the increased load.

As you may have noticed in the previous section, the address space plan referenced 2 address plans, 'small-queue' and 'small-anycast'. These address plans are stored as configmaps and may be defined as follows:

[source,yaml,options="nowrap"]
.link:service_admin/small-queue-plan.yaml[small-queue-plan.yaml]
----
include::small-queue-plan.yaml[]
----

The following fields are required:

* metadata.name
* requiredResources
* addressType

A single router and broker can support 5 and 3 instances of addresses with this plan respectively.  If the number of addresses with this plan increases to 4, another broker is created. If it increases further to 6, another router is created as well.

Note, however, that although the address space plan allows 2 routers and 2 brokers to be deployed, it only allows 2 pods to be deployed in total. This means that the address space is restricted to 3 addresses with the 'small-queue' plan.

The 'small-anycast' plan does not consume any broker resources, and may provision 2 routers at the expense of not being able to create any brokers:

[source,yaml,options="nowrap"]
.link:service_admin/small-anycast-plan.yaml[small-anycast-plan.yaml]
----
include::small-anycast-plan.yaml[]
----

Up to 10 addresses with this plan may be created.

[[resource-definitions]]
=== Resource definitions

Resource describes a template along with a set of parameters. The resource definition is referenced from the plans. At present, only 3 resource definitions are supported:

* router
* broker
* broker-topic

Resource definitions with other names will not work with {ProductName}. It is, however, possible to modify these resource definitions to change the template and template parameters used when instantiating the infrastructure. For instance, the following configmap that increases the memory available for brokers can replace the default provided by {ProductName}:

[source,yaml,options="nowrap"]
.link:service_admin/broker-resource.yaml[broker-resource.yaml]
----
include::broker-resource.yaml[]
----
