/*
 * Copyright 2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by go generate; DO NOT EDIT.

package watchers

import (
	"fmt"
	tp "k8s.io/api/core/v1"
	cp "k8s.io/client-go/kubernetes/typed/core/v1"
	"github.com/enmasseproject/enmasse/pkg/consolegraphql/cache"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
	"log"
	"reflect"
)

type NamespaceWatcher struct {
	Namespace       string
	cache.Cache
	ClientInterface cp.CoreV1Interface
	watching        chan struct{}
    watchingStarted bool
	stopchan        chan struct{}
	stoppedchan     chan struct{}
}

func (kw *NamespaceWatcher) Init(c cache.Cache, cl interface{}) error {
	client, ok := cl.(cp.CoreV1Interface)
	if !ok {
		return fmt.Errorf("unexpected type %T", cl)
	}
	kw.Cache = c
	kw.ClientInterface = client
	kw.watching = make(chan struct{})
	kw.stopchan = make(chan struct{})
	kw.stoppedchan = make(chan struct{})
	return nil
}

func (kw *NamespaceWatcher) Watch() error {
	go func() {
		defer close(kw.stoppedchan)
		defer func() {
			if !kw.watchingStarted {
				close(kw.watching)
			}
		}()
		resource := kw.ClientInterface.Namespaces()
		log.Printf("Namespace - Watching")
		running := true
		for running {
			err := kw.doWatch(resource)
			if err != nil {
				log.Printf("Namespace - Restarting watch")
			} else {
				running = false
			}
		}
		log.Printf("Namespace - Watching stopped")
	}()

	return nil
}

func (kw *NamespaceWatcher) NewClientForConfig(config *rest.Config) (interface{}, error) {
	return cp.NewForConfig(config)
}

func (kw *NamespaceWatcher) AwaitWatching() {
	<-kw.watching
}

func (kw *NamespaceWatcher) Shutdown() {
	close(kw.stopchan)
	<-kw.stoppedchan
}

func (kw *NamespaceWatcher) doWatch(resource cp.NamespaceInterface) error {
	resourceList, err := resource.List(v1.ListOptions{})
	if err != nil {
		return err
	}

	curr, err := kw.Cache.GetMap("Namespace/", cache.UidKeyAccessor)

	var added = 0
	var updated = 0
	var unchanged = 0
	for _, res := range resourceList.Items {
		copy := res.DeepCopy()
		kw.updateKind(copy)

		if val, ok := curr[copy.UID]; ok {
			if !reflect.DeepEqual(val, copy) {
				err = kw.Cache.Add(copy)
				updated++
				if err != nil {
					return err
				}
			} else {
				unchanged++
			}
			delete(curr, copy.UID)
		} else {
			kw.Cache.Add(copy)
			added++
		}

		kw.Cache.Add(copy)
	}

	// Now remove any stale
	for _, stale := range curr {
		err = kw.Cache.Delete(stale)
		if err != nil {
			return err
		}
	}
	var stale = len(curr)

	log.Printf("Namespace - Cache initialised population added %d, updated %d, unchanged %d, stale %d", added, updated, unchanged, stale)
	resourceWatch, err := resource.Watch(v1.ListOptions{
		ResourceVersion: resourceList.ResourceVersion,
	})

	if ! kw.watchingStarted {
		close(kw.watching)
		kw.watchingStarted = true
	}

	ch := resourceWatch.ResultChan()
	for {
		select {
		case event := <-ch:
			var err error
			if event.Type == watch.Error {
				err = fmt.Errorf("Watch ended in error")
			} else {
				res, ok := event.Object.(*tp.Namespace)
				log.Printf("Namespace - Received event type %s", event.Type)
				if !ok {
					err = fmt.Errorf("Watch error - object of unexpected type received")
				} else {
					copy := res.DeepCopy()
					kw.updateKind(copy)
					switch event.Type {
					case watch.Added:
						err = kw.Cache.Add(copy)
					case watch.Modified:
						err = kw.Cache.Add(copy)
					case watch.Deleted:
						err = kw.Cache.Delete(copy)
					}
				}
			}
			if err != nil {
				return err
			}
		case <-kw.stopchan:
			log.Printf("Namespace - Shutdown received")
			return nil
		}
	}
}

func (kw *NamespaceWatcher) updateKind(o *tp.Namespace) {
	if o.TypeMeta.Kind == "" {
		o.TypeMeta.Kind = "Namespace"
	}
}
