---
kind: ConfigMap
apiVersion: v1
metadata:
  name: maas
data:
  json: |
    {
        "myqueue": { "store_and_forward":true, "multicast":false, "flavor": "vanilla-queue" },
        "mytopic": { "store_and_forward":true, "multicast":true, "flavor": "vanilla-topic" },
        "anycast": { "store_and_forward":false, "multicast":false },
        "broadcast": { "store_and_forward":false, "multicast":true }
    }
