---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: tls-topic-inmemory
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      address_config: address-config-${NAME}
      app: enmasse
      group_id: "${NAME}"
    name: "${NAME}"
  spec:
    replicas: 1
    selector:
      group_id: "${NAME}"
      role: broker
    template:
      metadata:
        labels:
          app: enmasse
          group_id: "${NAME}"
          role: broker
      spec:
        containers:
        - env:
          - name: TOPIC_NAME
            value: "${ADDRESS}"
          - name: GROUP_ID
            value: "${NAME}"
          image: artemis
          lifecycle:
            preStop:
              exec:
                command:
                - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
          livenessProbe:
            tcpSocket:
              port: amqp
          name: broker
          ports:
          - containerPort: 5673
            name: amqp
          - containerPort: 61616
            name: core
          volumeMounts:
          - mountPath: "/var/run/artemis"
            name: vol-${NAME}
        - env:
          - name: LINK_CAPACITY
            value: "${ROUTER_LINK_CAPACITY}"
          - name: TOPIC_NAME
            value: "${ADDRESS}"
          image: router
          livenessProbe:
            tcpSocket:
              port: amqp
          name: router
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 55673
            name: internal
            protocol: TCP
          - containerPort: 5671
            name: amqps
            protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
          volumeMounts:
          - mountPath: "/etc/qpid-dispatch/ssl"
            name: ssl-certs
            readOnly: true
        - env:
          - name: TOPIC_NAME
            value: "${ADDRESS}"
          image: topic-forwarder
          livenessProbe:
            httpGet:
              path: "/health"
              port: health
          name: forwarder
          ports:
          - containerPort: 8080
            name: health
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
        volumes:
        - emptyDir: {}
          name: vol-${NAME}
        - name: ssl-certs
          secret:
            secretName: qdrouterd-certs
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - broker
        from:
          kind: ImageStreamTag
          name: artemis:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - router
        from:
          kind: ImageStreamTag
          name: router:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - forwarder
        from:
          kind: ImageStreamTag
          name: topic-forwarder:latest
      type: ImageChange
- apiVersion: v1
  data:
    "${ADDRESS}": '{"store_and_forward": true, "multicast": true}'
  kind: ConfigMap
  metadata:
    labels:
      app: enmasse
      group_id: "${NAME}"
      type: address-config
    name: address-config-${NAME}
parameters:
- description: Storage capacity required for volume claims
  name: STORAGE_CAPACITY
  value: 2Gi
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: A valid name for the instance
  name: NAME
  required: true
- description: The address to use for the topic
  name: ADDRESS
  required: true
