---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: tls-queue-inmemory
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      address_config: address-config-${NAME}
      app: enmasse
      group_id: "${NAME}"
    name: "${NAME}"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          group_id: "${NAME}"
          role: broker
      spec:
        containers:
        - env:
          - name: QUEUE_NAME
            value: "${ADDRESS}"
          - name: GROUP_ID
            value: "${NAME}"
          image: "${BROKER_REPO}:latest"
          lifecycle:
            preStop:
              exec:
                command:
                - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
          livenessProbe:
            tcpSocket:
              port: amqp
          name: broker
          ports:
          - containerPort: 5673
            name: amqp
          - containerPort: 61616
            name: core
          volumeMounts:
          - mountPath: "/var/run/artemis"
            name: vol-${NAME}
        volumes:
        - emptyDir: {}
          name: vol-${NAME}
        - name: ssl-certs
          secret:
            secretName: qdrouterd-certs
- apiVersion: v1
  data:
    "${ADDRESS}": '{"store_and_forward": true, "multicast": false}'
  kind: ConfigMap
  metadata:
    labels:
      app: enmasse
      group_id: "${NAME}"
      type: address-config
    name: address-config-${NAME}
parameters:
- description: Storage capacity required for volume claims
  name: STORAGE_CAPACITY
  value: 2Gi
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: A valid name for the instance
  name: NAME
  required: true
- description: The address to use for the queue
  name: ADDRESS
  required: true
