== Overview

A feature requested by several users is the ability to connect address spaces to external AMQP endpoints. NOTE: this proposal does not cover bridging between address spaces on the same cluster.

The use cases covered by this proposal are:

1. Forwarding messages from a local queue in a local address space to a destination on a remote AMQP endpoint
1. Forwarding messages to a local queue in a local address space from a destination on a remote AMQP endpoint
1. Sending messages to a remote AMQP endpoint via a local address space - by creating a connector and using prefixing
1. Receiving messages from a remote AMQP endpoint via a local address space - by creating a connector and using prefixing

The external bridging feature requires a dispatch router to support the above use cases. This means that this feature will only be available in the standard address space to start off with, but may be implemented in the brokered address space as well by adding a router to handle the bridging.

== Design

The address space specification would be expanded with 2 addition sub-objects, `connectors` and `forwarders`. A connector configures the infrastructure to connect to a remote AMQP endpoint and add address matching rules with the specified addresses. A forwarder specifies message routing rules to/from a local address to a remote address.  

The `AddressSpace` resource is extended in the following manner:

```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: local
spec:
  type: standard
  plan: standard-small
  connectors:
  - name: remote1
    hostname: example.com
    port: 5672
    tls: # If not specified, do not enable TLS. Use just 'tls: {}' to enable TLS without any cert configuration.
      caCertSecret:
        name: remote1-secret # Secret containing CA to be trusted for this connector. NB! Secret must be readable by the system:serviceaccount:enmasse-infra:address-space-controller service account.
      clientCertSecret:
        name: client-remot1-secret # Secret containing client cert to be used for this connector. NB! Secret must be readable by the system:serviceaccount:enmasse-infra:address-space-controller service account.
    credentials:
      username: foo # Allow specifying credentials in plain text
      password: bar
      secret: # Allow specifying credentials in the secret using the k
        name:  mysecret
        usernameKeyRef: username # Optional, default is 'username'
        passwordKeyRef: password # Optional, default is 'password'
    addresses: # A list of remote addresses accessible via this address space. The addresses will be prefixed with the connector name (remote1/foo*). Addresses can be suffixed by a 'match all' wildcard.
    - name: foo*
  forwarders:
  - name: fwd1
    connector: remote1 # Reference to the connector used for the forwarding
    localAddress: myqueue # Address within local address space
    remoteAddress: foo/queue1 
    direction: in | out # Specifies if messages are forwarded from localAddress to remoteAddress or from remoteAddress to localAddress.
```

NOTE: The localAddress of a forwarder may not exist locally at the point of creating the address space. A forwarding rule will only be applied if the localAddress exists and if the remoteAddress is matched by any of the entries in the connector `addresses` field. Sanity checking on the forwarders and connectors is needed to ensure that invalid forwarding rules cannot be applied.

The sending and receiving messages to a remote AMQP endpoint via local address space use cases are covered by simply creating a connector and attaching client to 'connectorname/address'.

The forwarding use cases are covered by creating a connector and a forwarder referencing the connector. The direction field will determine if messages are forwarded from remote to local or from local to remote.

Authorization for remote addresses will work the same as for local addresses. MessagingUser with address patterns matching remote addresses are allowed to send/recv from those.

== Implementation

==== Api server

The api server will need to perform an extra set of validation when creating address spaces to ensure that references from forwarder to connector are correct and that remoteAddress matches an address in the connector. The api-server should not require remoteAddress in forwarders to exist because it may not have been created yet.

==== Address space controller

The address space controller will need to pass additional configuration to the router when starting up. When creating the address space, the router config configmap need to be programatically crafted in order for the additional information to be optionally added to the config. The connector and forwarder definitions will essentially end up defining a set of connectors and autoLinks in the router config.

This kind of fine-grained reconciliation is a direction we're likely to go in when moving the address-space-controller logic to the controller-manager (enmasse-operator) in the future, but will create additional code that have to be rewritten if we implement this in the address-space-controller.

To avoid that, as an alternative, we could put the responsibility of creating the router config configmap to the controller-manager as a first step in this direction (the configmap would then have to be removed from the template). From a maintenance POV it it might be better to have the logic in the same 'place' though, and the controller-manager would not be aware of any processing error in the address-space-controller such as failing to create the address space, in which case one would end up with a stale configmap.

== Testing

* Set up an AMQP broker (i.e. Artemis) on a remote host
* Configure an address space with connectors and forwarders for the 4 different use cases listed initially

== Documentation

The addifional fields should be added to the address space reference, and the tenant guide should be extended to cover the use cases as a realistic scenario with examples.
