== Overview

A feature requested by several users is the ability to connect address spaces to external AMQP endpoints. NOTE: this proposal does not cover bridging between address spaces on the same cluster.

The use cases covered by this proposal are:

1. Forwarding messages from a local queue in a local address space to a destination on a remote AMQP endpoint
1. Forwarding messages to a local queue in a local address space from a destination on a remote AMQP endpoint
1. Sending messages to a remote AMQP endpoint via a local address space - by creating a connector and using prefixing
1. Receiving messages from a remote AMQP endpoint via a local address space - by creating a connector and using prefixing

The external bridging feature requires a dispatch router to support the above use cases. This means that this feature will only be available in the standard address space to start off with, but may be implemented in the brokered address space as well by adding a router to handle the bridging.

== Design

The address space specification would be expanded with 2 addition sub-objects, `connectors` and `forwarders`. A connector configures the infrastructure to connect to a remote AMQP endpoint and add address matching rules with the specified addresses. A forwarder specifies message routing rules to/from a local address to a remote address.  

The `AddressSpace` resource is extended in the following manner:

```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: local
spec:
  type: standard
  plan: standard-small
  connectors:
  - name: remote1
    endpointHosts:
    - host: example.com
      port: 5671
    - host: failover.example.com
      port: 5671
    tls: # If not specified, do not enable TLS. Use just 'tls: {}' to enable TLS without any cert configuration.
      caCert:
	value: "" # PEM encoded value or
	valueFromSecret: # Certificate stored in secret
          name: remote1-secret # Secret containing CA to be trusted for this connector. NB! Secret must be readable by the system:serviceaccounts:enmasse-infra group.
	   key:  ca.crt # If using something different than default
      clientCert:
	value: "" # PEM encoded value or
	valueFromSecret: # Certificate stored in secret
	   name: client-remot1-secret # Secret containing client cert to be used for this connector. NB!  Secret must be readable by the system:serviceaccounts:enmasse-infra group.
    credentials:
      username:
        value: foo # Allow specifying credentials in plain text or
	valueFromSecret: # Using a secret
	  name: mysecret
          key: username # Optional, default is `username`
      password:
        value: bar # Allow specifying credentials in plain text or
	valueFromSecret: # Using a secret
	  name: mysecret
          key: password # Optional, default is `password`
      password: bar
    addresses: # A list of remote addresses accessible via this address space. The addresses will be prefixed with the connector name (remote1/foo*). Addresses follows the pattern format as described in https://qpid.apache.org/releases/qpid-dispatch-master/man/qdrouterd.conf.html#_address
    - name: foo
      pattern: foo*
status:
  connectors:
  - name: remote1
    isReady: true
    messages: [] # Error messages if not ready
```

The sending and receiving messages to a remote AMQP endpoint via local address space use cases are covered by simply creating a connector and attaching client to 'connectorname/address'.

Authorization for remote addresses will work the same as for local addresses. MessagingUser with address patterns matching remote addresses are allowed to send/recv from those.

Readiness of an address space is not affected by failing connectors. The `.status.connectors` field can be checked to view the state of connectors.

Metrics about each connector may be exposed in the address space controller prometheus endpoint.

To meet the forwarding use case, the `Address` resources is extended to enabled forwarding for address types that support it:

Should the need arise in the future, a separate `Connector` custom resource will be defined, and the entries in the connector list may specify the field `reference: connector1` to reference the connectors to be created.

```
kind: Address
spec:
  ...
  address: myqueue
  type: queue | subscription # Queue allows direction in and out. Subscription only allows direction out.
  forwarders:
  - name: fwd1
    remoteAddress: foo/queue1 
    direction: in | out # Specifies if messages are pushed to remoteAddress or pulled from remoteAddress.
status:
  forwarders:
  - name: fwd1
    isReady: true
    messages: [] # Error messages
```

NOTE: A forwarding rule will only be applied if remoteAddress is matched by any of the entries in the address space connector `addresses` field. Sanity checking on the forwarders and connectors is needed to ensure that invalid forwarding rules cannot be applied.

NOTE: A tenant may create a forwarder that pushes from a local queue to a remote queue without needing credentials to do so. This is acceptable at this point, but if stricter separation of roles is needed, one would need to add credentials for consuming from the local queue.

Readiness of an address is not affected by failing forwarders. The `.status.forwarders` field can be checked to view the state of forwarders.

The forwarding use cases are covered by creating a connector and setting forwarders field on an address. The direction field will determine if messages are forwarded from remote to local or from local to remote.

Metrics about the forwarders may be exposed in the standard controller prometheus endpoint.

== Implementation

==== Api server

The api server will need to perform an extra set of validation when creating addresses to ensure that remoteAddress matches an address in the connector of its address space. It will also ensure that only queues and subscriptions can have forwarders (and subscriptions only in outgoing direction).

==== Address space controller

The address space controller will need to pass additional configuration to the router when starting up. When creating the address space, the router config configmap need to be programatically crafted in order for the additional information to be optionally added to the config. The connector definitions will essentially end up defining a set of connectors in the router config.

NOTE: This kind of fine-grained reconciliation is a direction we're likely to go in when moving the address-space-controller logic to the controller-manager (enmasse-operator) in the future, but will create additional code that have to be rewritten if we implement this in the address-space-controller. The agreement is that we will go ahead with implementing it in the address-space-controller for now, and migrate code to controller-manager as part of a larger refactoring.

The address space controller will collect statistics about connectors and attach to address space status. 

==== Standard controller

The standard controller will collect statistics about forwarders and attach to address status.

==== Agent

For each forwarder on an address, the agent will create a connector from the broker to the remote address. 

== Testing

* Set up an AMQP broker (i.e. Artemis) on a remote host
* Configure an address space with connectors and create addresses with forwarders for the 4 different use cases listed initially

=== List of functionalities/behaviours to test:
* [tested] Sending messages to a remote AMQP endpoint via a local address space - by creating a connector and using prefixing
* [tested] Receiving messages from a remote AMQP endpoint via a local address space - by creating a connector and using prefixing
* [tested] config a connector to refer to a host that does not exist. addressspace should report ready true and the connector's status should report the failure.
* [tested] invalid connector names (ie: using / in connector name)
* [tested] invalid patterns in address rule in connector (ie: queue*)
* [tested] Restart broker to ensure router reattached to broker and you can send/recv messages
* use TLS
* Using mutual TLS (SASL EXTERNAL) instead of credentials
* [tested] Forwarding messages from a local queue in a local address space to a destination on a remote AMQP endpoint
* [tested] Forwarding messages to a local queue in a local address space from a destination on a remote AMQP endpoint
* forward to FULL remote queue
* forward to FULL local queue
* [tested] try to forward messages when the remote broker is unavailable , and check how the messages are automatically forwarded when the remote broker comes back up

== Documentation

The addifional fields should be added to the address space reference, and the tenant guide should be extended to cover the use cases as a realistic scenario with examples.
