== Overview

Address spaces in EnMasse are currently isolated, i.e. they don't share infrastructure (router network, brokers). Moreover, the standard-controller and agent deployments are created per address space. Sharing infrastructure allows sharing resources and reducing the footprint when configuring multiple address spaces, and speed up the time to provision new address spaces. Furthermore, the split between `standard` and `brokered` address space types has caused a lot of quirks in the architecture, which a shared address space type may handle in a better way.

See the initial discussion in issue #3420 for more details on alternatives. This document will consider the alternative with a new address space type for shared infra.

== Design

A new address space type `shared` is introduced. This address space type will not be handled by the `address-space-controller`, which will have a filter to avoid processing such address spaces. Eventually, allow `type` field of an address space to be omitted, and make the absence of this field indicate that the `shared` type should be used.

The `AddressSpacePlan` will also have the 'shared' addressSpaceType. A new field `messagingInfraRef` can refer to a new CRD type instace, `MessagingInfra`. This new type will contain configuration for both brokers and router.

The infrastructure is deployed is when the `MessagingInfra` instance is created. Alternatively, it could be deployed on-demand when an address space referencing it is created. This behavior could potentially be configurable to give the service admins more control.

Example:

```
apiVersion: admin.enmasse.io/v1beta1
kind: MessagingInfra
metadata:
  name: infra1
spec:
  router:
    image: # Optional. Allows overriding router image

    replicas:
      min: 2 # Min replicas will be deployed when infra is created
      max: 3 # Max replicas that maybe scaled to
      minReady: 1 # Allows 1 router to not be ready before alerting

    topology: mesh | ring # Optional (default: mesh) How routers should be connected.

    # Optional (default: 1 entry with defaults set). Allows creating additional router groups, each with identical group configuration applied. Strict anti-affinity rules based on name will be applied to each group to enforce they are not running in the same zone
    groups: 
    - name: grp1
      linkWeight: 30 # Optional (default: same as internal weight). Allows controlling the weight of links to other router groups
    - name: grp2
      linkWeight: 60

    linkWeight: 100 # The weight of internal router links
    podTemplate: # Same as in standard infra config today. Based on Kubernetes spec
      spec:
        affinity: # Allow setting affinity rules to ensure routers do not run the same node etc.
        tolerations: # Allow enforcing which nodes to run on
        resources: # Memory and CPU settings
        priorityClassName: # Pod priority settings

    ... # Other router settings - same as in StandardInfraConfig, except vhost policies (which are derived per address space plan)

  brokers:
    image: # Optional. Allows overriding broker image
    min: 1 // Can be > 0 to pre-create brokers
    max: 5 // Will never create more brokers than this
    replicas: 1 // Must be >= 1, defaults to 1. Larger values creates HA replicas
    addressFullPolicy: BLOCK
    storageClassName: #

    podTemplate:
      metadata:
      spec:
        affinity:
        tolerations:
        resources:
        priorityClassName:
     
    ... # Other broker settings - ensure 
```

When deployed, the above would have the minimum impact of creating 3 routers and 1 brokers. The brokers may be configured according to the address spaces they need to support.

An `AddressSpacePlan` currently refers to router and broker credits to control the 'quota' of address spaces. With shared infra, the numbers would either have to change their meaning, or one could reithink and extend the schema.

For instance, address space limits can be expressed in more specific terms that map to the routers per vhost policies:

* connections
* links per connection

In addition, operator limits such as number of addresses can be specified:

* number of addresses

Moreover, a split into requests and limits similar to Kubernetes resources is used to allow the operator to calculate the cost of applying plans vs. infrastructure capacity when creating the plan, as well as the cost of applying the plan.

The `AddressSpacePlan` would then look like this:

```
apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: shared-small
spec:
  messagingInfraRef: shared1 // Plans may refer to the same infra - this means address spaces will run on the same infra
  resources:
    requests:
      addresses: 10
      connections: 1
    limits:
      addresses: 100
      connections: 10
      linksPerConnection: 2
```

This would be easier to understand and reason about than fractions. It is also easier to relate the impact of those limits to the shared infra, and allow the limits to be enforced. It would allow a shared infra to support address space plans with different limits in place. 

NOTE: Plans for existing address space types would continue to use the existing schema.

For routers and brokers, the shared infra has some potential for auto-scaling. It would be the responsibility of the enmasse-operator to scale the infrastructure within the bounds set by the `MessagingInfra`, which could be based on cpu and memory usage, or the limits defined in the address space plans.

Address spaces may also contain properties to indicate what sort of broker that needs to be used for the addresses:

```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: shared
  properties:
    transactions: true
```

The operator will ensure that addresses for this address space is always link-routed and put on the same broker (and HA replicas).

Address plans allow properties to indicate the desired guarantees of a queue such as message ordering, transaction support etc. An example address plan would be:

```
apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: small-queue
spec:
  addressType: queue
  properties:
  
  resources:
    requests:
      queueDepth: 3
    limits:
      queueDepth: 10

  allowOverrides: true # true means addresses are allowed to override properties
  properties:
    partitions: # Specifying a min and max allow the operator to make a decisions to split queue across multiple brokers to fit it. Setting max >= 1 may cause message affects message ordering
      min: 1
      max: 2
    ttl: 60s
    # Create these addresses on the same broker (requirements same as for this address)
    expiryQueue: exp1
    deadLetterQueue: dlq1
    
```

Addresses allow setting the same properties as the plan, if permitted:

```
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: myspace.addr1
spec:
  address: addr1
  type: queue
  plan: small-queue
  properties:
    ttl: 1200s
```

The set of properties for a given address will drive the placement of that queue, either on a link-routed broker, or across a set of brokers.

This can be translated to limits that can be enforced in the broker, and that can be reasoned about from a sizing perspective. Properties specified on an `Address` may also be specified on an `AddressPlan`, and the plan may restrict if properties can be overridden or not.

NOTE: Plans for existing address types would continue to use the existing schema.

The following components will not be part of shared infra:

* MQTT Gateway
* MQTT LWT
* Subserv
* Address-space-controller
* Agent
* Standard-controller
* Topic-forwarder (The implication is that partitioned/sharded topics will not be supported - at least initially)

=== Phase 1 (Milestone 0.32.0 ?)

Add support for shared infra address space type and implement basic features similar to standard address space.

The `MessagingInfra` resource would be managed by the enmasse-operator, which will do a reconciliation of deployments, services etc. The router-operator should be used to deploy and manage the dispatch router to simplify the interface. Depending on the maturity of the broker-operator, it should be used to deploy the brokers.

The `AddressSpace` resource of type `shared` will be managed by a controller in enmasse-operator. The controller will create vhost policies in the shared router infra for each address space, and apply restrictions as specified in the address space plan.

The `Address` resource for `shared` address space types will be managed by a controller in enmasse-operator. The controller will watch all addresses across all address spaces, and apply the needed address configuration to brokers and routers using AMQP management.

After the first phase, the following would be supported:

* Deploy shared infra using the `MessagingInfra` resource
* Creating 1 or more address spaces per shared infra
* Anycast, multicast, queue and non-sharded topics supported (no transactions etc. yet)
* Management using AMQ console

The following would NOT be supported:

* Connectors and forwarders
* Broker-semantics for addresses
* Configure per-address space limits
* Configure per-address limits
* MQTT, Core, STOMP

=== Phase 2 (Milestone 0.33.0 ?)

The second phase will expand the supported features of the shared infra. The shared infra will gain support for deploying broker clusters and assign addresses requiring a broker cluster to them.

After the second phase, the following would be supported as well:

* Connectors and forwarders
* Configure per-address space limits
* Configure per-address limits
* Broker-semantics for addresses - allow 'transactional' address spaces
* Deprecate standard

The following would NOT be supported:
* MQTT, Core, STOMP

=== Phase 3 (Milestone 0.34.0 ?)

* The missing protocol support could be addressed in some way.
* Handle migration from `brokered` and `standard` to `shared`, potentially as part of the enmasse-operator
* Deprecate brokered

=== Phase 4 (Milestone 0.X.0 ?)

Phase 4 would mainly involve removing `brokered` and `standard`, once the oldest version supported in upgrades has deprecated brokered and standard.

* Remove brokered and standard address space types
* Removal of address space `type` field
* Removal of BrokeredInfraConfig and StandardInfraConfig CRDs

== Testing

A new class of tests for shared infra should be created. The address-space-specific tests should be able to reuse the infra to speed up testing. Some tests would still need to be written to test that one can run multiple shared infra instances.

A load-test is also essential to ensure that the operator can handle a large number of address spaces and addresses.

== Documentation

The shared address space will cause a lot of changes to the documentation, and it might be good to create a separate chapter for both service admin and messaging tenant related to shared infra specifically. 