{
 "title": "EnMasse",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "60s",
 "panels": [
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "targets": [
    { "expr": "health" }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    { "expr": "version" }
   ]
  }
 ]
}