apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: grafana-config
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-k8s:9090
      jsonData:
        timeInterval: 60s
    - name: AlertManager
      type: camptocamp-prometheus-alertmanager-datasource
      url: http://alertmanager-main:9093
      access: proxy
      jsonData:
        timeInterval: 60s
        severity_critical: "4"
        severity_high: "3"
        severity_warning: "2"
        severity_info: "1"
      editable: true
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'EnMasse'
      org_id: 1
      folder: ''
      type: 'file'
      options:
        path: '/etc/grafana/dashboards'
