{
 "title": "Routers",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "router_set", "label": "router_set", "query": "label_values(job)" },
   { "name": "router", "label": "router", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Routers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(up{pod=~\"qdrouterd.+\"}) by (job)"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connections{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Links",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "links{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Addresses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "addresses{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Auto Links",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "auto_links{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Link Routes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "link_routes{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Presettled Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presettled_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Dropped Presettled Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dropped_presettled_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Accepted Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "accepted_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Released Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "released_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Rejected Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rejected_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Modified Deliveries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "modified_deliveries{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Deliveries Ingress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliveries_ingress{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Deliveries Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliveries_egress{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Deliveries Transit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliveries_transit{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Deliveries Ingress Route Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliveries_ingress_route_container{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  },
  {
   "title": "Deliveries Egress Route Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deliveries_egress_route_container{job=~\"[[router_set]]\",pod=~\"[[router]]\"}"
    }
   ]
  }
 ]
}