/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// AuthenticationServiceListerExpansion allows custom methods to be added to
// AuthenticationServiceLister.
type AuthenticationServiceListerExpansion interface{}

// AuthenticationServiceNamespaceListerExpansion allows custom methods to be added to
// AuthenticationServiceNamespaceLister.
type AuthenticationServiceNamespaceListerExpansion interface{}

// ConsoleServiceListerExpansion allows custom methods to be added to
// ConsoleServiceLister.
type ConsoleServiceListerExpansion interface{}

// ConsoleServiceNamespaceListerExpansion allows custom methods to be added to
// ConsoleServiceNamespaceLister.
type ConsoleServiceNamespaceListerExpansion interface{}
