/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	enmassev1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1"
	versioned "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/enmasseproject/enmasse/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/enmasseproject/enmasse/pkg/client/listers/enmasse/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MessagingPlanInformer provides access to a shared informer and lister for
// MessagingPlans.
type MessagingPlanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MessagingPlanLister
}

type messagingPlanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMessagingPlanInformer constructs a new informer for MessagingPlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMessagingPlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMessagingPlanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMessagingPlanInformer constructs a new informer for MessagingPlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMessagingPlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnmasseV1().MessagingPlans(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnmasseV1().MessagingPlans(namespace).Watch(options)
			},
		},
		&enmassev1.MessagingPlan{},
		resyncPeriod,
		indexers,
	)
}

func (f *messagingPlanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMessagingPlanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *messagingPlanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&enmassev1.MessagingPlan{}, f.defaultInformer)
}

func (f *messagingPlanInformer) Lister() v1.MessagingPlanLister {
	return v1.NewMessagingPlanLister(f.Informer().GetIndexer())
}
