#!/usr/bin/env groovy

pipeline {
    environment {
        STANDARD_JOB_NAME = 'enmasse-master-standard'
        BROKERED_JOB_NAME = 'enmasse-master-brokered'
        PLANS_JOB_NAME = 'enmasse-master-common'
        UPGRADE_JOB_NAME = 'enmasse-master-upgrade'
        IOT_JOB_NAME = 'enmasse-master-iot'
    }
//    parameters {
//        string(name: 'UPGRADE_FROM', defaultValue: '', description: 'upgrade from')
//    }
    options {
        ansiColor('xterm')
    }
    agent none
    stages {
        stage('execute brokered') {
            steps {
                build job: env.BROKERED_JOB_NAME, wait: false, parameters: [
                                [$class: 'StringParameterValue', name: 'BUILD_TAG', value: BUILD_TAG],
                                [$class: 'StringParameterValue', name: 'TEST_CASE', value: 'brokered.**'],
                        ]
            }
        }
        stage('execute standard') {
            environment {
                ACTUAL_COMMIT = readFile('actual-commit.file')
            }
            steps {
                build job: env.STANDARD_JOB_NAME, wait: false, parameters: [
                                [$class: 'StringParameterValue', name: 'BUILD_TAG', value: BUILD_TAG],
                                [$class: 'StringParameterValue', name: 'TEST_CASE', value: 'standard.**'],
                        ]
            }
        }
        stage('execute common') {
            environment {
                ACTUAL_COMMIT = readFile('actual-commit.file')
            }
            steps {
                build job: env.PLANS_JOB_NAME, wait: false, parameters: [
                                [$class: 'StringParameterValue', name: 'BUILD_TAG', value: BUILD_TAG],
                                [$class: 'StringParameterValue', name: 'TEST_CASE', value: 'common.**'],
                        ]
            }
        }
        stage('execute upgrade') {
            environment {
                ACTUAL_COMMIT = readFile('actual-commit.file')
            }
            steps {
                build job: env.UPGRADE_JOB_NAME, wait: false, parameters: [
                        [$class: 'StringParameterValue', name: 'BUILD_TAG', value: BUILD_TAG],
                        [$class: 'StringParameterValue', name: 'TEST_CASE', value: 'common.upgrade.**'],
                        [$class: 'StringParameterValue', name: 'START_VERSION', value: params.UPGRADE_FROM],
                ]
            }
        }
        stage('execute iot') {
            environment {
                ACTUAL_COMMIT = readFile('actual-commit.file')
            }
            steps {
                build job: env.IOT_JOB_NAME, wait: false, parameters: [
                        [$class: 'StringParameterValue', name: 'BUILD_TAG', value: BUILD_TAG],
                        [$class: 'BooleanParameterValue', name: 'DEPLOY_IOT', value: true],
                        [$class: 'StringParameterValue', name: 'TEST_CASE', value: 'iot.**'],
                ]
            }
        }
    }
}
