[id='getting-started-configuring-addresses-{context}']
= Configuring addresses

{ProductName} is configured with a set of addresses that you can use for messages. Currently, {ProductName} supports four different address types for the `standard` address space:

* Brokered queues
* Brokered topics (pub/sub)
* Direct anycast addresses
* Direct broadcast addresses

For more details, see xref:con-address-space-messaging[address space]. {ProductName} also comes with a console that you can use for managing addresses.

{ProductName} supports managing addresses natively in {PlatformName}.

.Procedure

. Create an address list definition
+
[source,yaml,options="nowrap"]
.link:standard-addresses.yaml[standard-addresses.yaml]
----
include::standard-addresses.yaml[]
----

. Create the addressses
+
[options="nowrap",subs="attributes"]
----
{cmdcli} create -f standard-addresses.yaml
----
+
The addresses are ready when the field `.status.isReady` is set to true.

. Check status of addressses
+
[options="nowrap",subs="attributes"]
----
{cmdcli} get addresses -o jsonpath={.items[*].status.isReady}
----
