apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-broker-admin-reader
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:admin-reader
subjects:
- kind: ServiceAccount
  name: service-broker
  namespace: ${NAMESPACE}
