/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/enmasseproject/enmasse/pkg/apis/iot/v1"
	"github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type IotV1Interface interface {
	RESTClient() rest.Interface
	IoTConfigsGetter
	IoTTenantsGetter
}

// IotV1Client is used to interact with features provided by the iot.enmasse.io group.
type IotV1Client struct {
	restClient rest.Interface
}

func (c *IotV1Client) IoTConfigs(namespace string) IoTConfigInterface {
	return newIoTConfigs(c, namespace)
}

func (c *IotV1Client) IoTTenants(namespace string) IoTTenantInterface {
	return newIoTTenants(c, namespace)
}

// NewForConfig creates a new IotV1Client for the given config.
func NewForConfig(c *rest.Config) (*IotV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &IotV1Client{client}, nil
}

// NewForConfigOrDie creates a new IotV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *IotV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new IotV1Client for the given RESTClient.
func New(c rest.Interface) *IotV1Client {
	return &IotV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *IotV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
