== why

To change configuration for the standard or brokered address space today involves changing a
configmap containing the resource definition, which references templates with no schema validation
and checking. The underlying openshift templates which are stored in a configmap as key-value
pairs and can only be changed at deploy-time.

The settings that can be tuned, and that will have an effect when changed is not clear to spot, and
are scattered around in the template.

Finally, there is at present no mechanism for the service admin to upgrade the infrastructure
between different versions of EnMasse and even for changing configuration run-time.

== what/how

This proposal attempts to address these issues by defining a format for infrastructure configuration
that clearly states the configuration settings that are available for tuning. Multiple versions of
the configuration may exist in the system, and a particluar instance of a configuration is mapped to
one of the configuration versions.

Upgrades are handled by updating the version of the instance of the infrastructure, in which case a
controller will take steps to migrate the infra from one version to the next.

Optionally, address spaces may also be versioned to indicate what version of the infrastructure is
required to support it, but to begin with it is assumed that an address space can be served by any
version of the infrastructure.

Defining a syntax for configuring infrastructure makes the operational life running EnMasse simpler.
It also allows us to decouple definition of the infrastructure from the address space(s) that the
infrastructure serves.

A `StandardInfraTemplate` resource defines an infrastructure containing an admin component, a router and 0 or
more brokers. Settings for these components can be tuned through this resource. More settings that
is desired to be configurable can be added. The resource is versioned, and different versions may
coexist to allow seamless upgrades.


```
apiVersion: enmasse.io/v1alpha1
kind: StandardInfraTemplate
metadata:
  name: standard-infra-0.21.2
  namespace: somewhere
spec:
  version: 0.21.2
  router:
    replicas: 1
    linkCapacity: 1000
    allowDurableSubscriptions: false
    resources:
      memory: 512Mi
  broker:
    addressFullPolicy: FAIL
    resources:
      memory: 512Mi
      disk: 2Gi
  admin:
    resources:
      memory: 512Mi
```

A `BrokeredInfraTemplate` resource defines a cluster containing an admin component, and a single broker (with plans to allow replicas to be specified as well). Settings for these components can be tuned through this resource.

```
apiVersion: enmasse.io/v1alpha1
kind: BrokeredInfraTemplate
metadata:
  name: brokered-infra-0.21.2
  namespace: somewhere
spec:
    version: 0.21.2
  broker:
    addressFullPolicy: PAGE
    resources:
      memory: 2Gi
      disk: 50Gi
  admin:
    resources:
      memory: 512Mi
```

In order to decouple `AddressSpace`, which is a logical resource managed by tenants, an `Infra`
resource type is used to represent an instance of the above templates. This paves the way later for
allowing multiple `AddressSpace` resource to be shared by the same `Infra` resource.

An `Infra` resource is used to declare some infrastructure to be created based on a template
resource (+ authentication service settings?). A component `infra-controller` will watch for
resources of this kind and instantiate the necessary components as these resources are created.
Initially, there might as well be a 1:1 mapping between AddressSpace and Infra, with the distinction
that tenants can see `AddressSpace` resources, where as only service admins can see `Infra`
resources.

The `Infra` resource contains a `version` field, which indicates which version of the
`*InfraTemplate` the infrastructure should converge to. If the version changes, the
`infra-controller` will be responsible for converging the `Infra` instance towards the new version
based on the new template.

Here is an example of an `Infra` instance:

```
apiVersion: enmasse.io/v1alpha1
kind: Infra
metadata:
  name: infra
  namespace: myinfra
spec:
  version:  0.21.1
  template:
    kind: StandardInfraTemplate
    name: standard-infra
  authenticationService:
    host: example.com
    port: 5671
    caBundle: // Base64 encoded CA cert
```

As a first step, AddressSpacePlans can still contain the 'defined-by' annotation which can refer to
a StandardInfraTemplate or a BrokeredInfraTemplate. When an address-space is created, this can be
the way to find which template is used for creating the `Infra` resource.

== testing

Tests would have to include defining multiple versions of templates with different settings, update
the `Infra` instance version, and verify that all components have been upgraded.

== documentation

The service admin documentation should include how to create the infra templates, how to upgrade
instances, how to verify that the upgrade is complete.
