apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adress-space-controller-admin
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: ${NAMESPACE}
