/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAddressSpaceSchemas implements AddressSpaceSchemaInterface
type FakeAddressSpaceSchemas struct {
	Fake *FakeEnmasseV1beta1
}

var addressspaceschemasResource = schema.GroupVersionResource{Group: "enmasse.io", Version: "v1beta1", Resource: "addressspaceschemas"}

var addressspaceschemasKind = schema.GroupVersionKind{Group: "enmasse.io", Version: "v1beta1", Kind: "AddressSpaceSchema"}

// Get takes name of the addressSpaceSchema, and returns the corresponding addressSpaceSchema object, and an error if there is any.
func (c *FakeAddressSpaceSchemas) Get(name string, options v1.GetOptions) (result *v1beta1.AddressSpaceSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(addressspaceschemasResource, name), &v1beta1.AddressSpaceSchema{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AddressSpaceSchema), err
}

// List takes label and field selectors, and returns the list of AddressSpaceSchemas that match those selectors.
func (c *FakeAddressSpaceSchemas) List(opts v1.ListOptions) (result *v1beta1.AddressSpaceSchemaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(addressspaceschemasResource, addressspaceschemasKind, opts), &v1beta1.AddressSpaceSchemaList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AddressSpaceSchemaList{ListMeta: obj.(*v1beta1.AddressSpaceSchemaList).ListMeta}
	for _, item := range obj.(*v1beta1.AddressSpaceSchemaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested addressSpaceSchemas.
func (c *FakeAddressSpaceSchemas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(addressspaceschemasResource, opts))
}

// Create takes the representation of a addressSpaceSchema and creates it.  Returns the server's representation of the addressSpaceSchema, and an error, if there is any.
func (c *FakeAddressSpaceSchemas) Create(addressSpaceSchema *v1beta1.AddressSpaceSchema) (result *v1beta1.AddressSpaceSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(addressspaceschemasResource, addressSpaceSchema), &v1beta1.AddressSpaceSchema{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AddressSpaceSchema), err
}

// Update takes the representation of a addressSpaceSchema and updates it. Returns the server's representation of the addressSpaceSchema, and an error, if there is any.
func (c *FakeAddressSpaceSchemas) Update(addressSpaceSchema *v1beta1.AddressSpaceSchema) (result *v1beta1.AddressSpaceSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(addressspaceschemasResource, addressSpaceSchema), &v1beta1.AddressSpaceSchema{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AddressSpaceSchema), err
}

// Delete takes name of the addressSpaceSchema and deletes it. Returns an error if one occurs.
func (c *FakeAddressSpaceSchemas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(addressspaceschemasResource, name), &v1beta1.AddressSpaceSchema{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAddressSpaceSchemas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(addressspaceschemasResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.AddressSpaceSchemaList{})
	return err
}

// Patch applies the patch and returns the patched addressSpaceSchema.
func (c *FakeAddressSpaceSchemas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AddressSpaceSchema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(addressspaceschemasResource, name, pt, data, subresources...), &v1beta1.AddressSpaceSchema{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AddressSpaceSchema), err
}
