#!/bin/bash

# This script is for deploying EnMasse into Kubernetes. The target of
# installation can be an existing Kubernetes deployment or an all-in-one
# container can be started.
#
# In either case, access to the `kubectl` command is required.
#
# example usage:
#
#    $ deploy-kubernetes.sh -c 10.0.1.100 -l
#
# this will deploy EnMasse into the Kubernetes master running at 10.0.1.100
# and apply the external load balancer support for Azure, AWS etc.  For further
# parameters please see the help text.

if which kubectl &> /dev/null
then :
else
    echo "Cannot find kubectl command, please check path to ensure it is installed"
    exit 1
fi

SCRIPTDIR=`dirname $0`
TEMPLATE_PARAMS=""
ENMASSE_TEMPLATE=$SCRIPTDIR/kubernetes/enmasse.yaml
KEYCLOAK_TEMPLATE=$SCRIPTDIR/kubernetes/addons/keycloak.yaml
KEYCLOAK_TEMPLATE_PARAMS=""
DEFAULT_NAMESPACE=enmasse
GUIDE=false

while getopts dgk:lm:n:t:vh opt; do
    case $opt in
        d)
            ALLINONE=true
            ;;
        g)
            GUIDE=true
            ;;
        k)
            KEYCLOAK_PASSWORD=$OPTARG
            ;;
        l)
            EXTERNAL_LB=true
            ;;
        m)
            MASTER_URI=$OPTARG
            ;;
        n)
            NAMESPACE=$OPTARG
            ;;
        t)
            ALT_TEMPLATE=$OPTARG
            ;;
        v)
            set -x
            ;;
        h)
            echo "usage: deploy-kubernetes.sh [options]"
            echo
            echo "deploy the EnMasse suite into a running Kubernetes cluster"
            echo
            echo "optional arguments:"
            echo "  -h                   show this help message"
            echo "  -d                   create an all-in-one minikube VM on localhost"
            echo "  -k KEYCLOAK_PASSWORD Deploy standard authentication service (keycloak) and use given password as admin password"
            echo "  -m MASTER            Kubernetes master URI to login against (default: https://localhost:8443)"
            echo "  -n NAMESPACE         Namespace to deploy EnMasse into (default: $DEFAULT_NAMESPACE)"
            echo "  -o HOSTNAME          Custom hostname for messaging endpoint (default: use autogenerated from template)"
            echo "  -t TEMPLATE          An alternative Kubernetes template file to deploy EnMasse"
            echo
            exit
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

source $SCRIPTDIR/common.sh
TEMPDIR=`tempdir`

if [ -z "$NAMESPACE" ]
then
    NAMESPACE=$DEFAULT_NAMESPACE
fi

e=`kubectl get namespace ${NAMESPACE} 2> /dev/null`
if [ $? -gt 0 ]; then
    runcmd "kubectl create namespace $NAMESPACE" "Create namespace $NAMESPACE"
fi

if [ -n "$ALLINONE" ]
then
    if [ -n "$MASTER_URI" ]
    then
        echo "Error: You have requested an all-in-one deployment AND specified a cluster address."
        echo "Please choose one of these options and restart."
        exit 1
    fi
    runcmd "minikube start" "Start local minikube cluster"
    runcmd "minikube addons enable ingress" "Enabling ingress controller"
fi

runcmd "kubectl create sa enmasse-service-account -n $NAMESPACE" "Create service account for address controller"

CA_KEY=${TEMPDIR}/ca.key
CA_CERT=${TEMPDIR}/ca.crt
runcmd "openssl req -new -x509 -batch -nodes -days 11000 -subj \"/O=io.enmasse/CN=enmasse\" -out ${CA_CERT} -keyout ${CA_KEY}" "Create self-signed certificate"
fix_key_file_format ${CA_KEY}
create_tls_secret "kubectl" "enmasse-ca" $CA_KEY $CA_CERT

create_and_sign_cert "kubectl " $CA_KEY $CA_CERT "address-controller.${NAMESPACE}.svc.cluster.local" "address-controller-cert"
create_self_signed_cert "kubectl" "none-authservice.${NAMESPACE}.svc.cluster.local" "none-authservice-cert"

if [ -n "$KEYCLOAK_PASSWORD" ]; then
    create_self_signed_cert "kubectl" "standard-authservice.${NAMESPACE}.svc.cluster.local" "standard-authservice-cert"
    runcmd "kubectl create secret generic keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password=$KEYCLOAK_PASSWORD -n $NAMESPACE" "Create secret with keycloak admin credentials"
    runcmd "kubectl apply -f $KEYCLOAK_TEMPLATE -n $NAMESPACE" "Deploy Keycloak to $NAMESPACE"
fi

if [ -n "$ALT_TEMPLATE" ]
then
    ENMASSE_TEMPLATE=$ALT_TEMPLATE
fi

runcmd "kubectl apply -f $ENMASSE_TEMPLATE -n $NAMESPACE" "Deploy EnMasse to $NAMESPACE"

if [ "$EXTERNAL_LB" == "true" ]
then
    runcmd "kubectl apply -f kubernetes/addons/external-lb.yaml -n $NAMESPACE"
fi
