apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:enmasse-operator
  labels:
    app: enmasse
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "update", "patch", "get", "list" ]
  - apiGroups: [ "oauth.openshift.io" ]
    resources: [ "oauthclients" ]
    verbs: [ "create", "get", "update", "list", "watch" ]
  - apiGroups: [ "user.enmasse.io" ]
    resources: [ "messagingusers", "messagingusers/finalizers", "messagingusers/status" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotprojects", "iotprojects/finalizers", "iotprojects/status" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addressspaces", "addresses" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices" ]
    resourceNames: [ "v1alpha1.enmasse.io", "v1beta1.enmasse.io", "v1alpha1.user.enmasse.io", "v1beta1.user.enmasse.io" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ "prometheusrules", "servicemonitors" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "integreatly.org" ]
    resources: [ "grafanadashboards", "grafanadashboards/finalizers" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "console.openshift.io" ]
    resources: [ "consolelinks" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
