apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: standard-unlimited-with-mqtt
  labels:
    app: enmasse
spec:
  displayName: Unlimited With MQTT
  displayOrder: 0
  infraConfigRef: default-with-mqtt
  shortDescription: Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis and MQTT support.
  longDescription: Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis and MQTT support. This plan allows an unlimited number of routers (minimum 2) and brokers, and is suitable for applications where you do not want to impose any restrictions.
  addressSpaceType: standard
  resourceLimits:
    router: 10000.0
    broker: 10000.0
    aggregate: 10000.0
  addressPlans:
    - standard-small-anycast
    - standard-medium-anycast
    - standard-large-anycast
    - standard-small-multicast
    - standard-medium-multicast
    - standard-large-multicast
    - standard-small-queue
    - standard-medium-queue
    - standard-large-queue
    - standard-xlarge-queue
    - standard-small-partitioned-queue
    - standard-medium-partitioned-queue
    - standard-large-partitioned-queue
    - standard-small-topic
    - standard-medium-topic
    - standard-large-topic
    - standard-xlarge-topic
    - standard-small-subscription
    - standard-medium-subscription
    - standard-large-subscription
