---
kind: IoTProject
apiVersion: iot.enmasse.io/v1alpha1
metadata:
  name: default
spec:
  downstreamStrategy:
    providedStrategy:
      namespace: hono
      addressSpaceName: default
      username: http
      password: http-secret
  