/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	enmassev1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMessagingPlans implements MessagingPlanInterface
type FakeMessagingPlans struct {
	Fake *FakeEnmasseV1
	ns   string
}

var messagingplansResource = schema.GroupVersionResource{Group: "enmasse.io", Version: "v1", Resource: "messagingplans"}

var messagingplansKind = schema.GroupVersionKind{Group: "enmasse.io", Version: "v1", Kind: "MessagingPlan"}

// Get takes name of the messagingPlan, and returns the corresponding messagingPlan object, and an error if there is any.
func (c *FakeMessagingPlans) Get(name string, options v1.GetOptions) (result *enmassev1.MessagingPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(messagingplansResource, c.ns, name), &enmassev1.MessagingPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*enmassev1.MessagingPlan), err
}

// List takes label and field selectors, and returns the list of MessagingPlans that match those selectors.
func (c *FakeMessagingPlans) List(opts v1.ListOptions) (result *enmassev1.MessagingPlanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(messagingplansResource, messagingplansKind, c.ns, opts), &enmassev1.MessagingPlanList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &enmassev1.MessagingPlanList{ListMeta: obj.(*enmassev1.MessagingPlanList).ListMeta}
	for _, item := range obj.(*enmassev1.MessagingPlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested messagingPlans.
func (c *FakeMessagingPlans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(messagingplansResource, c.ns, opts))

}

// Create takes the representation of a messagingPlan and creates it.  Returns the server's representation of the messagingPlan, and an error, if there is any.
func (c *FakeMessagingPlans) Create(messagingPlan *enmassev1.MessagingPlan) (result *enmassev1.MessagingPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(messagingplansResource, c.ns, messagingPlan), &enmassev1.MessagingPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*enmassev1.MessagingPlan), err
}

// Update takes the representation of a messagingPlan and updates it. Returns the server's representation of the messagingPlan, and an error, if there is any.
func (c *FakeMessagingPlans) Update(messagingPlan *enmassev1.MessagingPlan) (result *enmassev1.MessagingPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(messagingplansResource, c.ns, messagingPlan), &enmassev1.MessagingPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*enmassev1.MessagingPlan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMessagingPlans) UpdateStatus(messagingPlan *enmassev1.MessagingPlan) (*enmassev1.MessagingPlan, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(messagingplansResource, "status", c.ns, messagingPlan), &enmassev1.MessagingPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*enmassev1.MessagingPlan), err
}

// Delete takes name of the messagingPlan and deletes it. Returns an error if one occurs.
func (c *FakeMessagingPlans) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(messagingplansResource, c.ns, name), &enmassev1.MessagingPlan{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMessagingPlans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(messagingplansResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &enmassev1.MessagingPlanList{})
	return err
}

// Patch applies the patch and returns the patched messagingPlan.
func (c *FakeMessagingPlans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *enmassev1.MessagingPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(messagingplansResource, c.ns, name, pt, data, subresources...), &enmassev1.MessagingPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*enmassev1.MessagingPlan), err
}
