== scope

=== address controller api

This is the HTTP based API allowing address spaces to be created and
deleted and the addresses within those to be defined.  The
address-controller component will authenticate requests against the
openshift/kubernetes userbase, presumably using OAuth tokens supplied
in the HTTP headers.

=== service broker/service catalogue

The service broker implementation is part of the address
controller. This really just represents a slightly different API into
the same functionality for managing addresses and
address-spaces. Again requests would be authenticated against the
openshift/kubernetes userbase (as when using the service catalog in
openshift, the requests would be made as the principal with which the
openshift console user is logged in).

=== enmasse console

The console is a per address-space service and will authenticate
against the address-spaces userbase. For users with appropriate
permission it will allow creation or deletion of addresses via the
address-controller API for which it will use a service account it has
been configured with.

=== router & gateways

These are responsible for authenticating AMQP and MQTT connections. At
present all enforcement is actually done at the router level. The MQTT
gateway merely passes on the credentials it receives for each
connection.

=== internal components

Internal components authenticated using client certificates signed by
an internal CA. Verify: this is a per address-space CA?

== sasl delegating mechanism

TODO: Rob

== console authorisation

== configuring authentication for an address-space

Three options presented to user:

1. No authentication
2. Use enmasse authentication service
3. Use external authentication service

Deploy two authentication services along with address controller:

1. simple null service that always allows access
  * used for no authentication option above
2. keycloak instance with plugins
  * used for enmasse authentication option above
  * need to setup keycloak realm per address space with admin user

TODO: Need to update the address model to include the necessary
configuration details for the authentication service to use in the
address space resource schema. This includes host and port, but may
also be a CA cert for verifying the authentication services
certificate.

....
diff --git a/documentation/address-model/resource-definitions.md b/documentation/address-model/resource-definitions.md
index 8c5aab3..1cdfacf 100644
--- a/documentation/address-model/resource-definitions.md
+++ b/documentation/address-model/resource-definitions.md
@@ -43,6 +43,15 @@ The `AddressSpace` resource defines the type of address space and endpoint for c
                     "secretName": "mysecret"
                 }
             }
+        },
+
+        "authenticationService": { //Optional,
+                                   //if no authenticationService is provided it will be assumed no authentication is required,
+                                   //if an empty object is specified the dfeault enmasse authentication service is assumed
+                                   //TODO: verify that distinguishing between null and empty object is not a problem for address controller
+            "host": "myhost",
+            "port": 5672,
+            "caCertSecretName": "mysecret"
         }
     }
 }
....

The address controller will allow the authentication service to be
specified, and will set environment variables in the router deployment
describing the host and port and path to the CA cert to use. The CA
cert will be injected as a secret.

== testing

Automated system tests to cover authentication functionality.  test will cover EnMasse Authentication Service and No
Authentication.  External Authentication Service need not be covered through automated system tests as it is identical
from the point of view of an individual address space, and (by definition) an external authentication service is not
part of EnMasse.

[NOTE]
System tests will need to be able to support creation / deletion of address spaces on a per test (method) basis


=== Testing Messaging Client Authentication

==== EnMasse Authentication Service

* Validate successful authentication with enmasse authentication service and valid credentials
 . create an address space `A` which uses the enmasse authentication service
 . add a user `U` with password `P` to the Keycloak domain for `A` (using Keycloak API)
 . verify that AMQP & MQTT messaging clients can establish a connection to `A` using username `U` and password `P`
 . create an address space `B` which uses the enmasse authentication service
 . add a user `U` with password `X` to the Keycloak domain for `B`
 . verify that AMQP & MQTT messaging clients can still establish a connection to `A` using username `U` and password `P`

* Validate unsuccessful authentication with enmasse authentication service with no credentials
 . create an address space `A` which uses the enmasse authentication service
 . verify that AMQP & MQTT messaging clients cannot establish a connection without credentials
 . add a user `U` with password `P` to the Keycloak domain for `A`
 . verify that AMQP & MQTT messaging clients still cannot establish a connection without credentials

* Validate unsuccessful authentication with enmasse authentication service with incorrect credentials
 . create an address space `A` which uses the enmasse authentication service
 . verify that AMQP & MQTT messaging clients cannot establish a connection to `A` using username `U` and password `P`
 . add a user `U` with password `P` to the Keycloak domain for `A`
 . verify that AMQP & MQTT messaging clients cannot establish a connection to `A` using username `U` and password `X`
 . verify that AMQP & MQTT messaging clients cannot establish a connection to `A` using username `V` and password `P`
 . create an address space `B` which uses the enmasse authentication service
 . add a user `U` with password `X` to the Keycloak domain for `B`
 . verify that AMQP & MQTT messaging clients cannot establish a connection to `A` using username `U` and password `X`
 . verify that AMQP & MQTT messaging clients cannot establish a connection to `B` using username `U` and password `P`

==== No Authentication

* Validate successful authentication with no authentication
 . create an address space `A` which uses the enmasse authentication service
 . verify that AMQP & MQTT messaging clients can establish a connection to address space `A` without credentials
 . verify that AMQP & MQTT messaging clients can establish a connection to address space `A` using username `U` and password `P`
 . create an address space `B` which uses the enmasse authentication service
 . verify that AMQP & MQTT messaging clients can still establish a connection to address space `A` without credentials
 . verify that AMQP & MQTT messaging clients can still establish a connection to address space `A` using username `U` and password `P`

=== Testing Console Access

[NOTE]
Do we need to add some basic authz first, or do we just initially allow all users in the domain to have full access to the console?

=== Testing Address Controller / Service Broker

[NOTE]
Here we'll need to potentially have multiple sets of openshift credentials passed in to the tests / these users to be set up prior to the system test execution




