== scope

=== address controller api

This is the HTTP based API allowing address spaces to be created and
deleted and the addresses within those to be defined.  The
address-controller component will authenticate requests against the
openshift/kubernetes userbase, presumably using OAuth tokens supplied
in the HTTP headers.

=== service broker/service catalogue

The service broker implementation is part of the address
controller. This really just represents a slightly different API into
the same functionality for managing addresses and
address-spaces. Again requests would be authenticated against the
openshift/kubernetes userbase (as when using the service catalog in
openshift, the requests would be made as the principal with which the
openshift console user is logged in).

=== enmasse console

The console is a per address-space service and will authenticate
against the address-spaces userbase. For users with appropriate
permission it will allow creation or deletion of addresses via the
address-controller API for which it will use a service account it has
been configured with.

=== router & gateways

These are responsible for authenticating AMQP and MQTT connections. At
present all enforcement is actually done at the router level. The MQTT
gateway merely passes on the credentials it receives for each
connection.

=== internal components

Internal components authenticated using client certificates signed by
an internal CA. Verify: this is a per address-space CA?

== sasl delegating mechanism

TODO: Rob

== console authorisation

== configuring authentication for an address-space

Three options presented to user:

1. No authentication
2. Use enmasse authentication service
3. Use external authentication service

Deploy two authentication services along with address controller:

1. simple null service that always allows access
  * used for no authentication option above
2. keycloak instance with plugins
  * used for enmasse authentication option above
  * need to setup keycloak realm per address space with admin user

== testing

TODO: Rob
