== scope

There are three aspects of securing communications:

1. For internal clients to verify identity internal services
2. For internal services to verify identity of internal clients
3. For keycloak to verify clients and vice versa

=== Internal TLS mechanism 

For 1. and 2., there are a couple of alternatives for the mechanism.

==== Use certs for verifying service identities, and a sasl db for verifying client identities

Client verifies service identity using openshift generated certificates (uses an annotation on the
service). Services (i.e. the router) have a list of valid client credentials that they check against.

* Pros:
** CA signing handled automatically

* Cons:
** Client validation requires internal sasl db for internal users in router
** Might not be easy to use SASL by all components

==== Create per-address space CA that is used for generating per-service certificates

Client verifies service identity using address space CA. CN=internal service host name.  Services
(i.e. the router) validate clients via trusting the address space CA.

Address controller generates per-address space CA based on its own CA. Internal clients are verified
by the address controller implicitly (per-address space CAs are derived from 'global' address
controller CA). Address controller identity is verified by internal clients as its cert is signed by
the address space CA.

* Pros:
** Generic mechanism that works for all things that support TLS
** No requirement on using SASL
** We already have certificate generation being done in the address controller

* Cons:
** Address controller needs to know services that needs to have certs generated (an attempt at discovering through annotations is possible).

=== Verifying keycloak clients

TODO

=== Components and need for auth

Below is a list of components that either act as a client or server (or both). All of them needs to
have a certificate generated, but some of them have a bit different requirements.

==== Address Controller

* Internal ports: 5672, 8080, 8081
* External ports: 8080

The address controller has no internal ports, only external. The external port might be used by
internal components as well, in which case its cert should have both CN=address-controller.svc...
and CN=route host for its certificate. It might be easier if we just used 2 certs for it.

The AMQP port 5672 is not used by any component and should be considered for removal for time being.

==== Configserv

* Internal ports: 5672 (service) -> 5672 (pod)

The internal port should be secured and changed to 5671

==== Queue-scheduler

* Internal ports: 5672 (service) -> 55667 (pod)
* Connects to: configserv

The internal port should be secured and changed to 5671.

==== Router agent

* Internal ports: 5672 (service) -> 55672 (pod)
* Connects to: configserv

The internal port should be secured and changed to 5671

==== Console

* Internal ports: 5672 (service) -> 56720 (pod), 8080
* External ports: 8080
* Connects to: router agent, address-controller

Both ports should be secured with TLS.

==== Router

* Internal ports: 55673, 5672, 5671
* External ports: 5672, 5671
* Connects to: router agent, broker (if colocated), subserv

The router exposes 5672 and 5671 through routes. We can remove 5672 if we want to be strict (and
, it is useless as long as routes and ingress don't support non-TLS non-HTTP ports).

5671 needs to use both internal and external certs. 55673 needs to enable TLS. 

We should consider having subserv opening the connection to the router and not vice versa.

==== Router metrics

* Internal ports: 8080
* Connects to: router

Needs to enable TLS on metric collection and have cert trusted by hawkular-openshift-agent

==== Broker

* Internal ports: 5673, 61616, 8080
* Connects to: router, queue-scheduler (if not colocated)

The broker needs to support TLS for the outgoing connector. The incoming ports needs to be
TLS-enabled. Port 8080 is used by the metrics collector, and also needs to be TLS-enabled.

==== Topic-forwarder

* Connects to: broker

==== Keycloak

* Internal ports: 8080

==== None-authservice

* Internal ports: 8080

==== Keycloak-controller

* Connects to: keycloak

==== Subserv

* Internal ports: 5672
* Connects to: router, broker, configserv

==== Mqtt-gateway

* External ports: 1883, 8883
* Connects to: router, mqtt-lwt

==== Mqtt-lwt

* Connects to: router

