apiVersion: v1
kind: Service
metadata:
  name: iot-tenant-service
  labels:
    app: iot-registry
    deploymentconfig: iot-tenant-service
    enmasse-component: iot
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: iot-tenant-service-tls
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: amqps
      port: 5671
      targetPort: 5671
  selector:
    app: iot-registry
    deploymentconfig: iot-tenant-service
