apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan # align name with operator version
spec:
  ports:
  - port: 11222
    targetPort: 11222
    name: infinispan
  - port: 9990
    targetPort: 9990
    name: management
  selector:
    name: infinispan
    app: infinispan