apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinispan
  labels:
    app: infinispan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iot.enmasse.io:infinispan
subjects:
- kind: ServiceAccount
  name: infinispan
  namespace: ${NAMESPACE}
