---
apiVersion: v1
kind: Service
metadata:
  name: hono-service-auth
  labels:
    app: iot-core
    component: hono-service-auth
    enmasse-component: iot
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: hono-service-auth-tls
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    app: iot-core
    component: hono-service-auth