/*
 * Copyright 2018-2019, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1beta1"
	scheme "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AddressSpaceSchemasGetter has a method to return a AddressSpaceSchemaInterface.
// A group's client should implement this interface.
type AddressSpaceSchemasGetter interface {
	AddressSpaceSchemas(namespace string) AddressSpaceSchemaInterface
}

// AddressSpaceSchemaInterface has methods to work with AddressSpaceSchema resources.
type AddressSpaceSchemaInterface interface {
	Create(*v1beta1.AddressSpaceSchema) (*v1beta1.AddressSpaceSchema, error)
	Update(*v1beta1.AddressSpaceSchema) (*v1beta1.AddressSpaceSchema, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.AddressSpaceSchema, error)
	List(opts v1.ListOptions) (*v1beta1.AddressSpaceSchemaList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AddressSpaceSchema, err error)
	AddressSpaceSchemaExpansion
}

// addressSpaceSchemas implements AddressSpaceSchemaInterface
type addressSpaceSchemas struct {
	client rest.Interface
	ns     string
}

// newAddressSpaceSchemas returns a AddressSpaceSchemas
func newAddressSpaceSchemas(c *EnmasseV1beta1Client, namespace string) *addressSpaceSchemas {
	return &addressSpaceSchemas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the addressSpaceSchema, and returns the corresponding addressSpaceSchema object, and an error if there is any.
func (c *addressSpaceSchemas) Get(name string, options v1.GetOptions) (result *v1beta1.AddressSpaceSchema, err error) {
	result = &v1beta1.AddressSpaceSchema{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AddressSpaceSchemas that match those selectors.
func (c *addressSpaceSchemas) List(opts v1.ListOptions) (result *v1beta1.AddressSpaceSchemaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AddressSpaceSchemaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested addressSpaceSchemas.
func (c *addressSpaceSchemas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a addressSpaceSchema and creates it.  Returns the server's representation of the addressSpaceSchema, and an error, if there is any.
func (c *addressSpaceSchemas) Create(addressSpaceSchema *v1beta1.AddressSpaceSchema) (result *v1beta1.AddressSpaceSchema, err error) {
	result = &v1beta1.AddressSpaceSchema{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		Body(addressSpaceSchema).
		Do().
		Into(result)
	return
}

// Update takes the representation of a addressSpaceSchema and updates it. Returns the server's representation of the addressSpaceSchema, and an error, if there is any.
func (c *addressSpaceSchemas) Update(addressSpaceSchema *v1beta1.AddressSpaceSchema) (result *v1beta1.AddressSpaceSchema, err error) {
	result = &v1beta1.AddressSpaceSchema{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		Name(addressSpaceSchema.Name).
		Body(addressSpaceSchema).
		Do().
		Into(result)
	return
}

// Delete takes name of the addressSpaceSchema and deletes it. Returns an error if one occurs.
func (c *addressSpaceSchemas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *addressSpaceSchemas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("addressspaceschemas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched addressSpaceSchema.
func (c *addressSpaceSchemas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AddressSpaceSchema, err error) {
	result = &v1beta1.AddressSpaceSchema{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("addressspaceschemas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
