/*
 * Copyright 2020, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

const SET_SERVER_ERROR = "SET_SERVER_ERROR";
const RESET_SERVER_ERROR = "RESET_SERVER_ERROR";
const SET_NETWORK_ERROR = "SET_NETWORK_ERROR";
const RESET_NETWORK_ERROR = "RESET_NETWORK_ERROR";
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";

/**
 * address-space
 */
const DELETE_ADDRESS_SPACE = "DELETE_ADDRESS_SPACE";
const EDIT_ADDRESS_SPACE = "EDIT_ADDRESS_SPACE";
const CREATE_ADDRESS_SPACE = "CREATE_ADDRESS_SPACE";

/**
 * address
 */
const DELETE_ADDRESS = "DELETE_ADDRESS";
const PURGE_ADDRESS = "PURGE_ADDRESS";
const CREATE_ADDRESS = "CREATE_ADDRESS";
const EDIT_ADDRESS = "EDIT_ADDRESS";
const CLOSE_CONNECTIONS = "CLOSE_CONNECTIONS";

const types = {
  SET_SERVER_ERROR,
  RESET_SERVER_ERROR,
  SET_NETWORK_ERROR,
  RESET_NETWORK_ERROR,
  SHOW_MODAL,
  HIDE_MODAL
};

const MODAL_TYPES = {
  DELETE_ADDRESS_SPACE,
  EDIT_ADDRESS_SPACE,
  EDIT_ADDRESS,
  CREATE_ADDRESS_SPACE,
  DELETE_ADDRESS,
  PURGE_ADDRESS,
  CREATE_ADDRESS,
  CLOSE_CONNECTIONS
};

export { MODAL_TYPES, types };
