// Include an 'ID' that corresponds to the title of the procedure
// The ID will be used as an anchor for linking to the title
// Do not change the ID to make sure existing links keep working
[[procedure_template]]
= Procedure Template and Guidelines

_Start the title with a verb form, such as Creating or Create._

_Avoid using the word 'Configuring' over and over.  Other words might include:_

* _Specifying_
* _Adding_
* _Constructing_
* _Arranging_
* _Building_
* _Setting_
* _Managing_
* _Defining_
* _Customizing_
* _Or instead of using synonyms (which becomes obvious) 'verb-alize' a word and refactor the heading - limiting (instead of 'setting resource limits')_

_The standard for all headings and titles._

_A procedure module explains and lists actions that complete a small useful unit of work -- what a user must do to accomplish a goal. The list of actions is presented as numbered steps in a sequence that yields a successful result._

// Ideally, base the name of the file on the title to avoid confusion
// Use a consistent system for filenames and IDs, e.g.:
//  * Only substitute spaces with underscores
//  * Don't use any CAPS

This paragraph explains why the user performs the procedure, sets the context of the procedure, and may explain or list special considerations specific to this procedure. Keep the information brief and focused on what is needed for this specific procedure. Suggested length is 1 to 3 sentences, can be longer if needed.

.Prerequisites

* Sentence or a bulleted list of prerequisites that must be in place or done before the user starts this procedure.

* Delete section title and bullets if the procedure has no required prerequisites.

* Text can be a link to a prerequisite procedure that the user must do before starting this procedure.


.Procedure

_Put steps in a numbered list. The step sequence is important to a repeatable successful outcome._

. Start each step with an active verb, because each step corresponds to one user action.

. Include one command or action per step.

. Format the step line as an unnumbered bullet if the procedure includes only 1 step (exception to numbering the steps).

. Include one command or action per step.

. Include one command or action per step.


.Related Information

* Bulleted list of links to concept, reference, or procedure modules closely related to this procedure module.

* Include only the most relevant items as links, not every possible related item.

* Delete section title and bullets if no related information is needed.
